package neqsim.process.mechanicaldesign;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import neqsim.process.equipment.ProcessEquipmentInterface;
import neqsim.process.mechanicaldesign.SystemMechanicalDesign.EquipmentDesignSummary;
import neqsim.process.processmodel.ProcessSystem;

/**
 * Generates comprehensive mechanical design reports for a process system.
 *
 * <p>
 * This class provides various output formats for mechanical design deliverables:
 * </p>
 * <ul>
 * <li>Equipment List (CSV format for import to Excel/database)</li>
 * <li>Piping Line List with sizes and schedules</li>
 * <li>Weight Report with breakdowns by type and discipline</li>
 * <li>Equipment Data Sheets (summary format)</li>
 * </ul>
 *
 * @author NeqSim Development Team
 * @version 1.0
 */
public class MechanicalDesignReport implements java.io.Serializable {
  /** Serialization version UID. */
  private static final long serialVersionUID = 1000L;

  // ============================================================================
  // References
  // ============================================================================

  private ProcessSystem processSystem;
  private SystemMechanicalDesign systemDesign;
  private ProcessInterconnectionDesign pipingDesign;

  // ============================================================================
  // Constructor
  // ============================================================================

  /**
   * Constructor for MechanicalDesignReport.
   *
   * @param processSystem the process system to generate reports for
   */
  public MechanicalDesignReport(ProcessSystem processSystem) {
    this.processSystem = processSystem;
  }

  // ============================================================================
  // Report Generation Methods
  // ============================================================================

  /**
   * Run all design calculations to prepare data for reports.
   */
  public void runDesignCalculations() {
    // Run system mechanical design
    systemDesign = new SystemMechanicalDesign(processSystem);
    systemDesign.runDesignCalculation();

    // Run piping design
    pipingDesign = new ProcessInterconnectionDesign(processSystem);
    pipingDesign.calculatePipingEstimates();
  }

  /**
   * Generate equipment list in CSV format.
   *
   * @return CSV formatted equipment list
   */
  public String generateEquipmentListCSV() {
    if (systemDesign == null) {
      runDesignCalculations();
    }

    StringBuilder sb = new StringBuilder();

    // Header
    sb.append("Tag,Equipment Type,Description,");
    sb.append("Design Pressure (barg),Design Temperature (°C),");
    sb.append("Operating Pressure (barg),Operating Temperature (°C),");
    sb.append("Power (kW),Duty (kW),");
    sb.append("Dry Weight (kg),Operating Weight (kg),");
    sb.append("Length (m),Width (m),Height (m),");
    sb.append("Material,Remarks\n");

    // Equipment rows
    List<EquipmentDesignSummary> equipmentList = systemDesign.getEquipmentList();
    for (EquipmentDesignSummary equip : equipmentList) {
      sb.append(String.format("\"%s\",", equip.getName()));
      sb.append(String.format("\"%s\",", equip.getType()));
      sb.append(String.format("\"%s\",", getEquipmentDescription(equip)));
      sb.append(String.format("%.1f,%.1f,", equip.getDesignPressure() - 1.01325,
          equip.getDesignTemperature()));
      sb.append(String.format("%.1f,%.1f,", equip.getDesignPressure() / 1.1 - 1.01325,
          equip.getDesignTemperature() - 30.0));
      sb.append(String.format("%.1f,%.1f,", equip.getPower(), equip.getDuty()));
      sb.append(String.format("%.0f,%.0f,", equip.getWeight(), equip.getWeight() * 1.1));
      sb.append(
          String.format("%.2f,%.2f,%.2f,", equip.getLength(), equip.getWidth(), equip.getHeight()));
      sb.append("\"Carbon Steel\",");
      sb.append("\"Generated by NeqSim\"\n");
    }

    return sb.toString();
  }

  /**
   * Generate piping line list in CSV format.
   *
   * @return CSV formatted piping line list
   */
  public String generatePipingLineListCSV() {
    if (pipingDesign == null) {
      runDesignCalculations();
    }

    StringBuilder sb = new StringBuilder();

    // Header
    sb.append("Line Number,From,To,");
    sb.append("Nominal Size (in),OD (mm),Wall Thickness (mm),Schedule,");
    sb.append("Design Pressure (barg),Design Temperature (°C),");
    sb.append("Length (m),Weight (kg),");
    sb.append("Material,Service,Remarks\n");

    // Line rows
    List<ProcessInterconnectionDesign.PipeSegment> segments = pipingDesign.getPipeSegments();
    int lineNumber = 1;
    for (ProcessInterconnectionDesign.PipeSegment seg : segments) {
      sb.append(String.format("L-%03d,", lineNumber++));
      sb.append(String.format("\"%s\",\"%s\",", seg.getFromEquipment(), seg.getToEquipment()));
      sb.append(String.format("%.0f,%.1f,%.1f,\"%s\",", seg.getNominalSizeInch(),
          seg.getOutsideDiameterMm(), seg.getWallThicknessMm(), seg.getSchedule()));
      sb.append(String.format("%.1f,%.1f,", seg.getDesignPressureBara() - 1.01325,
          seg.getDesignTemperatureC()));
      sb.append(String.format("%.1f,%.0f,", seg.getLengthM(), seg.getWeightKg()));
      sb.append(String.format("\"%s\",", seg.getMaterial()));
      sb.append(String.format("\"%s\",", seg.isGasService() ? "Gas" : "Liquid/Two-Phase"));
      sb.append("\"Estimated\"\n");
    }

    return sb.toString();
  }

  /**
   * Generate weight report.
   *
   * @return formatted weight report
   */
  public String generateWeightReport() {
    if (systemDesign == null) {
      runDesignCalculations();
    }

    StringBuilder sb = new StringBuilder();
    String separator = repeat("=", 70);
    String subSeparator = repeat("-", 70);

    sb.append(separator).append("\n");
    sb.append("MECHANICAL DESIGN WEIGHT REPORT\n");
    sb.append("Process: ").append(processSystem.getName()).append("\n");
    sb.append(separator).append("\n\n");

    // Overall Summary
    sb.append("OVERALL SUMMARY\n");
    sb.append(subSeparator).append("\n");
    double equipWeight = systemDesign.getTotalWeight();
    double pipingWeight = pipingDesign.getTotalPipingWeight();
    double totalWeight = equipWeight + pipingWeight;
    sb.append(String.format("Equipment Weight:          %,12.0f kg (%,.1f tonnes)\n", equipWeight,
        equipWeight / 1000.0));
    sb.append(String.format("Piping Weight:             %,12.0f kg (%,.1f tonnes)\n", pipingWeight,
        pipingWeight / 1000.0));
    sb.append(String.format("TOTAL DRY WEIGHT:          %,12.0f kg (%,.1f tonnes)\n", totalWeight,
        totalWeight / 1000.0));
    sb.append("\n");

    // Weight by Equipment Type
    sb.append("WEIGHT BY EQUIPMENT TYPE\n");
    sb.append(subSeparator).append("\n");
    sb.append(String.format("%-25s %15s %15s\n", "Type", "Count", "Weight (kg)"));
    for (String type : systemDesign.getWeightByEquipmentType().keySet()) {
      int count = systemDesign.getEquipmentCountByType().get(type);
      double weight = systemDesign.getWeightByEquipmentType().get(type);
      sb.append(String.format("%-25s %15d %,15.0f\n", type, count, weight));
    }
    sb.append("\n");

    // Weight by Discipline
    sb.append("WEIGHT BY DISCIPLINE\n");
    sb.append(subSeparator).append("\n");
    for (String discipline : systemDesign.getWeightByDiscipline().keySet()) {
      double weight = systemDesign.getWeightByDiscipline().get(discipline);
      sb.append(String.format("%-25s %,15.0f kg\n", discipline, weight));
    }
    sb.append("\n");

    // Piping Breakdown
    sb.append("PIPING BREAKDOWN BY SIZE\n");
    sb.append(subSeparator).append("\n");
    sb.append(String.format("%-15s %15s %15s\n", "Size", "Length (m)", "Weight (kg)"));
    for (String size : pipingDesign.getWeightBySize().keySet()) {
      sb.append(String.format("%-15s %,15.0f %,15.0f\n", size,
          pipingDesign.getLengthBySize().get(size), pipingDesign.getWeightBySize().get(size)));
    }
    sb.append(
        String.format("%-15s %,15.0f %,15.0f\n", "Valves", 0.0, pipingDesign.getValveWeight()));
    sb.append(
        String.format("%-15s %,15.0f %,15.0f\n", "Flanges", 0.0, pipingDesign.getFlangeWeight()));
    sb.append(
        String.format("%-15s %,15.0f %,15.0f\n", "Fittings", 0.0, pipingDesign.getFittingWeight()));
    sb.append("\n");

    // Utility Requirements
    sb.append("UTILITY REQUIREMENTS\n");
    sb.append(subSeparator).append("\n");
    sb.append(String.format("Total Power Required:      %,.0f kW\n",
        systemDesign.getTotalPowerRequired()));
    sb.append(String.format("Total Power Recovered:     %,.0f kW\n",
        systemDesign.getTotalPowerRecovered()));
    sb.append(String.format("Net Power Requirement:     %,.0f kW\n",
        systemDesign.getNetPowerRequirement()));
    sb.append(
        String.format("Total Heating Duty:        %,.0f kW\n", systemDesign.getTotalHeatingDuty()));
    sb.append(
        String.format("Total Cooling Duty:        %,.0f kW\n", systemDesign.getTotalCoolingDuty()));
    sb.append("\n");

    sb.append(separator).append("\n");

    return sb.toString();
  }

  /**
   * Generate equipment data sheets.
   *
   * @return formatted data sheets
   */
  public String generateEquipmentDataSheets() {
    if (systemDesign == null) {
      runDesignCalculations();
    }

    StringBuilder sb = new StringBuilder();
    String separator = repeat("=", 60);
    String subSeparator = repeat("-", 60);

    sb.append(separator).append("\n");
    sb.append("EQUIPMENT DATA SHEETS\n");
    sb.append(separator).append("\n\n");

    // Generate a summary data sheet for each equipment
    ArrayList<String> names = processSystem.getAllUnitNames();
    for (String name : names) {
      ProcessEquipmentInterface equipment = processSystem.getUnit(name);
      if (equipment == null) {
        continue;
      }

      sb.append(subSeparator).append("\n");
      sb.append("EQUIPMENT: ").append(name).append("\n");
      sb.append(subSeparator).append("\n");

      // Get mechanical design if available
      try {
        MechanicalDesign mechDesign = equipment.getMechanicalDesign();
        if (mechDesign != null) {
          sb.append(String.format("Design Pressure:     %.1f barg\n",
              mechDesign.getMaxDesignPressure() - 1.01325));
          sb.append(String.format("Design Temperature:  %.0f °C\n",
              mechDesign.getDesignMaxTemperatureLimit()));
          sb.append(
              String.format("Dry Weight:          %.0f kg\n", mechDesign.getWeigthVesselShell()));
        }
      } catch (Exception e) {
        // Equipment doesn't have mechanical design
      }

      sb.append("\n");
    }

    return sb.toString();
  }

  /**
   * Write equipment list to CSV file.
   *
   * @param filePath path to output file
   * @throws IOException if file cannot be written
   */
  public void writeEquipmentListCSV(String filePath) throws IOException {
    try (PrintWriter writer = new PrintWriter(new FileWriter(filePath))) {
      writer.print(generateEquipmentListCSV());
    }
  }

  /**
   * Write piping line list to CSV file.
   *
   * @param filePath path to output file
   * @throws IOException if file cannot be written
   */
  public void writePipingLineListCSV(String filePath) throws IOException {
    try (PrintWriter writer = new PrintWriter(new FileWriter(filePath))) {
      writer.print(generatePipingLineListCSV());
    }
  }

  /**
   * Write weight report to text file.
   *
   * @param filePath path to output file
   * @throws IOException if file cannot be written
   */
  public void writeWeightReport(String filePath) throws IOException {
    try (PrintWriter writer = new PrintWriter(new FileWriter(filePath))) {
      writer.print(generateWeightReport());
    }
  }

  /**
   * Generate complete design package report.
   *
   * @return formatted complete report
   */
  public String generateCompleteReport() {
    StringBuilder sb = new StringBuilder();

    sb.append(generateWeightReport());
    sb.append("\n\n");
    sb.append(pipingDesign.generatePipingReport());
    sb.append("\n\n");
    sb.append(systemDesign.generateSummaryReport());

    return sb.toString();
  }

  // ============================================================================
  // JSON Export Methods
  // ============================================================================

  /**
   * Generate combined JSON report for all mechanical design data.
   *
   * <p>
   * This method creates a comprehensive JSON output combining:
   * </p>
   * <ul>
   * <li>System-level totals (weights, utilities, plot space)</li>
   * <li>Equipment list with individual mechanical design data</li>
   * <li>Piping interconnection design data</li>
   * <li>Weight breakdowns by type and discipline</li>
   * </ul>
   *
   * <p>
   * Usage example:
   * </p>
   * 
   * <pre>
   * {@code
   * MechanicalDesignReport report = new MechanicalDesignReport(process);
   * report.runDesignCalculations();
   * String json = report.toJson();
   * }
   * </pre>
   *
   * @return JSON string with all mechanical design data
   */
  public String toJson() {
    if (systemDesign == null || pipingDesign == null) {
      runDesignCalculations();
    }

    JsonObject root = new JsonObject();

    // Add process info
    root.addProperty("processName", processSystem.getName());
    root.addProperty("reportType", "MechanicalDesignReport");
    root.addProperty("generatedAt", java.time.Instant.now().toString());

    // Add system-level summary
    JsonObject systemSummary = new JsonObject();
    systemSummary.addProperty("totalEquipmentWeight_kg", systemDesign.getTotalWeight());
    systemSummary.addProperty("totalPipingWeight_kg", pipingDesign.getTotalPipingWeight());
    systemSummary.addProperty("totalWeight_kg",
        systemDesign.getTotalWeight() + pipingDesign.getTotalPipingWeight());
    systemSummary.addProperty("totalVolume_m3", systemDesign.getTotalVolume());
    systemSummary.addProperty("totalPlotSpace_m2", systemDesign.getTotalPlotSpace());
    systemSummary.addProperty("equipmentCount", systemDesign.getTotalNumberOfModules());
    root.add("systemSummary", systemSummary);

    // Add utility requirements
    JsonObject utilities = new JsonObject();
    utilities.addProperty("totalPowerRequired_kW", systemDesign.getTotalPowerRequired());
    utilities.addProperty("totalPowerRecovered_kW", systemDesign.getTotalPowerRecovered());
    utilities.addProperty("netPowerRequirement_kW", systemDesign.getNetPowerRequirement());
    utilities.addProperty("totalHeatingDuty_kW", systemDesign.getTotalHeatingDuty());
    utilities.addProperty("totalCoolingDuty_kW", systemDesign.getTotalCoolingDuty());
    root.add("utilityRequirements", utilities);

    // Add weight by equipment type
    JsonObject weightByType = new JsonObject();
    for (Map.Entry<String, Double> entry : systemDesign.getWeightByEquipmentType().entrySet()) {
      weightByType.addProperty(entry.getKey(), entry.getValue());
    }
    root.add("weightByEquipmentType", weightByType);

    // Add weight by discipline
    JsonObject weightByDiscipline = new JsonObject();
    for (Map.Entry<String, Double> entry : systemDesign.getWeightByDiscipline().entrySet()) {
      weightByDiscipline.addProperty(entry.getKey(), entry.getValue());
    }
    root.add("weightByDiscipline", weightByDiscipline);

    // Add equipment list with individual designs
    JsonArray equipmentArray = new JsonArray();
    for (ProcessEquipmentInterface unit : processSystem.getUnitOperations()) {
      JsonObject equipJson = new JsonObject();
      equipJson.addProperty("name", unit.getName());
      equipJson.addProperty("type", unit.getClass().getSimpleName());

      // Try to get mechanical design JSON for this equipment
      try {
        MechanicalDesign mechDesign = unit.getMechanicalDesign();
        if (mechDesign != null) {
          String mechJson = mechDesign.toJson();
          if (mechJson != null && !mechJson.isEmpty()) {
            JsonObject mechObj = JsonParser.parseString(mechJson).getAsJsonObject();
            equipJson.add("mechanicalDesign", mechObj);
          }
        }
      } catch (Exception e) {
        // Equipment doesn't have mechanical design, skip
      }

      equipmentArray.add(equipJson);
    }
    root.add("equipment", equipmentArray);

    // Add piping design data
    JsonObject pipingJson = new JsonObject();
    pipingJson.addProperty("totalLength_m", pipingDesign.getTotalPipingLength());
    pipingJson.addProperty("totalWeight_kg", pipingDesign.getTotalPipingWeight());
    pipingJson.addProperty("valveWeight_kg", pipingDesign.getValveWeight());
    pipingJson.addProperty("flangeWeight_kg", pipingDesign.getFlangeWeight());
    pipingJson.addProperty("fittingWeight_kg", pipingDesign.getFittingWeight());

    // Weight by pipe size
    JsonObject weightBySize = new JsonObject();
    for (Map.Entry<String, Double> entry : pipingDesign.getWeightBySize().entrySet()) {
      weightBySize.addProperty(entry.getKey(), entry.getValue());
    }
    pipingJson.add("weightBySize", weightBySize);

    // Length by pipe size
    JsonObject lengthBySize = new JsonObject();
    for (Map.Entry<String, Double> entry : pipingDesign.getLengthBySize().entrySet()) {
      lengthBySize.addProperty(entry.getKey(), entry.getValue());
    }
    pipingJson.add("lengthBySize", lengthBySize);

    // Pipe segments
    JsonArray segmentsArray = new JsonArray();
    for (ProcessInterconnectionDesign.PipeSegment seg : pipingDesign.getPipeSegments()) {
      JsonObject segJson = new JsonObject();
      segJson.addProperty("fromEquipment", seg.getFromEquipment());
      segJson.addProperty("toEquipment", seg.getToEquipment());
      segJson.addProperty("nominalSizeInch", seg.getNominalSizeInch());
      segJson.addProperty("outsideDiameter_mm", seg.getOutsideDiameterMm());
      segJson.addProperty("wallThickness_mm", seg.getWallThicknessMm());
      segJson.addProperty("schedule", seg.getSchedule());
      segJson.addProperty("length_m", seg.getLengthM());
      segJson.addProperty("weight_kg", seg.getWeightKg());
      segJson.addProperty("designPressure_bara", seg.getDesignPressureBara());
      segJson.addProperty("designTemperature_C", seg.getDesignTemperatureC());
      segJson.addProperty("material", seg.getMaterial());
      segJson.addProperty("isGasService", seg.isGasService());
      segmentsArray.add(segJson);
    }
    pipingJson.add("pipeSegments", segmentsArray);

    root.add("pipingDesign", pipingJson);

    // Serialize with pretty printing and NaN/Infinity support
    Gson gson =
        new GsonBuilder().serializeSpecialFloatingPointValues().setPrettyPrinting().create();
    return gson.toJson(root);
  }

  /**
   * Generate compact JSON report (no pretty printing).
   *
   * @return compact JSON string
   */
  public String toCompactJson() {
    if (systemDesign == null || pipingDesign == null) {
      runDesignCalculations();
    }

    // Generate full JSON and re-serialize without pretty printing
    String prettyJson = toJson();
    JsonObject parsed = JsonParser.parseString(prettyJson).getAsJsonObject();
    Gson compactGson = new GsonBuilder().serializeSpecialFloatingPointValues().create();
    return compactGson.toJson(parsed);
  }

  /**
   * Write JSON report to file.
   *
   * @param filePath path to output file
   * @throws IOException if file cannot be written
   */
  public void writeJsonReport(String filePath) throws IOException {
    try (PrintWriter writer = new PrintWriter(new FileWriter(filePath))) {
      writer.print(toJson());
    }
  }

  // ============================================================================
  // Helper Methods
  // ============================================================================

  /**
   * Get equipment description based on type.
   *
   * @param equip equipment summary
   * @return description string
   */
  private String getEquipmentDescription(EquipmentDesignSummary equip) {
    String type = equip.getType();
    if (type.contains("Separator")) {
      return "Process Separator";
    } else if (type.contains("Compressor")) {
      return "Centrifugal Compressor";
    } else if (type.contains("Pump")) {
      return "Centrifugal Pump";
    } else if (type.contains("Heater") || type.contains("Cooler")) {
      return "Shell & Tube Heat Exchanger";
    } else if (type.contains("Valve")) {
      return "Control Valve";
    } else if (type.contains("Tank")) {
      return "Storage Tank";
    } else {
      return type;
    }
  }

  /**
   * Repeat a string n times (Java 8 compatible).
   *
   * @param str string to repeat
   * @param count number of times
   * @return repeated string
   */
  private static String repeat(String str, int count) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < count; i++) {
      sb.append(str);
    }
    return sb.toString();
  }

  // ============================================================================
  // Getters
  // ============================================================================

  /**
   * Get the system mechanical design.
   *
   * @return system mechanical design
   */
  public SystemMechanicalDesign getSystemDesign() {
    return systemDesign;
  }

  /**
   * Get the piping design.
   *
   * @return piping design
   */
  public ProcessInterconnectionDesign getPipingDesign() {
    return pipingDesign;
  }
}
