package neqsim.process.research;

import java.util.Map;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

/**
 * Exports process synthesis superstructures for external optimization tools.
 *
 * <p>
 * Native rigorous NeqSim unit models are non-smooth because of phase changes, recycle convergence,
 * and equipment-specific feasibility failures. This exporter therefore produces a transparent
 * reduced superstructure description and a Pyomo/GDP starter script that external MINLP/GDP tools
 * can refine before NeqSim evaluates the selected candidates rigorously.
 * </p>
 *
 * @author NeqSim Development Team
 * @version 1.0
 */
public class ProcessSuperstructureExporter {
  private final Gson gson = new GsonBuilder().setPrettyPrinting().create();

  /**
   * Creates a superstructure exporter.
   */
  public ProcessSuperstructureExporter() {}

  /**
   * Exports the synthesis superstructure as JSON.
   *
   * @param spec process research specification
   * @return JSON superstructure description
   */
  public String toJson(ProcessResearchSpec spec) {
    JsonObject root = new JsonObject();
    root.addProperty("name", spec.getName());
    root.addProperty("feedMaterial", spec.getFeedMaterialName());
    root.add("materials", materialsToJson(spec));
    root.add("operations", operationsToJson(spec));
    root.add("reactions", reactionsToJson(spec));
    root.add("decisionVariables", decisionVariablesToJson(spec));
    root.add("scoringWeights", scoringWeightsToJson(spec.getScoringWeights()));
    root.addProperty("recommendedSolverClass", "GDP/MINLP with NeqSim as rigorous evaluator");
    return gson.toJson(root);
  }

  /**
   * Creates a Pyomo/GDP starter script for the exported superstructure.
   *
   * @param spec process research specification
   * @return Python script text
   */
  public String toPyomoSkeleton(ProcessResearchSpec spec) {
    StringBuilder builder = new StringBuilder();
    builder.append("# Generated by NeqSim ProcessSuperstructureExporter\n");
    builder.append("# Fill reduced-order constraints, solve with GDPopt/MINLP, ");
    builder.append("then send selected candidates back to NeqSim.\n");
    builder.append("from pyomo.environ import ConcreteModel, Var, Binary, Objective, maximize\n");
    builder.append("from pyomo.gdp import Disjunct, Disjunction\n\n");
    builder.append("m = ConcreteModel()\n");
    builder.append("m.use_operation = Var([\n");
    for (OperationOption option : spec.getOperationOptions()) {
      builder.append("    '").append(escape(option.getName())).append("',\n");
    }
    for (ReactionOption reaction : spec.getReactionOptions()) {
      builder.append("    '").append(escape(reaction.getName())).append("',\n");
    }
    builder.append("], domain=Binary)\n");
    builder.append("# TODO: add material-balance, logic, utility, cost, and safety constraints.\n");
    builder.append("m.objective = Objective(expr=sum(m.use_operation[i] ");
    builder.append("for i in m.use_operation), sense=maximize)\n");
    return builder.toString();
  }

  /**
   * Converts material nodes to JSON.
   *
   * @param spec process research specification
   * @return material array
   */
  private JsonArray materialsToJson(ProcessResearchSpec spec) {
    JsonArray array = new JsonArray();
    for (MaterialNode node : spec.getMaterialNodes()) {
      JsonObject object = new JsonObject();
      object.addProperty("name", node.getName());
      object.addProperty("description", node.getDescription());
      if (node.getComponentName() != null) {
        object.addProperty("componentName", node.getComponentName());
      }
      array.add(object);
    }
    return array;
  }

  /**
   * Converts operation options to JSON.
   *
   * @param spec process research specification
   * @return operation array
   */
  private JsonArray operationsToJson(ProcessResearchSpec spec) {
    JsonArray array = new JsonArray();
    for (OperationOption option : spec.getOperationOptions()) {
      JsonObject object = new JsonObject();
      object.addProperty("name", option.getName());
      object.addProperty("equipmentType", option.getEquipmentType());
      object.add("inputs", stringsToJson(option.getInputMaterials()));
      object.add("outputs", stringsToJson(option.getOutputMaterials()));
      object.add("properties", option.propertiesToJson());
      array.add(object);
    }
    return array;
  }

  /**
   * Converts reaction options to JSON.
   *
   * @param spec process research specification
   * @return reaction array
   */
  private JsonArray reactionsToJson(ProcessResearchSpec spec) {
    JsonArray array = new JsonArray();
    for (ReactionOption reaction : spec.getReactionOptions()) {
      JsonObject object = new JsonObject();
      object.addProperty("name", reaction.getName());
      object.addProperty("reactorType", reaction.getReactorType());
      object.addProperty("energyMode", reaction.getEnergyMode());
      if (reaction.getExpectedProductComponent() != null) {
        object.addProperty("expectedProductComponent", reaction.getExpectedProductComponent());
      }
      JsonObject stoich = new JsonObject();
      for (Map.Entry<String, Double> entry : reaction.getStoichiometry().entrySet()) {
        stoich.addProperty(entry.getKey(), entry.getValue());
      }
      object.add("stoichiometry", stoich);
      array.add(object);
    }
    return array;
  }

  /**
   * Converts decision variables to JSON.
   *
   * @param spec process research specification
   * @return decision-variable array
   */
  private JsonArray decisionVariablesToJson(ProcessResearchSpec spec) {
    JsonArray array = new JsonArray();
    for (ProcessResearchSpec.DecisionVariable variable : spec.getDecisionVariables()) {
      JsonObject object = new JsonObject();
      object.addProperty("equipmentName", variable.getEquipmentName());
      object.addProperty("propertyName", variable.getPropertyName());
      object.addProperty("lowerBound", variable.getLowerBound());
      object.addProperty("upperBound", variable.getUpperBound());
      object.addProperty("unit", variable.getUnit());
      array.add(object);
    }
    return array;
  }

  /**
   * Converts scoring weights to JSON.
   *
   * @param weights scoring weights
   * @return scoring-weight object
   */
  private JsonObject scoringWeightsToJson(ProcessResearchSpec.ScoringWeights weights) {
    JsonObject object = new JsonObject();
    object.addProperty("productFlow", weights.getProductFlowWeight());
    object.addProperty("purity", weights.getPurityWeight());
    object.addProperty("electricPowerPenalty", weights.getElectricPowerPenalty());
    object.addProperty("hotUtilityPenalty", weights.getHotUtilityPenalty());
    object.addProperty("coldUtilityPenalty", weights.getColdUtilityPenalty());
    object.addProperty("capitalCostPenalty", weights.getCapitalCostPenalty());
    object.addProperty("emissionsPenalty", weights.getEmissionsPenalty());
    object.addProperty("complexityPenalty", weights.getComplexityPenalty());
    object.addProperty("robustnessWeight", weights.getRobustnessWeight());
    return object;
  }

  /**
   * Converts strings to a JSON array.
   *
   * @param values values to convert
   * @return JSON string array
   */
  private JsonArray stringsToJson(java.util.List<String> values) {
    JsonArray array = new JsonArray();
    for (String value : values) {
      array.add(value);
    }
    return array;
  }

  /**
   * Escapes text for inclusion in simple generated Python strings.
   *
   * @param value text to escape
   * @return escaped text
   */
  private String escape(String value) {
    return value.replace("'", "\\'");
  }
}
