package neqsim.process.equipment.watertreatment;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import neqsim.process.equipment.watertreatment.OilInWaterMonthlyComplianceMonitor.MonthlyStatus;

/**
 * Decision-support optimizer for demulsifier dose and monthly OIW warning workflows.
 *
 * <p>
 * The optimizer combines a calibrated dose-response model, chemical lag model, analyzer drift model, and monthly
 * weighted OIW monitor. It scans a bounded dose range and returns the lowest dose expected to satisfy the tighter of
 * the regulatory target and remaining monthly budget.
 * </p>
 *
 * @author ESOL
 * @version 1.0
 */
public class OilInWaterDoseOptimizer implements Serializable {
  private static final long serialVersionUID = 1000L;

  /** Calibrated demulsifier dose-response model. */
  private DemulsifierDoseResponseModel doseResponseModel = new DemulsifierDoseResponseModel();

  /** Chemical inventory and lag model. */
  private ChemicalDoseLagModel chemicalLagModel = new ChemicalDoseLagModel();

  /** Analyzer drift and uncertainty model. */
  private OilInWaterAnalyzerDriftModel analyzerDriftModel = new OilInWaterAnalyzerDriftModel();

  /** Monthly weighted OIW monitor. */
  private OilInWaterMonthlyComplianceMonitor monthlyMonitor = new OilInWaterMonthlyComplianceMonitor();

  /** Minimum dose scanned by the optimizer in ppm. */
  private double minimumDosePpm = 0.0;

  /** Maximum dose scanned by the optimizer in ppm. */
  private double maximumDosePpm = 120.0;

  /** Dose scan step in ppm. */
  private double doseStepPpm = 1.0;

  /** Safety margin subtracted from the OIW target in mg/L. */
  private double safetyMarginMgL = 3.0;

  /** Time horizon used to convert setpoint dose into effective dose. */
  private double optimizationHorizonHours = 1.0;

  /** Optional conservative analyzer multiplier applied in recommendation checks. */
  private double analyzerConfidenceMultiplier = 0.0;

  /** Last recommendation generated by the optimizer. */
  private DoseRecommendation lastRecommendation;

  /**
   * Immutable dose recommendation result.
   */
  public static class DoseRecommendation implements Serializable {
    private static final long serialVersionUID = 1000L;

    /** Recommended injected setpoint dose in ppm. */
    private final double setpointDosePpm;

    /** Predicted effective process dose after lag in ppm. */
    private final double effectiveDosePpm;

    /** Predicted true OIW concentration in mg/L. */
    private final double predictedOilInWaterMgL;

    /** Predicted analyzer reading in mg/L. */
    private final double predictedMeasuredOilInWaterMgL;

    /** Target OIW concentration in mg/L. */
    private final double targetOilInWaterMgL;

    /** Whether a feasible dose was found inside configured limits. */
    private final boolean feasible;

    /** Recommendation status string. */
    private final String status;

    /** Recommendation message. */
    private final String message;

    /**
     * Creates a dose recommendation result.
     *
     * @param setpointDosePpm                setpoint dose in ppm
     * @param effectiveDosePpm               effective dose in ppm
     * @param predictedOilInWaterMgL         predicted true OIW in mg/L
     * @param predictedMeasuredOilInWaterMgL predicted measured OIW in mg/L
     * @param targetOilInWaterMgL            target OIW in mg/L
     * @param feasible                       true if the target can be met within the configured dose range
     * @param status                         recommendation status
     * @param message                        recommendation message
     */
    public DoseRecommendation(double setpointDosePpm, double effectiveDosePpm, double predictedOilInWaterMgL,
	double predictedMeasuredOilInWaterMgL, double targetOilInWaterMgL, boolean feasible, String status,
	String message) {
      this.setpointDosePpm = setpointDosePpm;
      this.effectiveDosePpm = effectiveDosePpm;
      this.predictedOilInWaterMgL = predictedOilInWaterMgL;
      this.predictedMeasuredOilInWaterMgL = predictedMeasuredOilInWaterMgL;
      this.targetOilInWaterMgL = targetOilInWaterMgL;
      this.feasible = feasible;
      this.status = status;
      this.message = message;
    }

    /**
     * Gets setpoint dose.
     *
     * @return setpoint dose in ppm
     */
    public double getSetpointDosePpm() {
      return setpointDosePpm;
    }

    /**
     * Gets effective dose.
     *
     * @return effective dose in ppm
     */
    public double getEffectiveDosePpm() {
      return effectiveDosePpm;
    }

    /**
     * Gets predicted true OIW.
     *
     * @return predicted true OIW in mg/L
     */
    public double getPredictedOilInWaterMgL() {
      return predictedOilInWaterMgL;
    }

    /**
     * Gets predicted measured OIW.
     *
     * @return predicted measured OIW in mg/L
     */
    public double getPredictedMeasuredOilInWaterMgL() {
      return predictedMeasuredOilInWaterMgL;
    }

    /**
     * Gets target OIW.
     *
     * @return target OIW in mg/L
     */
    public double getTargetOilInWaterMgL() {
      return targetOilInWaterMgL;
    }

    /**
     * Checks if the recommendation is feasible.
     *
     * @return true if feasible
     */
    public boolean isFeasible() {
      return feasible;
    }

    /**
     * Gets recommendation status.
     *
     * @return status string
     */
    public String getStatus() {
      return status;
    }

    /**
     * Gets recommendation message.
     *
     * @return message string
     */
    public String getMessage() {
      return message;
    }
  }

  /**
   * Creates an optimizer with default model instances.
   */
  public OilInWaterDoseOptimizer() {
  }

  /**
   * Recommends the lowest demulsifier dose meeting the current monthly OIW target.
   *
   * @param untreatedOilInWaterMgL untreated or pre-chemical OIW in mg/L
   * @param waterRateM3h           produced-water flow rate in m3/h
   * @param dayOfMonth             current day of month, starting at 1
   * @return dose recommendation
   */
  public DoseRecommendation recommendDose(double untreatedOilInWaterMgL, double waterRateM3h, int dayOfMonth) {
    return recommendDose(untreatedOilInWaterMgL, waterRateM3h, 0.0, dayOfMonth);
  }

  /**
   * Recommends the lowest dose while accounting for analyzer drift age.
   *
   * @param untreatedOilInWaterMgL       untreated or pre-chemical OIW in mg/L
   * @param waterRateM3h                 produced-water flow rate in m3/h
   * @param daysSinceAnalyzerCalibration days since analyzer calibration
   * @param dayOfMonth                   current day of month, starting at 1
   * @return dose recommendation
   */
  public DoseRecommendation recommendDose(double untreatedOilInWaterMgL, double waterRateM3h,
      double daysSinceAnalyzerCalibration, int dayOfMonth) {
    MonthlyStatus monthlyStatus = monthlyMonitor.calculateStatus(dayOfMonth);
    double targetOilInWater = calculateTargetOilInWater(monthlyStatus);
    DoseRecommendation bestRecommendation = null;

    for (double dose = minimumDosePpm; dose <= maximumDosePpm + 1.0e-9; dose += doseStepPpm) {
      DoseRecommendation candidate = evaluateDose(dose, untreatedOilInWaterMgL, waterRateM3h,
	  daysSinceAnalyzerCalibration, targetOilInWater);
      if (candidate.getPredictedMeasuredOilInWaterMgL() <= targetOilInWater) {
	bestRecommendation = candidate;
	break;
      }
      bestRecommendation = candidate;
    }

    if (bestRecommendation != null && bestRecommendation.getPredictedMeasuredOilInWaterMgL() <= targetOilInWater) {
      lastRecommendation = new DoseRecommendation(bestRecommendation.getSetpointDosePpm(),
	  bestRecommendation.getEffectiveDosePpm(), bestRecommendation.getPredictedOilInWaterMgL(),
	  bestRecommendation.getPredictedMeasuredOilInWaterMgL(), targetOilInWater, true, "OK",
	  monthlyStatus.getRecommendation());
    } else if (bestRecommendation != null) {
      lastRecommendation = new DoseRecommendation(bestRecommendation.getSetpointDosePpm(),
	  bestRecommendation.getEffectiveDosePpm(), bestRecommendation.getPredictedOilInWaterMgL(),
	  bestRecommendation.getPredictedMeasuredOilInWaterMgL(), targetOilInWater, false, "NO_FEASIBLE_DOSE",
	  "Maximum configured dose does not meet the OIW target");
    } else {
      lastRecommendation = new DoseRecommendation(0.0, 0.0, untreatedOilInWaterMgL, untreatedOilInWaterMgL,
	  targetOilInWater, false, "NO_EVALUATION", "No dose could be evaluated");
    }
    return lastRecommendation;
  }

  /**
   * Adds a monthly sample to the internal monitor.
   *
   * @param oilInWaterMgL OIW concentration in mg/L
   * @param waterVolumeM3 water volume in m3
   */
  public void addMonthlySample(double oilInWaterMgL, double waterVolumeM3) {
    monthlyMonitor.addSample(oilInWaterMgL, waterVolumeM3);
  }

  /**
   * Serializes optimizer configuration and the last recommendation to JSON.
   *
   * @return JSON representation
   */
  public String toJson() {
    Map<String, Object> data = new LinkedHashMap<String, Object>();
    data.put("minimumDosePpm", minimumDosePpm);
    data.put("maximumDosePpm", maximumDosePpm);
    data.put("doseStepPpm", doseStepPpm);
    data.put("safetyMarginMgL", safetyMarginMgL);
    data.put("optimizationHorizonHours", optimizationHorizonHours);
    data.put("analyzerConfidenceMultiplier", analyzerConfidenceMultiplier);
    data.put("doseResponse", doseResponseModel.getModelParameters());
    data.put("monthlyWeightedAverageMgL", monthlyMonitor.getWeightedAverageMgL());
    data.put("lastRecommendation", lastRecommendation);
    Gson gson = new GsonBuilder().setPrettyPrinting().serializeSpecialFloatingPointValues().create();
    return gson.toJson(data);
  }

  /**
   * Calculates the target OIW from the regulatory limit and remaining monthly budget.
   *
   * @param monthlyStatus monthly compliance status
   * @return target OIW in mg/L
   */
  private double calculateTargetOilInWater(MonthlyStatus monthlyStatus) {
    double target = monthlyMonitor.getMonthlyLimitMgL() - safetyMarginMgL;
    if (monthlyStatus.getRemainingWaterVolumeM3() > 0.0) {
      target = Math.min(target, monthlyStatus.getRemainingAllowedAverageMgL() - safetyMarginMgL);
    }
    return Math.max(0.0, target);
  }

  /**
   * Evaluates one setpoint dose.
   *
   * @param setpointDosePpm              setpoint dose in ppm
   * @param untreatedOilInWaterMgL       untreated OIW in mg/L
   * @param waterRateM3h                 produced-water flow rate in m3/h
   * @param daysSinceAnalyzerCalibration days since analyzer calibration
   * @param targetOilInWaterMgL          target OIW in mg/L
   * @return dose recommendation candidate
   */
  private DoseRecommendation evaluateDose(double setpointDosePpm, double untreatedOilInWaterMgL, double waterRateM3h,
      double daysSinceAnalyzerCalibration, double targetOilInWaterMgL) {
    double effectiveDose = predictEffectiveDose(setpointDosePpm, waterRateM3h);
    double trueOiw = doseResponseModel.predictOilInWater(untreatedOilInWaterMgL, effectiveDose);
    double measuredOiw = analyzerDriftModel.measureConservative(trueOiw, daysSinceAnalyzerCalibration,
	analyzerConfidenceMultiplier);
    return new DoseRecommendation(setpointDosePpm, effectiveDose, trueOiw, measuredOiw, targetOilInWaterMgL,
	measuredOiw <= targetOilInWaterMgL, "CANDIDATE", "Candidate dose");
  }

  /**
   * Predicts effective dose from setpoint without mutating the optimizer lag state.
   *
   * @param setpointDosePpm setpoint dose in ppm
   * @param waterRateM3h    water rate in m3/h
   * @return effective dose in ppm
   */
  private double predictEffectiveDose(double setpointDosePpm, double waterRateM3h) {
    ChemicalDoseLagModel scenarioLag = chemicalLagModel.copy();
    return scenarioLag.step(setpointDosePpm, waterRateM3h, optimizationHorizonHours);
  }

  /**
   * Gets dose-response model.
   *
   * @return dose-response model
   */
  public DemulsifierDoseResponseModel getDoseResponseModel() {
    return doseResponseModel;
  }

  /**
   * Sets dose-response model.
   *
   * @param doseResponseModel dose-response model
   */
  public void setDoseResponseModel(DemulsifierDoseResponseModel doseResponseModel) {
    if (doseResponseModel != null) {
      this.doseResponseModel = doseResponseModel;
    }
  }

  /**
   * Gets chemical lag model.
   *
   * @return chemical lag model
   */
  public ChemicalDoseLagModel getChemicalLagModel() {
    return chemicalLagModel;
  }

  /**
   * Sets chemical lag model.
   *
   * @param chemicalLagModel chemical lag model
   */
  public void setChemicalLagModel(ChemicalDoseLagModel chemicalLagModel) {
    if (chemicalLagModel != null) {
      this.chemicalLagModel = chemicalLagModel;
    }
  }

  /**
   * Gets analyzer drift model.
   *
   * @return analyzer drift model
   */
  public OilInWaterAnalyzerDriftModel getAnalyzerDriftModel() {
    return analyzerDriftModel;
  }

  /**
   * Sets analyzer drift model.
   *
   * @param analyzerDriftModel analyzer drift model
   */
  public void setAnalyzerDriftModel(OilInWaterAnalyzerDriftModel analyzerDriftModel) {
    if (analyzerDriftModel != null) {
      this.analyzerDriftModel = analyzerDriftModel;
    }
  }

  /**
   * Gets monthly compliance monitor.
   *
   * @return monthly compliance monitor
   */
  public OilInWaterMonthlyComplianceMonitor getMonthlyMonitor() {
    return monthlyMonitor;
  }

  /**
   * Sets monthly compliance monitor.
   *
   * @param monthlyMonitor monthly compliance monitor
   */
  public void setMonthlyMonitor(OilInWaterMonthlyComplianceMonitor monthlyMonitor) {
    if (monthlyMonitor != null) {
      this.monthlyMonitor = monthlyMonitor;
    }
  }

  /**
   * Sets dose scan range.
   *
   * @param minimumDosePpm minimum dose in ppm
   * @param maximumDosePpm maximum dose in ppm
   * @param doseStepPpm    scan step in ppm
   */
  public void setDoseRange(double minimumDosePpm, double maximumDosePpm, double doseStepPpm) {
    this.minimumDosePpm = Math.max(0.0, minimumDosePpm);
    this.maximumDosePpm = Math.max(this.minimumDosePpm, maximumDosePpm);
    this.doseStepPpm = Math.max(0.01, doseStepPpm);
  }

  /**
   * Sets safety margin.
   *
   * @param safetyMarginMgL safety margin in mg/L
   */
  public void setSafetyMarginMgL(double safetyMarginMgL) {
    this.safetyMarginMgL = Math.max(0.0, safetyMarginMgL);
  }

  /**
   * Gets safety margin.
   *
   * @return safety margin in mg/L
   */
  public double getSafetyMarginMgL() {
    return safetyMarginMgL;
  }

  /**
   * Sets optimization horizon.
   *
   * @param optimizationHorizonHours optimization horizon in hours
   */
  public void setOptimizationHorizonHours(double optimizationHorizonHours) {
    this.optimizationHorizonHours = Math.max(0.0, optimizationHorizonHours);
  }

  /**
   * Gets optimization horizon.
   *
   * @return optimization horizon in hours
   */
  public double getOptimizationHorizonHours() {
    return optimizationHorizonHours;
  }

  /**
   * Sets analyzer confidence multiplier.
   *
   * @param analyzerConfidenceMultiplier multiplier on analyzer noise standard deviation
   */
  public void setAnalyzerConfidenceMultiplier(double analyzerConfidenceMultiplier) {
    this.analyzerConfidenceMultiplier = Math.max(0.0, analyzerConfidenceMultiplier);
  }

  /**
   * Gets last recommendation.
   *
   * @return last recommendation, or null if none has been generated
   */
  public DoseRecommendation getLastRecommendation() {
    return lastRecommendation;
  }
}
