repos:
  - repo: local
    hooks:
      - id: spotless-apply
        name: Spotless Format (Java)
        entry: python devtools/run_spotless.py apply
        language: system
        files: \.(java)$
        pass_filenames: false
        stages: [pre-commit]
        verbose: false

  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check (Java)
        entry: python devtools/run_spotless.py check
        language: system
        files: \.(java)$
        pass_filenames: false
        stages: [pre-push]
        verbose: false
