package neqsim.process.envelope;

import java.io.Serializable;

/**
 * Represents a predicted trip event for a piece of process equipment.
 *
 * <p>
 * A {@code TripPrediction} is generated by the Operating Envelope Agent when a margin trend
 * indicates that a process trip (emergency shutdown of equipment) is likely within a predicted time
 * horizon. It includes the affected equipment, the type of limit being approached, the estimated
 * time to trip, and the confidence of the prediction.
 * </p>
 *
 * <p>
 * This is a purely advisory/informational output — no control system actions are taken.
 * </p>
 *
 * <p>
 * Example:
 * </p>
 *
 * <pre>
 * TripPrediction prediction = new TripPrediction("1st Stage Compressor",
 *     OperatingMargin.MarginType.SURGE, 3.2, 450.0, 0.85, TripPrediction.Severity.HIGH,
 *     "Surge margin decreasing at 0.02%/s due to rising suction pressure");
 * </pre>
 *
 * @author NeqSim
 * @version 1.0
 */
public class TripPrediction implements Serializable, Comparable<TripPrediction> {
  private static final long serialVersionUID = 1L;

  /**
   * Severity classification of the predicted trip.
   */
  public enum Severity {
    /** Trip predicted in more than 30 minutes — informational. */
    LOW(3),
    /** Trip predicted within 10-30 minutes — elevated concern. */
    MEDIUM(2),
    /** Trip predicted within 10 minutes — operator action needed. */
    HIGH(1),
    /** Trip imminent (less than 2 minutes) or already occurring. */
    IMMINENT(0);

    private final int rank;

    /**
     * Creates a severity with sort rank.
     *
     * @param rank numeric rank (0 = most severe)
     */
    Severity(int rank) {
      this.rank = rank;
    }

    /**
     * Returns the numeric rank for sorting.
     *
     * @return rank value
     */
    public int getRank() {
      return rank;
    }
  }

  private final String equipmentName;
  private final OperatingMargin.MarginType marginType;
  private final double currentMarginPercent;
  private final double estimatedTimeToTripSeconds;
  private final double confidence;
  private final Severity severity;
  private final String triggeringTrend;

  /**
   * Creates a trip prediction.
   *
   * @param equipmentName name of the equipment at risk
   * @param marginType type of operating margin being breached
   * @param currentMarginPercent current margin as percentage
   * @param estimatedTimeToTripSeconds estimated time until trip in seconds
   * @param confidence confidence level of the prediction (0.0 to 1.0)
   * @param severity severity classification
   * @param triggeringTrend description of the trend causing the prediction
   */
  public TripPrediction(String equipmentName, OperatingMargin.MarginType marginType,
      double currentMarginPercent, double estimatedTimeToTripSeconds, double confidence,
      Severity severity, String triggeringTrend) {
    this.equipmentName = equipmentName;
    this.marginType = marginType;
    this.currentMarginPercent = currentMarginPercent;
    this.estimatedTimeToTripSeconds = estimatedTimeToTripSeconds;
    this.confidence = Math.max(0.0, Math.min(1.0, confidence));
    this.severity = severity;
    this.triggeringTrend = triggeringTrend;
  }

  /**
   * Creates a trip prediction with auto-determined severity from time-to-trip.
   *
   * @param equipmentName name of the equipment at risk
   * @param marginType type of margin being breached
   * @param currentMarginPercent current margin percentage
   * @param estimatedTimeToTripSeconds estimated time in seconds
   * @param confidence confidence (0.0 to 1.0)
   * @param triggeringTrend description of the triggering trend
   */
  public TripPrediction(String equipmentName, OperatingMargin.MarginType marginType,
      double currentMarginPercent, double estimatedTimeToTripSeconds, double confidence,
      String triggeringTrend) {
    this(equipmentName, marginType, currentMarginPercent, estimatedTimeToTripSeconds, confidence,
        classifySeverity(estimatedTimeToTripSeconds), triggeringTrend);
  }

  /**
   * Classifies severity based on estimated time to trip.
   *
   * @param timeToTripSeconds estimated time in seconds
   * @return severity classification
   */
  private static Severity classifySeverity(double timeToTripSeconds) {
    if (timeToTripSeconds <= 120) {
      return Severity.IMMINENT;
    } else if (timeToTripSeconds <= 600) {
      return Severity.HIGH;
    } else if (timeToTripSeconds <= 1800) {
      return Severity.MEDIUM;
    } else {
      return Severity.LOW;
    }
  }

  /**
   * Returns the equipment name at risk of tripping.
   *
   * @return equipment name
   */
  public String getEquipmentName() {
    return equipmentName;
  }

  /**
   * Returns the type of margin being breached.
   *
   * @return margin type
   */
  public OperatingMargin.MarginType getMarginType() {
    return marginType;
  }

  /**
   * Returns the current margin as a percentage.
   *
   * @return margin percent
   */
  public double getCurrentMarginPercent() {
    return currentMarginPercent;
  }

  /**
   * Returns the estimated time to trip in seconds.
   *
   * @return seconds until trip
   */
  public double getEstimatedTimeToTripSeconds() {
    return estimatedTimeToTripSeconds;
  }

  /**
   * Returns the estimated time to trip in minutes.
   *
   * @return minutes until trip
   */
  public double getEstimatedTimeToTripMinutes() {
    return estimatedTimeToTripSeconds / 60.0;
  }

  /**
   * Returns the confidence level of the prediction.
   *
   * @return confidence (0.0 to 1.0)
   */
  public double getConfidence() {
    return confidence;
  }

  /**
   * Returns the severity classification.
   *
   * @return severity
   */
  public Severity getSeverity() {
    return severity;
  }

  /**
   * Returns the description of the triggering trend.
   *
   * @return triggering trend description
   */
  public String getTriggeringTrend() {
    return triggeringTrend;
  }

  /**
   * Compares predictions by severity (most severe first), then by time (soonest first).
   *
   * @param other the other prediction
   * @return comparison result
   */
  @Override
  public int compareTo(TripPrediction other) {
    int severityCompare = Integer.compare(this.severity.getRank(), other.severity.getRank());
    if (severityCompare != 0) {
      return severityCompare;
    }
    return Double.compare(this.estimatedTimeToTripSeconds, other.estimatedTimeToTripSeconds);
  }

  /**
   * Returns a formatted summary string.
   *
   * @return summary
   */
  @Override
  public String toString() {
    String timeStr;
    if (estimatedTimeToTripSeconds < 120) {
      timeStr = String.format("%.0f sec", estimatedTimeToTripSeconds);
    } else {
      timeStr = String.format("%.1f min", estimatedTimeToTripSeconds / 60.0);
    }
    return String.format("[%s] %s: %s margin at %.1f%%, trip in %s (conf=%.0f%%)", severity,
        equipmentName, marginType, currentMarginPercent, timeStr, confidence * 100);
  }
}
