package neqsim.process.safety.hazid;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import com.google.gson.GsonBuilder;
import neqsim.process.equipment.ProcessEquipmentInterface;
import neqsim.process.equipment.stream.StreamInterface;
import neqsim.process.processmodel.ProcessSystem;
import neqsim.process.safety.hazid.HAZOPTemplate.GuideWord;
import neqsim.process.safety.hazid.HAZOPTemplate.HAZOPDeviation;
import neqsim.process.safety.hazid.HAZOPTemplate.Parameter;

/**
 * Auto-populates HAZOP worksheet consequence and safeguard columns by mapping each guide-word/parameter deviation to
 * the NeqSim calculation that quantifies the scenario.
 *
 * <p>
 * A first-pass HAZOP grid generated by {@link HAZOPTemplate#generateGrid(Parameter...)} or
 * {@link HAZOPTemplate#fromProcessSystem} contains only "TBD" placeholders. This populator replaces those placeholders
 * with simulation-backed consequence mechanisms, the recommended NeqSim calculator, the governing standard, and a
 * typical safeguard, drawn from the static catalogue in {@link #catalogue()}.
 *
 * <p>
 * The catalogue encodes the HAZOP deviation &rarr; calculation map:
 * <table>
 * <caption>HAZOP deviation to NeqSim calculation mapping</caption>
 * <tr>
 * <th>Deviation</th>
 * <th>NeqSim calculator</th>
 * <th>Standard</th>
 * </tr>
 * <tr>
 * <td>MORE PRESSURE (overpressure)</td>
 * <td>ReliefValveSizing / SettleOutPressureAnalyzer / GasBlowbyAnalyzer</td>
 * <td>API 520/521</td>
 * </tr>
 * <tr>
 * <td>LESS PRESSURE (vacuum collapse)</td>
 * <td>VacuumCollapseAnalyzer</td>
 * <td>API 521 / ASME</td>
 * </tr>
 * <tr>
 * <td>LESS TEMPERATURE (autorefrigeration / brittle)</td>
 * <td>MDMTCalculator / DepressurizationSimulator</td>
 * <td>ASME UCS-66 / API 521</td>
 * </tr>
 * <tr>
 * <td>NO FLOW (deadhead)</td>
 * <td>PumpDeadheadAnalyzer</td>
 * <td>API 610</td>
 * </tr>
 * <tr>
 * <td>MORE FLOW (surge / erosion)</td>
 * <td>getUtilizationSnapshot surge/velocity check</td>
 * <td>API 14E / 617</td>
 * </tr>
 * <tr>
 * <td>REVERSE FLOW (backflow / surge)</td>
 * <td>WaterHammerStudy</td>
 * <td>API 521</td>
 * </tr>
 * <tr>
 * <td>AS_WELL_AS COMPOSITION (contamination)</td>
 * <td>phase / hydrate / separator screening</td>
 * <td>API 521</td>
 * </tr>
 * <tr>
 * <td>OTHER_THAN REACTION (runaway)</td>
 * <td>RunawayReactionAnalyzer</td>
 * <td>DIERS / API 521</td>
 * </tr>
 * <tr>
 * <td>MORE TEMPERATURE (fire case)</td>
 * <td>TrappedLiquidFireRuptureStudy / PfpDemandCalculator</td>
 * <td>API 521</td>
 * </tr>
 * </table>
 *
 * <p>
 * <b>References:</b>
 * <ul>
 * <li>IEC 61882 — HAZOP studies application guide</li>
 * <li>API 521 — Pressure-relieving and Depressuring Systems</li>
 * <li>API 520 — Sizing, Selection, and Installation of Pressure-relieving Devices</li>
 * </ul>
 *
 * @author ESOL
 * @version 1.0
 */
public final class HazopConsequenceAutoPopulator implements Serializable {
  private static final long serialVersionUID = 1L;

  /** Marker used by {@link HAZOPTemplate} for un-populated cells. */
  private static final String TBD = "TBD";

  /** Static catalogue keyed by guide-word/parameter. */
  private static final Map<String, HazopConsequenceMapping> CATALOGUE = buildCatalogue();

  /**
   * Hidden constructor — the populator is used through its instance methods after construction with {@code new}.
   */
  public HazopConsequenceAutoPopulator() {
  }

  /**
   * Build the static deviation &rarr; calculation catalogue.
   *
   * @return an insertion-ordered map keyed by {@link #key(GuideWord, Parameter)}
   */
  private static Map<String, HazopConsequenceMapping> buildCatalogue() {
    Map<String, HazopConsequenceMapping> map = new LinkedHashMap<>();
    add(map,
        new HazopConsequenceMapping(GuideWord.MORE, Parameter.PRESSURE,
            "Overpressure of equipment beyond MAWP from blocked outlet, gas blow-by or settle-out",
            "ReliefValveSizing, SettleOutPressureAnalyzer, GasBlowbyAnalyzer", "API 520 / API 521",
            "Pressure safety valve (PSV) and/or high-integrity pressure protection system (HIPPS)"));
    add(map,
        new HazopConsequenceMapping(GuideWord.LESS, Parameter.PRESSURE,
            "Vacuum collapse of a vessel from cooling, draining or blocked make-up gas", "VacuumCollapseAnalyzer",
            "API 521 / ASME BPVC", "Vacuum breaker / vacuum relief valve"));
    add(map,
        new HazopConsequenceMapping(GuideWord.LESS, Parameter.TEMPERATURE,
            "Autorefrigeration / low-temperature brittle fracture from depressurisation or J-T cooling",
            "MDMTCalculator, DepressurizationSimulator", "ASME UCS-66 / API 521",
            "Low-temperature trip, material selection for MDMT"));
    add(map,
        new HazopConsequenceMapping(GuideWord.MORE, Parameter.TEMPERATURE,
            "External fire heat input causing thermal expansion, overpressure or wall rupture",
            "TrappedLiquidFireRuptureStudy, PipeFireRuptureStudy, PfpDemandCalculator", "API 521",
            "Thermal safety valve (TSV), passive fire protection (PFP), depressurisation"));
    add(map,
        new HazopConsequenceMapping(GuideWord.NO, Parameter.FLOW,
            "Pump deadhead — blocked discharge causing temperature rise and shutoff overpressure",
            "PumpDeadheadAnalyzer", "API 610", "Minimum-flow recycle line, low-flow trip"));
    add(map,
        new HazopConsequenceMapping(GuideWord.MORE, Parameter.FLOW,
            "Compressor surge or high pipe velocity causing erosion and mechanical damage",
            "getUtilizationSnapshot (surge / velocity constraints)", "API 14E / API 617",
            "Anti-surge controller, flow restriction / velocity limit"));
    add(map,
        new HazopConsequenceMapping(GuideWord.LESS, Parameter.FLOW,
            "Low flow causing deadhead, overheating or loss of cooling duty", "PumpDeadheadAnalyzer", "API 610",
            "Minimum-flow recycle, low-flow alarm"));
    add(map,
        new HazopConsequenceMapping(GuideWord.REVERSE, Parameter.FLOW,
            "Backflow / check-valve slam generating hydraulic surge (water hammer)", "WaterHammerStudy", "API 521",
            "Check valve, slow-closing actuator, surge analysis"));
    add(map,
        new HazopConsequenceMapping(GuideWord.AS_WELL_AS, Parameter.COMPOSITION,
            "Contamination / unexpected phase (water, heavies) causing hydrate, corrosion or carry-over",
            "phase / hydrate / separator screening (TPflash, hydrate equilibrium)", "API 521",
            "Composition monitoring, hydrate inhibitor injection, separator design margin"));
    add(map,
        new HazopConsequenceMapping(GuideWord.PART_OF, Parameter.COMPOSITION,
            "Loss of a key component changing phase behaviour or downstream specification",
            "phase / separator screening (TPflash)", "API 521", "Composition analyser, specification alarm"));
    add(map,
        new HazopConsequenceMapping(GuideWord.OTHER_THAN, Parameter.REACTION,
            "Runaway / unintended exothermic reaction exceeding the maximum allowable temperature",
            "RunawayReactionAnalyzer", "DIERS / API 521",
            "Reaction quench, emergency relief (two-phase), reaction inhibitor"));
    return map;
  }

  /**
   * Insert a mapping into the catalogue keyed by its guide-word and parameter.
   *
   * @param map the catalogue being built
   * @param mapping the mapping to insert
   */
  private static void add(Map<String, HazopConsequenceMapping> map, HazopConsequenceMapping mapping) {
    map.put(key(mapping.getGuideWord(), mapping.getParameter()), mapping);
  }

  /**
   * Build the catalogue key for a guide-word/parameter pair.
   *
   * @param guideWord the guide-word
   * @param parameter the parameter
   * @return a stable string key
   */
  private static String key(GuideWord guideWord, Parameter parameter) {
    return guideWord.name() + ":" + parameter.name();
  }

  /**
   * Get the immutable list of all consequence mappings in the catalogue.
   *
   * @return the catalogue mappings, in declaration order
   */
  public List<HazopConsequenceMapping> catalogue() {
    return new ArrayList<>(CATALOGUE.values());
  }

  /**
   * Look up the consequence mapping for a guide-word/parameter deviation.
   *
   * @param guideWord the guide-word (must not be null)
   * @param parameter the parameter (must not be null)
   * @return the matching mapping, or {@code null} if the catalogue has no entry for the deviation
   */
  public HazopConsequenceMapping mappingFor(GuideWord guideWord, Parameter parameter) {
    if (guideWord == null || parameter == null) {
      return null;
    }
    return CATALOGUE.get(key(guideWord, parameter));
  }

  /**
   * Produce a new HAZOP node with consequence and safeguard columns auto-populated from the catalogue.
   *
   * <p>
   * The source template is not modified ({@link HAZOPDeviation} rows are immutable). For each deviation, if a catalogue
   * mapping exists, the placeholder consequence/safeguard/recommendation cells are filled with the mapped values;
   * already-filled (non-"TBD") cells are preserved. Deviations without a catalogue entry are copied unchanged.
   *
   * @param source the HAZOP node to populate (must not be null)
   * @return a new {@link HAZOPTemplate} with the same node id and design intent and populated deviation rows
   * @throws IllegalArgumentException if {@code source} is null
   */
  public HAZOPTemplate populate(HAZOPTemplate source) {
    if (source == null) {
      throw new IllegalArgumentException("source must not be null");
    }
    HAZOPTemplate populated = new HAZOPTemplate(source.getNodeId(), source.getDesignIntent());
    for (HAZOPDeviation d : source.getDeviations()) {
      HazopConsequenceMapping mapping = mappingFor(d.guideWord, d.parameter);
      if (mapping == null) {
        populated.addDeviation(d.guideWord, d.parameter, d.cause, d.consequence, d.safeguard, d.recommendation);
        continue;
      }
      String consequence = fill(d.consequence, mapping.getConsequenceMechanism());
      String safeguard = fill(d.safeguard, mapping.getTypicalSafeguard());
      String recommendation = fillRecommendation(d.recommendation, mapping);
      populated.addDeviation(d.guideWord, d.parameter, d.cause, consequence, safeguard, recommendation);
    }
    return populated;
  }

  /**
   * Replace a placeholder cell with a mapped value, preserving any existing non-placeholder content.
   *
   * @param existing the existing cell content (may be null or "TBD")
   * @param mapped the mapped value to use when the cell is empty/placeholder
   * @return the existing content if meaningful, otherwise the mapped value
   */
  private String fill(String existing, String mapped) {
    if (existing == null || existing.trim().isEmpty() || TBD.equalsIgnoreCase(existing.trim())) {
      return mapped;
    }
    return existing;
  }

  /**
   * Build the recommendation cell, citing the recommended NeqSim calculator and governing standard when the existing
   * recommendation is empty.
   *
   * @param existing the existing recommendation (may be null or "TBD")
   * @param mapping the catalogue mapping for the deviation
   * @return the existing recommendation if meaningful, otherwise a calculator/standard citation
   */
  private String fillRecommendation(String existing, HazopConsequenceMapping mapping) {
    if (existing != null && !existing.trim().isEmpty() && !TBD.equalsIgnoreCase(existing.trim())) {
      return existing;
    }
    return "Quantify with " + mapping.getRecommendedCalculator() + " per " + mapping.getStandardReference();
  }

  /**
   * Serialise the full catalogue to a pretty-printed JSON array.
   *
   * @return JSON representation of all catalogue mappings
   */
  public String catalogueToJson() {
    return new GsonBuilder().setPrettyPrinting().create().toJson(catalogue());
  }

  /**
   * Quantify the simulation-backed HAZOP consequences of a live flowsheet into deterministic PASS / EXCEEDS findings.
   *
   * <p>
   * Where {@link #populate(HAZOPTemplate)} only states which calculator applies, this method actually evaluates the
   * consequences that depend on the thermodynamic engine and that can be read directly from the post-run stream state,
   * then compares each computed value against a design limit from {@code limits}:
   * </p>
   *
   * <ul>
   * <li><b>Compressors and expanders</b> &mdash; MORE TEMPERATURE: the discharge temperature (the result of polytropic
   * compression plus a flash) is compared against the maximum allowable discharge temperature.</li>
   * <li><b>Valves</b> &mdash; LESS TEMPERATURE: the outlet temperature (the result of an isenthalpic Joule-Thomson
   * flash) is compared against the minimum design metal temperature, screening for low-temperature embrittlement.</li>
   * </ul>
   *
   * <p>
   * The flowsheet must already have been run (for example via {@code process.run()}) so the outlet streams carry solved
   * conditions. Units with no thermodynamically quantifiable scenario produce no finding here; their catalogue text is
   * still available through {@link #populate(HAZOPTemplate)}. Any read or calculation that fails degrades to a
   * {@link Verdict#NOT_EVALUATED} finding rather than throwing, mirroring the tolerant flowsheet walk used elsewhere.
   * </p>
   *
   * @param process the run flowsheet to evaluate (must not be null)
   * @param limits the design limits to compare computed consequences against; defaults are used when null
   * @return one finding per quantifiable deviation, in flowsheet order (possibly empty)
   * @throws IllegalArgumentException if {@code process} is null
   */
  public List<HazopConsequenceFinding> quantify(ProcessSystem process, HazopQuantificationLimits limits) {
    if (process == null) {
      throw new IllegalArgumentException("process must not be null");
    }
    HazopQuantificationLimits effective = limits != null ? limits : new HazopQuantificationLimits();
    List<HazopConsequenceFinding> findings = new ArrayList<HazopConsequenceFinding>();
    int index = 1;
    for (ProcessEquipmentInterface unit : process.getUnitOperations()) {
      if (unit == null) {
        continue;
      }
      String name = unit.getName();
      String type = unit.getClass().getSimpleName();
      String nodeId = String.format(Locale.ROOT, "Node-%02d: %s (%s)", index, name, type);
      String lower = type == null ? "" : type.toLowerCase(Locale.ROOT);
      if (lower.contains("compressor") || lower.contains("expander")) {
        findings.add(evaluateDischargeTemperature(nodeId, unit, name, effective));
      } else if (lower.contains("valve")) {
        findings.add(evaluateAutoRefrigeration(nodeId, unit, name, effective));
      }
      index++;
    }
    return findings;
  }

  /**
   * Evaluate the MORE TEMPERATURE consequence for a compressor or expander: discharge over-temperature.
   *
   * @param nodeId the HAZOP node identifier
   * @param unit the compressor or expander unit
   * @param name the unit name
   * @param limits the resolved design limits
   * @return a discharge-temperature finding, or a NOT_EVALUATED finding if the temperature cannot be read
   */
  private HazopConsequenceFinding evaluateDischargeTemperature(String nodeId, ProcessEquipmentInterface unit,
      String name, HazopQuantificationLimits limits) {
    String calculator = "Discharge temperature (polytropic compression + flash)";
    String standard = "API 617 / API 521";
    Double outletC = outletTemperatureCelsius(unit);
    if (outletC == null) {
      return new HazopConsequenceFinding(nodeId, name, GuideWord.MORE, Parameter.TEMPERATURE, Double.NaN, Double.NaN,
          "C", Verdict.NOT_EVALUATED, calculator, standard,
          "Discharge temperature could not be read; ensure the flowsheet has been run.");
    }
    double limit = limits.maxDischargeTemperatureC(name);
    boolean exceeds = outletC.doubleValue() > limit;
    Verdict verdict = exceeds ? Verdict.EXCEEDS : Verdict.PASS;
    String message = String.format(Locale.ROOT, "Discharge temperature %.1f C %s maximum allowable %.1f C.",
        outletC.doubleValue(), exceeds ? "EXCEEDS" : "within", limit);
    return new HazopConsequenceFinding(nodeId, name, GuideWord.MORE, Parameter.TEMPERATURE, outletC.doubleValue(),
        limit, "C", verdict, calculator, standard, message);
  }

  /**
   * Evaluate the LESS TEMPERATURE consequence for a valve: Joule-Thomson auto-refrigeration below the MDMT.
   *
   * @param nodeId the HAZOP node identifier
   * @param unit the valve unit
   * @param name the unit name
   * @param limits the resolved design limits
   * @return an auto-refrigeration finding, or a NOT_EVALUATED finding if the temperature cannot be read
   */
  private HazopConsequenceFinding evaluateAutoRefrigeration(String nodeId, ProcessEquipmentInterface unit, String name,
      HazopQuantificationLimits limits) {
    String calculator = "Outlet temperature (isenthalpic Joule-Thomson flash)";
    String standard = "ASME UCS-66 / API 521";
    Double outletC = outletTemperatureCelsius(unit);
    if (outletC == null) {
      return new HazopConsequenceFinding(nodeId, name, GuideWord.LESS, Parameter.TEMPERATURE, Double.NaN, Double.NaN,
          "C", Verdict.NOT_EVALUATED, calculator, standard,
          "Outlet temperature could not be read; ensure the flowsheet has been run.");
    }
    double limit = limits.minDesignMetalTemperatureC(name);
    boolean exceeds = outletC.doubleValue() < limit;
    Verdict verdict = exceeds ? Verdict.EXCEEDS : Verdict.PASS;
    String message = String.format(Locale.ROOT,
        "Auto-refrigeration outlet temperature %.1f C %s minimum design metal temperature %.1f C.",
        outletC.doubleValue(), exceeds ? "is BELOW" : "stays at or above", limit);
    return new HazopConsequenceFinding(nodeId, name, GuideWord.LESS, Parameter.TEMPERATURE, outletC.doubleValue(),
        limit, "C", verdict, calculator, standard, message);
  }

  /**
   * Read the temperature of a unit's first outlet stream in degrees Celsius, tolerating equipment that throws.
   *
   * @param unit the unit operation
   * @return the outlet temperature in degrees Celsius, or null if no outlet stream is available or the read fails
   */
  private Double outletTemperatureCelsius(ProcessEquipmentInterface unit) {
    try {
      List<StreamInterface> outlets = unit.getOutletStreams();
      if (outlets == null) {
        return null;
      }
      for (StreamInterface stream : outlets) {
        if (stream == null) {
          continue;
        }
        double temperature = stream.getTemperature("C");
        if (Double.isNaN(temperature)) {
          continue;
        }
        return Double.valueOf(temperature);
      }
      return null;
    } catch (RuntimeException ex) {
      return null;
    }
  }
}
