package neqsim.process.equipment.pipeline.twophasepipe.validation;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import neqsim.process.equipment.pipeline.TwoFluidMassBalanceReport;
import neqsim.process.equipment.pipeline.TwoFluidMassBalanceReport.Phase;
import neqsim.process.equipment.pipeline.TwoFluidPipe;
import neqsim.process.equipment.pipeline.TwoFluidPipe.BoundaryCondition;
import neqsim.process.equipment.pipeline.TwoFluidPipe.SlugTrackingMode;
import neqsim.process.equipment.pipeline.twophasepipe.LagrangianSlugTracker;
import neqsim.process.equipment.pipeline.twophasepipe.SlugProbe;
import neqsim.process.equipment.pipeline.twophasepipe.SlugProbe.Crossing;
import neqsim.process.equipment.pipeline.twophasepipe.SlugProbe.InterfaceType;
import neqsim.process.equipment.pipeline.twophasepipe.numerics.TimeIntegrator;
import neqsim.process.equipment.pipeline.twophasepipe.validation.MohmmedSlugFlowBenchmark.ComparisonRow;
import neqsim.process.equipment.pipeline.twophasepipe.validation.MohmmedSlugFlowBenchmark.Point;
import neqsim.process.equipment.stream.Stream;
import neqsim.thermo.system.SystemInterface;
import neqsim.thermo.system.SystemSrkEos;

/**
 * Independent physical screening of the actual coupled TwoFluidPipe against measured horizontal slug statistics.
 *
 * <p>
 * Every measured velocity operating point uses the same 8 m, 15 s calculation, with a 5 s warm-up. Defaults are 40
 * cells and 0.05 s outer calls. Positive benchmark-only properties {@code neqsim.mohmmed.cells} and
 * {@code neqsim.mohmmed.outerStep} support declared joint refinement at 40/0.05, 80/0.025 and 160/0.0125. Physical
 * inputs, duration, seed and comparison targets stay fixed. Slugs are generated by the model; no measured outcome
 * initializes a slug. A probe observes accepted kinematic steps before merging and removal. Tail and front speeds are
 * inferred from displacement at crossings of 81D. Tail speed is the predeclared primary translation convention, with
 * front speed reported separately because the experimental feature definition is unresolved. Exactly matching
 * downstream length/frequency observations are compared too: 15 + 13 + 14 = 42 measurements. Upstream 54D/58D
 * measurements and other flow conditions are explicitly outside this scope.
 * </p>
 *
 * <p>
 * Source: DOI 10.1016/j.dib.2017.11.026, CC BY 4.0. The 20% speed and 30% length/frequency targets are engineering
 * criteria, not experimental uncertainties. Missing events, solver failures and incomplete intervals fail visibly;
 * there is no analytic fallback. Only forward crossings in the inclusive [5,15] s window are counted, once per slug ID
 * and interface. Only external liquid-union boundaries generate events; length is connected liquid-union length at
 * passage. Birth and instantaneous merge geometry changes are not probe crossings. Dropped or invalid probe records
 * fail the case. Each single-grid, single-seed screening does not establish converged distributions, pressure/film
 * validation, or commercial-simulator equivalence. Run deliberately with
 * {@code -DexcludedTestGroups= -Dtest=MohmmedTwoFluidPipeExperimentalBenchmarkTest}.
 * </p>
 */
@Tag("benchmark")
class MohmmedTwoFluidPipeExperimentalBenchmarkTest {
  private static final Logger logger = LogManager.getLogger(MohmmedTwoFluidPipeExperimentalBenchmarkTest.class);
  private static final int CELLS = positiveIntegerProperty("neqsim.mohmmed.cells", 40);
  private static final double PIPE_LENGTH = 8.0;
  private static final double OUTER_STEP = positiveDoubleProperty("neqsim.mohmmed.outerStep", 0.05);
  private static final double WARM_UP = 5.0;
  private static final double END_TIME = 15.0;
  private static final long RANDOM_SEED = 20260905L;
  // A fixed operational budget. Exhaustion fails the case rather than enlarging physical time steps.
  private static final int MAXIMUM_SUBSTEP_ATTEMPTS = 2000;

  private static int positiveIntegerProperty(String name, int defaultValue) {
    String configured = System.getProperty(name);
    int value = configured == null ? defaultValue : Integer.parseInt(configured);
    if (value <= 0) {
      throw new IllegalArgumentException(name + " must be a positive integer");
    }
    return value;
  }

  private static double positiveDoubleProperty(String name, double defaultValue) {
    String configured = System.getProperty(name);
    double value = configured == null ? defaultValue : Double.parseDouble(configured);
    if (!Double.isFinite(value) || value <= 0.0) {
      throw new IllegalArgumentException(name + " must be finite and positive");
    }
    return value;
  }

  @Test
  void comparesAllFifteenOperatingPointsAndMatchingDownstreamStatistics() throws Exception {
    List<Point> measurements = readMeasurements();
    List<Point> operatingPoints = new ArrayList<Point>();
    for (Point point : measurements) {
      if ("translation_velocity".equals(point.quantity)) {
        operatingPoints.add(point);
      }
    }
    assertEquals(15, operatingPoints.size());
    List<Point> comparedMeasurements = new ArrayList<Point>();
    Map<String, Double> predictions = new HashMap<String, Double>();
    StringBuilder simulationFailures = new StringBuilder();
    logger.info("Full TwoFluidPipe experiment: cells={}, outerStep={} s, warmUp={} s, end={} s, seed={}", CELLS,
        OUTER_STEP, WARM_UP, END_TIME, RANDOM_SEED);
    logger.info("Benchmark-only refinement properties: neqsim.mohmmed.cells={}, neqsim.mohmmed.outerStep={}; "
        + "declared levels are 40/0.05, 80/0.025 and 160/0.0125", CELLS, OUTER_STEP);
    logger.info("Inlet/stochastic generation and wake effects enabled; initial/min/max model lengths=20D/12D/300D; "
        + "no measured slug outcomes used as inputs");
    logger.info("Solver settings: CONSERVATIVE_LAGRANGIAN, IMEX_PRESSURE_CORRECTION, coupled pressure/momentum=true, "
        + "interfacial pressure=true, adaptive=true, CFL=0.5, maximum substep attempts={}, "
        + "thermodynamic refresh interval=10 accepted steps (default), mass transfer=false, wall heat transfer=0, "
        + "steady initialization wall-clock limit=infinity", MAXIMUM_SUBSTEP_ATTEMPTS);
    logger.info("Observation protocol revision=2: accepted-step motion probe at 81D before merge/exit; "
        + "inclusive window=[5,15] s, positive direction, once per slug ID/interface, tail-primary translation");
    for (Point operatingPoint : operatingPoints) {
      CaseResult result = runCase(operatingPoint);
      logger.info(
          "FULL_PIPE_CASE id={}, jG={}, jL={}, completed={}, time_s={}, reason={}, frontEvents={}, "
              + "tailEvents={}, front_m_s={}, tail_m_s={}, length_D={}, frequency_Hz={}, generated={}, merged={}, "
              + "dissipated={}, exited={}, unresolvedObservationIntervals={}, maxStepMassResidual_kg={}",
          operatingPoint.id, operatingPoint.superficialGasVelocity, operatingPoint.superficialLiquidVelocity,
          result.completed, result.elapsed, result.failure, result.frontEvents, result.tailEvents,
          result.meanFrontSpeed(), result.meanTailSpeed(), result.meanLengthDiameters(operatingPoint.diameter),
          result.frequency(), result.generated, result.merged, result.dissipated, result.exited,
          result.unresolvedObservationIntervals, result.maximumMassResidual);
      logger.info(
          "FULL_PIPE_PROBE id={}, observedEvents={}, beforeWindow={}, afterWindow={}, reverseEvents={}, "
              + "repeatedEvents={}, droppedEvents={}, invalidEvents={}",
          operatingPoint.id, result.observedProbeEvents, result.beforeWindowEvents, result.afterWindowEvents,
          result.reverseProbeEvents, result.repeatedProbeEvents, result.droppedProbeEvents, result.invalidProbeEvents);
      logger.info(
          "FULL_PIPE_BOUNDARY_DIAGNOSTIC id={}, initializationRecorded={}, steadyPressureFloorLimited={}, "
              + "steadyConverged={}, initialMinimumPressure_Pa={}, outletDiagnosticAvailable={}, "
              + "outletPhaseBackflowAllowed={}, transientOutletBackflowClamped={}",
          operatingPoint.id, result.initializationRecorded, result.steadyPressureFloorLimited, result.steadyConverged,
          result.initialMinimumPressure, result.outletDiagnosticAvailable, result.outletPhaseBackflowAllowed,
          result.transientOutletBackflowClamped);
      if (!result.completed || result.unresolvedObservationIntervals > 0) {
        simulationFailures.append(operatingPoint.id).append(" failed at ").append(result.elapsed).append(" s: ")
            .append(result.failure).append(", unresolved observation intervals=")
            .append(result.unresolvedObservationIntervals).append("; ");
      }
      // Preserve every eligible reference, even if the corresponding simulation failed.
      for (Point measurement : measurements) {
        if (!sameOperatingPoint(operatingPoint, measurement)) {
          continue;
        }
        double prediction;
        if ("translation_velocity".equals(measurement.quantity)) {
          prediction = result.meanTailSpeed();
          logger.info("FULL_PIPE_FRONT_ALTERNATIVE id={}, measured_m_s={}, front_m_s={}, relativeError={}",
              measurement.id, measurement.measuredValue, result.meanFrontSpeed(),
              Math.abs(result.meanFrontSpeed() - measurement.measuredValue) / measurement.measuredValue);
        } else if (measurement.stationMinimumDiameters == 81.0 && measurement.stationMaximumDiameters == 81.0) {
          prediction = "frequency".equals(measurement.quantity) ? result.frequency()
              : result.meanLengthDiameters(operatingPoint.diameter);
        } else {
          continue;
        }
        comparedMeasurements.add(measurement);
        predictions.put(measurement.id,
            result.completed && result.unresolvedObservationIntervals == 0 ? prediction : Double.NaN);
      }
    }
    assertEquals(42, comparedMeasurements.size(), "Declared scope: 15 speed + 13 length + 14 frequency points");
    List<ComparisonRow> comparisons = MohmmedSlugFlowBenchmark.compare(comparedMeasurements, predictions);
    int failed = 0;
    StringBuilder comparisonFailures = new StringBuilder();
    for (ComparisonRow row : comparisons) {
      logger.info(
          "FULL_PIPE_COMPARISON id={}, quantity={}, measured={}, predicted={}, unit={}, relativeError={}, "
              + "engineeringTolerance={}, passed={}",
          row.point.id, row.point.quantity, row.point.measuredValue, row.predictedValue, row.point.unit,
          row.absoluteRelativeError, row.point.getRelativeTolerance(), row.withinEngineeringTolerance);
      if (!row.withinEngineeringTolerance) {
        failed++;
        comparisonFailures.append(row.point.id).append(" relativeError=").append(row.absoluteRelativeError)
            .append("; ");
      }
    }
    logger.info("Full-pipe measured comparison: {} of {} observations outside fixed targets; "
        + "source-definition uncertainty and missing refinement remain", failed, comparisons.size());
    assertTrue(simulationFailures.length() == 0 && failed == 0,
        "Full-pipe experimental screening failed. " + simulationFailures + comparisonFailures);
  }

  private List<Point> readMeasurements() throws Exception {
    String resource = "/neqsim/process/equipment/pipeline/twophasepipe/validation/"
        + "mohmmed_2018_slug_measurements.csv";
    try (InputStream input = getClass().getResourceAsStream(resource)) {
      assertNotNull(input);
      return MohmmedSlugFlowBenchmark.readCsv(new InputStreamReader(input, StandardCharsets.UTF_8));
    }
  }

  private boolean sameOperatingPoint(Point first, Point second) {
    return Math.abs(first.superficialGasVelocity - second.superficialGasVelocity) < 1e-12
        && Math.abs(first.superficialLiquidVelocity - second.superficialLiquidVelocity) < 1e-12;
  }

  private CaseResult runCase(Point point) {
    CaseResult result = new CaseResult();
    TwoFluidPipe pipe = null;
    try {
      double area = Math.PI * point.diameter * point.diameter / 4.0;
      double dryAirMass = point.superficialGasVelocity * area * 1.188;
      double waterMass = point.superficialLiquidVelocity * area * 997.3;
      double airMoles = dryAirMass / (0.79 * 0.0280134 + 0.21 * 0.0319988);
      SystemInterface fluid = new SystemSrkEos(point.temperature, point.pressure / 1e5);
      fluid.addComponent("nitrogen", 0.79 * airMoles);
      fluid.addComponent("oxygen", 0.21 * airMoles);
      fluid.addComponent("water", waterMass / 0.01801528);
      fluid.setMixingRule("classic");
      fluid.setMultiPhaseCheck(true);
      Stream feed = new Stream("Mohmmed feed " + point.id, fluid);
      feed.setFlowRate(dryAirMass + waterMass, "kg/sec");
      feed.run();
      feed.getFluid().initProperties();
      for (int phase = 0; phase < feed.getFluid().getNumberOfPhases(); phase++) {
        double phaseMass = feed.getFluid().getPhase(phase).getFlowRate("kg/sec");
        double phaseDensity = feed.getFluid().getPhase(phase).getDensity("kg/m3");
        logger.info(
            "FULL_PIPE_FLASH id={}, phase={}, mass_kg_s={}, density_kg_m3={}, actual_j_m_s={}, "
                + "requestedDryAir_kg_s={}, requestedWater_kg_s={}",
            point.id, feed.getFluid().getPhase(phase).getType(), phaseMass, phaseDensity,
            phaseMass / phaseDensity / area, dryAirMass, waterMass);
      }
      if (!feed.getFluid().hasPhaseType("gas") || !feed.getFluid().hasPhaseType("aqueous")) {
        throw new IllegalStateException("Air-water feed flash did not produce both gas and aqueous phases");
      }
      pipe = new TwoFluidPipe("Mohmmed full pipe " + point.id, feed);
      pipe.setLength(PIPE_LENGTH);
      pipe.setDiameter(point.diameter);
      pipe.setRoughness(1e-6); // Smooth Plexiglas assumption, not a tabulated measured roughness.
      pipe.setNumberOfSections(CELLS);
      pipe.setElevationProfile(new double[CELLS]);
      pipe.setOutletPressure(point.pressure);
      pipe.setInletBoundaryCondition(BoundaryCondition.STREAM_CONNECTED);
      pipe.setSlugTrackingMode(SlugTrackingMode.CONSERVATIVE_LAGRANGIAN);
      pipe.setTimeIntegrationMethod(TimeIntegrator.Method.IMEX_PRESSURE_CORRECTION);
      pipe.setEnableCoupledPressureMomentum(true);
      pipe.setEnableInterfacialPressure(true);
      pipe.setEnableAdaptiveTimestepping(true);
      pipe.setCflNumber(0.5);
      pipe.setMaximumTransientSubsteps(MAXIMUM_SUBSTEP_ATTEMPTS);
      pipe.setHeatTransferCoefficient(0.0);
      pipe.setIncludeMassTransfer(false);
      pipe.setSteadyStateMaxWallClockTime(Double.POSITIVE_INFINITY);
      pipe.run();
      result.initializationRecorded = true;
      result.steadyPressureFloorLimited = pipe.isSteadyStatePressureFloorLimited();
      result.steadyConverged = pipe.isSteadyStateConverged();
      double[] initialPressures = pipe.getPressureProfile();
      if (initialPressures.length > 0) {
        result.initialMinimumPressure = Double.POSITIVE_INFINITY;
        for (double pressure : initialPressures) {
          result.initialMinimumPressure = Math.min(result.initialMinimumPressure, pressure);
        }
      }
      LagrangianSlugTracker tracker = pipe.getLagrangianSlugTracker();
      tracker.setRandomSeed(RANDOM_SEED);
      tracker.setEnableInletSlugGeneration(true);
      tracker.setEnableStochasticInitiation(true);
      tracker.setEnableTerrainSlugGeneration(false);
      tracker.setEnableWakeEffects(true);
      tracker.setInitialSlugLengthDiameters(20.0);
      tracker.setMinSlugLengthDiameters(12.0);
      tracker.setMaxSlugLengthDiameters(300.0);
      SlugProbe probe = tracker.addProbe(81.0 * point.diameter);
      int calls = (int) Math.ceil(END_TIME / OUTER_STEP);
      for (int step = 0; step < calls; step++) {
        double beforeTime = pipe.getSimulationTime();
        double requestedStep = Math.min(OUTER_STEP, END_TIME - beforeTime);
        try {
          pipe.runTransient(requestedStep, UUID.randomUUID());
        } finally {
          // Accepted passages remain diagnostics if a later internal trial fails. The
          // incomplete physical case still supplies NaN to every measured comparison.
          observeProbe(probe, point.id, result);
        }
        double afterTime = pipe.getSimulationTime();
        if (Math.abs(afterTime - beforeTime - requestedStep) > 1e-10) {
          throw new IllegalStateException("Requested outer interval was not completely advanced");
        }
        TwoFluidMassBalanceReport report = pipe.getLastMassBalanceReport();
        if (report == null) {
          throw new IllegalStateException("Accepted interval has no mass-balance report");
        }
        for (Phase phase : new Phase[] { Phase.GAS, Phase.OIL, Phase.WATER }) {
          result.maximumMassResidual = Math.max(result.maximumMassResidual, Math.abs(report.getResidualKg(phase)));
          if (!report.isWithinTolerance(phase, 1e-8, 1e-6)) {
            throw new IllegalStateException("Phase conservation tolerance exceeded for " + phase);
          }
        }
      }
      result.completed = Math.abs(pipe.getSimulationTime() - END_TIME) <= 1e-9;
      result.failure = result.completed ? "none" : "incomplete physical duration";
    } catch (Exception exception) {
      result.failure = exception.getClass().getSimpleName() + ": " + exception.getMessage();
      logger.warn("Full-pipe case {} failed: {}", point.id, result.failure);
    } finally {
      if (pipe != null) {
        result.elapsed = pipe.getSimulationTime();
        result.outletDiagnosticAvailable = true;
        result.outletPhaseBackflowAllowed = pipe.isOutletPhaseBackflowAllowed();
        result.transientOutletBackflowClamped = pipe.isTransientOutletBackflowClamped();
        LagrangianSlugTracker tracker = pipe.getLagrangianSlugTracker();
        if (tracker != null) {
          result.generated = tracker.getTotalSlugsGenerated();
          result.merged = tracker.getTotalSlugsMerged();
          result.dissipated = tracker.getTotalSlugsDissipated();
          result.exited = tracker.getTotalSlugsExited();
        }
      }
    }
    return result;
  }

  private void observeProbe(SlugProbe probe, String pointId, CaseResult result) {
    result.droppedProbeEvents = probe.getDroppedEventCount();
    if (result.droppedProbeEvents > 0) {
      result.unresolvedObservationIntervals++;
      throw new IllegalStateException("Accepted-step probe dropped crossing records");
    }
    for (Crossing event : probe.drainEvents()) {
      result.observedProbeEvents++;
      String exclusion = "none";
      boolean valid = Double.isFinite(event.getTime()) && Double.isFinite(event.getVelocity())
          && Double.isFinite(event.getSlugLength()) && event.getSlugLength() >= 0.0
          && (event.getDirection() == 1 || event.getDirection() == -1)
          && event.getDirection() * event.getVelocity() > 0.0
          && (event.getInterfaceType() == InterfaceType.FRONT || event.getInterfaceType() == InterfaceType.TAIL);
      if (!valid) {
        result.invalidProbeEvents++;
        exclusion = "invalid_event";
      } else if (event.getTime() < WARM_UP) {
        result.beforeWindowEvents++;
        exclusion = "before_window";
      } else if (event.getTime() > END_TIME) {
        result.afterWindowEvents++;
        exclusion = "after_window";
      } else if (event.getDirection() < 0) {
        result.reverseProbeEvents++;
        exclusion = "reverse_direction";
      } else {
        Set<Integer> counted = event.getInterfaceType() == InterfaceType.FRONT ? result.frontIds : result.tailIds;
        if (!counted.add(event.getSlugId())) {
          result.repeatedProbeEvents++;
          exclusion = "repeated_id_interface";
        } else if (event.getInterfaceType() == InterfaceType.FRONT) {
          result.frontSpeedSum += event.getVelocity();
          result.lengthSum += event.getSlugLength();
          result.frontEvents++;
        } else {
          result.tailSpeedSum += event.getVelocity();
          result.tailEvents++;
        }
      }
      logger.info(
          "FULL_PIPE_PROBE_EVENT id={}, slugId={}, interface={}, time_s={}, direction={}, "
              + "velocity_m_s={}, length_m={}, included={}, exclusion={}",
          pointId, event.getSlugId(), event.getInterfaceType(), event.getTime(), event.getDirection(),
          event.getVelocity(), event.getSlugLength(), "none".equals(exclusion), exclusion);
    }
    if (result.invalidProbeEvents > 0) {
      result.unresolvedObservationIntervals++;
      throw new IllegalStateException("Accepted-step probe produced invalid crossing records");
    }
  }

  private static final class CaseResult {
    private boolean completed;
    private String failure = "not started";
    private double elapsed;
    private double frontSpeedSum;
    private double tailSpeedSum;
    private double lengthSum;
    private double maximumMassResidual;
    private int frontEvents;
    private int tailEvents;
    private int generated;
    private int merged;
    private int dissipated;
    private int exited;
    private int unresolvedObservationIntervals;
    private int observedProbeEvents;
    private int beforeWindowEvents;
    private int afterWindowEvents;
    private int reverseProbeEvents;
    private int repeatedProbeEvents;
    private long droppedProbeEvents;
    private int invalidProbeEvents;
    private boolean initializationRecorded;
    private boolean steadyPressureFloorLimited;
    private boolean steadyConverged;
    private double initialMinimumPressure = Double.NaN;
    private boolean outletDiagnosticAvailable;
    private boolean outletPhaseBackflowAllowed;
    private boolean transientOutletBackflowClamped;
    private final Set<Integer> frontIds = new HashSet<Integer>();
    private final Set<Integer> tailIds = new HashSet<Integer>();

    private double meanFrontSpeed() {
      return frontEvents > 0 ? frontSpeedSum / frontEvents : Double.NaN;
    }

    private double meanTailSpeed() {
      return tailEvents > 0 ? tailSpeedSum / tailEvents : Double.NaN;
    }

    private double meanLengthDiameters(double diameter) {
      return frontEvents > 0 ? lengthSum / frontEvents / diameter : Double.NaN;
    }

    private double frequency() {
      return completed ? frontEvents / (END_TIME - WARM_UP) : Double.NaN;
    }
  }
}
