package neqsim.blackoil.io;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import neqsim.blackoil.BlackOilPVTTable;
import neqsim.thermo.system.SystemInterface;
import neqsim.thermo.system.SystemSrkEos;

/**
 * Tests for Eclipse and CMG EOS exporters.
 *
 * @author esol
 */
class EOSExporterTest {

  @TempDir
  Path tempDir;

  private SystemInterface testFluid;
  private BlackOilPVTTable testPVTTable;

  @BeforeEach
  void setUp() {
    // Create a simple test fluid with water (required by BlackOilConverter)
    testFluid = new SystemSrkEos(373.15, 150.0);
    testFluid.addComponent("nitrogen", 0.01);
    testFluid.addComponent("CO2", 0.02);
    testFluid.addComponent("methane", 0.50);
    testFluid.addComponent("ethane", 0.06);
    testFluid.addComponent("propane", 0.04);
    testFluid.addComponent("n-butane", 0.02);
    testFluid.addComponent("n-pentane", 0.02);
    testFluid.addComponent("n-hexane", 0.02);
    testFluid.addComponent("n-heptane", 0.11);
    testFluid.addComponent("water", 0.20);
    testFluid.setMixingRule("classic");
    testFluid.init(0);

    // Create a simple test PVT table
    List<BlackOilPVTTable.Record> records = new ArrayList<>();
    records.add(
        new BlackOilPVTTable.Record(50.0, 80.0, 1.25, 0.001, 0.015, 1.5e-5, 0.0, 1.02, 0.0005));
    records.add(new BlackOilPVTTable.Record(100.0, 120.0, 1.35, 0.0008, 0.008, 1.8e-5, 0.0, 1.015,
        0.00048));
    records.add(
        new BlackOilPVTTable.Record(150.0, 150.0, 1.42, 0.0006, 0.005, 2.1e-5, 0.0, 1.01, 0.00045));
    records.add(new BlackOilPVTTable.Record(200.0, 150.0, 1.38, 0.0005, 0.004, 2.3e-5, 0.0, 1.005,
        0.00042));
    testPVTTable = new BlackOilPVTTable(records, 150.0);
  }

  // ========== Eclipse Exporter Tests ==========

  @Test
  void testEclipseExportFromFluidToString() {
    String result = EclipseEOSExporter.toString(testFluid);

    assertNotNull(result);
    assertFalse(result.isEmpty());

    // Check for required keywords
    assertTrue(result.contains("DENSITY"), "Should contain DENSITY keyword");
    assertTrue(result.contains("PVTO"), "Should contain PVTO keyword");
    assertTrue(result.contains("PVTG"), "Should contain PVTG keyword");
    assertTrue(result.contains("PVTW"), "Should contain PVTW keyword");

    // Check header
    assertTrue(result.contains("Generated by NeqSim"), "Should contain NeqSim attribution");
  }

  @Test
  void testEclipseExportFromFluidToFile() throws IOException {
    Path outputPath = tempDir.resolve("test_eclipse.inc");

    EclipseEOSExporter.toFile(testFluid, outputPath);

    assertTrue(Files.exists(outputPath), "Output file should exist");
    String content = Files.readString(outputPath);

    assertTrue(content.contains("PVTO"), "File should contain PVTO keyword");
    assertTrue(content.contains("DENSITY"), "File should contain DENSITY keyword");
  }

  @Test
  void testEclipseExportWithConfig() {
    EclipseEOSExporter.ExportConfig config =
        new EclipseEOSExporter.ExportConfig().setUnits(EclipseEOSExporter.Units.FIELD)
            .setIncludeHeader(true).setComment("Test export for validation")
            .setPressureGrid(new double[] {50, 100, 150, 200, 250, 300});

    String result = EclipseEOSExporter.toString(testFluid, config);

    assertNotNull(result);
    assertTrue(result.contains("FIELD"), "Should indicate FIELD units");
    assertTrue(result.contains("Test export for validation"), "Should contain custom comment");
  }

  @Test
  void testEclipseExportFromPVTTable() {
    double rhoOilSc = 800.0;
    double rhoGasSc = 1.2;
    double rhoWaterSc = 1000.0;

    String result = EclipseEOSExporter.toString(testPVTTable, rhoOilSc, rhoGasSc, rhoWaterSc);

    assertNotNull(result);
    assertTrue(result.contains("DENSITY"), "Should contain DENSITY keyword");
    assertTrue(result.contains("800.0"), "Should contain oil density");
    assertTrue(result.contains("PVTO"), "Should contain PVTO keyword");

    // Check bubble point is mentioned
    assertTrue(result.contains("150"), "Should reference bubble point pressure");
  }

  @Test
  void testEclipseExportFromPVTTableToFile() throws IOException {
    Path outputPath = tempDir.resolve("test_pvt_eclipse.inc");
    double rhoOilSc = 800.0;
    double rhoGasSc = 1.2;
    double rhoWaterSc = 1000.0;

    EclipseEOSExporter.toFile(testPVTTable, rhoOilSc, rhoGasSc, rhoWaterSc, outputPath);

    assertTrue(Files.exists(outputPath), "Output file should exist");
    assertTrue(Files.size(outputPath) > 0, "Output file should not be empty");
  }

  @Test
  void testEclipseMetricUnits() {
    EclipseEOSExporter.ExportConfig config =
        new EclipseEOSExporter.ExportConfig().setUnits(EclipseEOSExporter.Units.METRIC);

    String result = EclipseEOSExporter.toString(testFluid, config);

    assertTrue(result.contains("METRIC"), "Should indicate METRIC units");
    assertTrue(result.contains("BARSA") || result.contains("bar"), "Should use bar for pressure");
  }

  @Test
  void testEclipseFieldUnits() {
    EclipseEOSExporter.ExportConfig config =
        new EclipseEOSExporter.ExportConfig().setUnits(EclipseEOSExporter.Units.FIELD);

    String result = EclipseEOSExporter.toString(testFluid, config);

    assertTrue(result.contains("FIELD"), "Should indicate FIELD units");
    assertTrue(result.contains("PSIA") || result.contains("psia"),
        "Should use psia for pressure in field units");
  }

  @Test
  void testEclipseSelectiveKeywords() {
    EclipseEOSExporter.ExportConfig config = new EclipseEOSExporter.ExportConfig()
        .setIncludePVTO(true).setIncludePVTG(false).setIncludePVTW(false).setIncludeDensity(true);

    String result = EclipseEOSExporter.toString(testFluid, config);

    assertTrue(result.contains("PVTO"), "Should contain PVTO when enabled");
    assertTrue(result.contains("DENSITY"), "Should contain DENSITY when enabled");
    assertFalse(result.contains("PVTG\n"), "Should not contain PVTG when disabled");
  }

  // ========== CMG Exporter Tests ==========

  @Test
  void testCMGExportFromFluidToString() {
    String result = CMGEOSExporter.toString(testFluid);

    assertNotNull(result);
    assertFalse(result.isEmpty());

    // Check for CMG-specific markers
    assertTrue(result.contains("**"), "Should contain CMG comment markers");
    assertTrue(result.contains("NeqSim"), "Should contain NeqSim attribution");
  }

  @Test
  void testCMGExportFromFluidToFile() throws IOException {
    Path outputPath = tempDir.resolve("test_cmg.dat");

    CMGEOSExporter.toFile(testFluid, outputPath);

    assertTrue(Files.exists(outputPath), "Output file should exist");
    String content = Files.readString(outputPath);
    assertFalse(content.isEmpty(), "File content should not be empty");
  }

  @Test
  void testCMGExportIMEXFormat() {
    CMGEOSExporter.ExportConfig config =
        new CMGEOSExporter.ExportConfig().setSimulator(CMGEOSExporter.Simulator.IMEX);

    String result = CMGEOSExporter.toString(testFluid, config);

    assertNotNull(result);
    assertTrue(result.contains("IMEX"), "Should indicate IMEX simulator");
    assertTrue(result.contains("*MODEL") || result.contains("BLACKOIL"),
        "Should contain IMEX-specific keywords");
    assertTrue(result.contains("*DENSITY") || result.contains("DENSITY"),
        "Should contain density data");
  }

  @Test
  void testCMGExportGEMFormat() {
    CMGEOSExporter.ExportConfig config =
        new CMGEOSExporter.ExportConfig().setSimulator(CMGEOSExporter.Simulator.GEM);

    String result = CMGEOSExporter.toString(testFluid, config);

    assertNotNull(result);
    assertTrue(result.contains("GEM"), "Should indicate GEM simulator");
  }

  @Test
  void testCMGExportSTARSFormat() {
    CMGEOSExporter.ExportConfig config =
        new CMGEOSExporter.ExportConfig().setSimulator(CMGEOSExporter.Simulator.STARS);

    String result = CMGEOSExporter.toString(testFluid, config);

    assertNotNull(result);
    assertTrue(result.contains("STARS"), "Should indicate STARS simulator");
  }

  @Test
  void testCMGExportFromPVTTable() {
    double rhoOilSc = 800.0;
    double rhoGasSc = 1.2;
    double rhoWaterSc = 1000.0;

    String result = CMGEOSExporter.toString(testPVTTable, rhoOilSc, rhoGasSc, rhoWaterSc);

    assertNotNull(result);
    assertFalse(result.isEmpty());
    assertTrue(result.contains("**"), "Should contain CMG comments");
  }

  @Test
  void testCMGExportWithCustomConfig() {
    CMGEOSExporter.ExportConfig config = new CMGEOSExporter.ExportConfig()
        .setSimulator(CMGEOSExporter.Simulator.IMEX).setUnits(CMGEOSExporter.Units.FIELD)
        .setModelName("MY_RESERVOIR_FLUID").setComment("Custom test fluid model")
        .setPressureGrid(new double[] {50, 100, 150, 200, 300});

    String result = CMGEOSExporter.toString(testFluid, config);

    assertNotNull(result);
    assertTrue(result.contains("MY_RESERVOIR_FLUID"), "Should contain custom model name");
    assertTrue(result.contains("Custom test fluid model"), "Should contain custom comment");
    assertTrue(result.contains("FIELD"), "Should indicate FIELD units");
  }

  @Test
  void testCMGExportSIUnits() {
    CMGEOSExporter.ExportConfig config =
        new CMGEOSExporter.ExportConfig().setUnits(CMGEOSExporter.Units.SI);

    String result = CMGEOSExporter.toString(testFluid, config);

    assertTrue(result.contains("SI"), "Should indicate SI units");
    assertTrue(result.contains("kPa") || result.contains("KPA"),
        "Should use kPa for pressure in SI units");
  }

  // ========== Roundtrip / Integration Tests ==========

  @Test
  void testEclipseExportImportRoundtrip() throws IOException {
    // Export to Eclipse format
    Path outputPath = tempDir.resolve("roundtrip_test.inc");

    double rhoOilSc = 800.0;
    double rhoGasSc = 1.2;
    double rhoWaterSc = 1000.0;

    EclipseEOSExporter.toFile(testPVTTable, rhoOilSc, rhoGasSc, rhoWaterSc, outputPath);

    // Verify file was created and has content
    assertTrue(Files.exists(outputPath));
    String content = Files.readString(outputPath);

    // Verify key data is present
    assertTrue(content.contains("DENSITY"));
    assertTrue(content.contains("PVTO"));

    // Verify densities are in the output
    assertTrue(content.contains("800"), "Oil density should be in output");
  }

  @Test
  void testExportWithDifferentPressureGrids() {
    // Test with few pressure points
    EclipseEOSExporter.ExportConfig sparseConfig =
        new EclipseEOSExporter.ExportConfig().setPressureGrid(new double[] {50, 150, 300});

    String sparseResult = EclipseEOSExporter.toString(testFluid, sparseConfig);
    assertNotNull(sparseResult);

    // Test with many pressure points
    double[] denseGrid = new double[20];
    for (int i = 0; i < 20; i++) {
      denseGrid[i] = 20 + i * 20;
    }
    EclipseEOSExporter.ExportConfig denseConfig =
        new EclipseEOSExporter.ExportConfig().setPressureGrid(denseGrid);

    String denseResult = EclipseEOSExporter.toString(testFluid, denseConfig);
    assertNotNull(denseResult);

    // Dense result should be longer (more data points)
    assertTrue(denseResult.length() > sparseResult.length(),
        "Dense grid should produce more output");
  }

  @Test
  void testExportHeaderToggle() {
    // With header
    EclipseEOSExporter.ExportConfig withHeader =
        new EclipseEOSExporter.ExportConfig().setIncludeHeader(true);
    String resultWithHeader = EclipseEOSExporter.toString(testFluid, withHeader);

    // Without header
    EclipseEOSExporter.ExportConfig withoutHeader =
        new EclipseEOSExporter.ExportConfig().setIncludeHeader(false);
    String resultWithoutHeader = EclipseEOSExporter.toString(testFluid, withoutHeader);

    assertTrue(resultWithHeader.contains("Generated by NeqSim"),
        "With header should contain attribution");
    assertFalse(resultWithoutHeader.contains("Generated by NeqSim"),
        "Without header should not contain attribution");
  }

  @Test
  void testBothExportersProduceValidOutput() {
    // Ensure both exporters work on the same fluid
    String eclipseResult = EclipseEOSExporter.toString(testFluid);
    String cmgResult = CMGEOSExporter.toString(testFluid);

    assertNotNull(eclipseResult);
    assertNotNull(cmgResult);
    assertFalse(eclipseResult.isEmpty());
    assertFalse(cmgResult.isEmpty());

    // They should have different formats
    assertTrue(eclipseResult.contains("--"), "Eclipse uses -- for comments");
    assertTrue(cmgResult.contains("**"), "CMG uses ** for comments");
  }

  @Test
  void testExportNumericPrecision() {
    double rhoOilSc = 823.456789;
    double rhoGasSc = 1.23456789;
    double rhoWaterSc = 1002.345678;

    String result = EclipseEOSExporter.toString(testPVTTable, rhoOilSc, rhoGasSc, rhoWaterSc);

    // Check that values are formatted with appropriate precision
    // Oil and water densities should have 4 decimal places
    assertTrue(result.contains("823.4567") || result.contains("823.4568"),
        "Oil density should be formatted");
    // Gas density should have 6 decimal places
    assertTrue(result.contains("1.2345") || result.contains("1.234568"),
        "Gas density should be formatted with more precision");
  }
}
