package neqsim.process.equipment.compressor;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Utility to calibrate a compressor performance chart from field data.
 *
 * <p>
 * This helper supports the anti-surge / surge-control-line workflow where a screening compressor chart (for example one
 * generated by {@link CompressorChartGenerator}) must be brought closer to reality using two field measurements:
 * </p>
 *
 * <ul>
 * <li>a <b>surge test</b> that yields measured surge points (flow, head) — used by
 * {@link #fitSurgeCurve(double[], double[])} to replace the theoretical surge curve; and</li>
 * <li>a <b>gas sample</b> that yields the actual molecular weight — used by
 * {@link #molarMassHeadCorrectionFactor(double, double)} to correct the polytropic head for the change in gas
 * properties by similarity ({@code H_p} is proportional to {@code 1 / MW} at fixed volumetric flow and speed).</li>
 * </ul>
 *
 * <p>
 * The class also provides a simple {@link #recommendControlMargin(double, double[])} helper that widens a base
 * control-line margin by the relative scatter of the measured surge points, so a noisier surge test produces a more
 * conservative control line.
 * </p>
 *
 * <p>
 * Results are screening-level and must be reviewed by a qualified rotating-equipment engineer (API 617 / API 692) and
 * confirmed against the vendor performance test (ASME PTC 10 / ISO 5389) before use.
 * </p>
 *
 * @author NeqSim
 * @version 1.0
 */
public class CompressorChartCalibrator {
  private static final Logger logger = LogManager.getLogger(CompressorChartCalibrator.class);

  private final Compressor compressor;

  /**
   * Create a calibrator bound to a compressor.
   *
   * @param compressor the compressor whose chart is to be calibrated (must not be null)
   */
  public CompressorChartCalibrator(Compressor compressor) {
    if (compressor == null) {
      throw new IllegalArgumentException("compressor can not be null");
    }
    this.compressor = compressor;
  }

  /**
   * Replace the surge curve of the compressor chart with one fitted to measured surge points.
   *
   * <p>
   * The flow and head arrays are the coordinates of the surge points recorded during a field surge test (inlet actual
   * volumetric flow in m3/hr and polytropic head in the chart head unit). A spline-based surge curve with safe
   * extrapolation ({@link SafeSplineSurgeCurve}) is built and installed on the compressor chart.
   * </p>
   *
   * @param flow measured surge flow points (m3/hr); must have the same length as {@code head} and at least one point
   * @param head measured surge head points (same head unit as the chart)
   * @throws IllegalArgumentException if the arrays are null, of different length, or empty
   */
  public void fitSurgeCurve(double[] flow, double[] head) {
    if (flow == null || head == null) {
      throw new IllegalArgumentException("flow and head arrays must not be null");
    }
    if (flow.length != head.length) {
      throw new IllegalArgumentException("flow and head arrays must have the same length");
    }
    if (flow.length < 1) {
      throw new IllegalArgumentException("at least one surge point is required");
    }
    SafeSplineSurgeCurve surgeCurve = new SafeSplineSurgeCurve(flow, head);
    if (compressor.getCompressorChart() == null) {
      throw new IllegalStateException("compressor has no chart to attach the surge curve to");
    }
    compressor.getCompressorChart().setSurgeCurve(surgeCurve);
    logger.info("Fitted surge curve from {} field surge points", flow.length);
  }

  /**
   * Head correction factor for a change in gas molecular weight.
   *
   * <p>
   * At a fixed inlet volumetric flow and speed the polytropic head of a centrifugal compressor is inversely
   * proportional to the gas molecular weight ({@code H_p} proportional to {@code Z R T1 / MW}). Multiplying a
   * reference-MW head by this factor gives the head at the actual MW.
   * </p>
   *
   * @param mwReference the reference molecular weight the map was built for (g/mol or kg/mol; units cancel)
   * @param mwActual the actual molecular weight from the gas sample (same unit as {@code mwReference})
   * @return the head correction factor {@code mwReference / mwActual}
   * @throws IllegalArgumentException if either molecular weight is not strictly positive
   */
  public static double molarMassHeadCorrectionFactor(double mwReference, double mwActual) {
    if (mwReference <= 0 || mwActual <= 0) {
      throw new IllegalArgumentException("molecular weights must be strictly positive");
    }
    return mwReference / mwActual;
  }

  /**
   * Recommend an anti-surge control-line margin from a base margin and the scatter of the measured surge points.
   *
   * <p>
   * The recommended margin is {@code baseMargin + coefficientOfVariation(flow)}, where the coefficient of variation is
   * the standard deviation of the measured surge flows divided by their mean. A noisier surge test therefore yields a
   * wider (more conservative) control-line margin. A single measured point contributes zero scatter.
   * </p>
   *
   * @param baseMargin the minimum control-line margin (fraction of surge flow, e.g. 0.10)
   * @param measuredSurgeFlow the measured surge flow points (m3/hr)
   * @return the recommended control-line margin as a fraction of surge flow
   * @throws IllegalArgumentException if {@code baseMargin} is negative or the array is null/empty
   */
  public double recommendControlMargin(double baseMargin, double[] measuredSurgeFlow) {
    if (baseMargin < 0) {
      throw new IllegalArgumentException("baseMargin can not be negative");
    }
    if (measuredSurgeFlow == null || measuredSurgeFlow.length < 1) {
      throw new IllegalArgumentException("at least one measured surge flow point is required");
    }
    double mean = 0.0;
    for (double f : measuredSurgeFlow) {
      mean += f;
    }
    mean /= measuredSurgeFlow.length;
    double coefficientOfVariation = 0.0;
    if (measuredSurgeFlow.length > 1 && mean > 0) {
      double var = 0.0;
      for (double f : measuredSurgeFlow) {
        var += (f - mean) * (f - mean);
      }
      var /= (measuredSurgeFlow.length - 1);
      coefficientOfVariation = Math.sqrt(var) / mean;
    }
    return baseMargin + coefficientOfVariation;
  }
}
