package neqsim.process.safety.cfd;

import com.google.gson.GsonBuilder;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Exports {@link CfdSourceTermCase} payloads to neutral JSON and CFD starter files.
 *
 * <p>
 * The exporter deliberately writes a neutral source-term package and an OpenFOAM-oriented skeleton,
 * not a completed CFD model. Detailed meshes, obstacle geometry, turbulence models and solver
 * selections remain study-specific engineering decisions.
 * </p>
 *
 * @author ESOL
 * @version 1.0
 */
public class CfdSourceTermExporter implements Serializable {
  private static final long serialVersionUID = 1000L;

  /**
   * Serializes a case to neutral JSON.
   *
   * @param sourceTermCase CFD source-term case
   * @return JSON representation
   */
  public String toJson(CfdSourceTermCase sourceTermCase) {
    requireCase(sourceTermCase);
    return sourceTermCase.toJson();
  }

  /**
   * Writes a neutral JSON case file.
   *
   * @param sourceTermCase CFD source-term case
   * @param filename output filename
   */
  public void exportJson(CfdSourceTermCase sourceTermCase, String filename) {
    requireCase(sourceTermCase);
    writeToFile(new File(filename), sourceTermCase.toJson());
  }

  /**
   * Writes a manifest containing multiple CFD source-term cases.
   *
   * @param sourceTermCases cases to include
   * @param filename output filename
   */
  public void exportManifest(List<CfdSourceTermCase> sourceTermCases, String filename) {
    if (sourceTermCases == null) {
      throw new IllegalArgumentException("sourceTermCases must not be null");
    }
    Map<String, Object> manifest = new LinkedHashMap<String, Object>();
    manifest.put("schemaVersion", CfdSourceTermCase.SCHEMA_VERSION);
    manifest.put("caseCount", Integer.valueOf(sourceTermCases.size()));
    List<Map<String, Object>> cases = new ArrayList<Map<String, Object>>();
    for (CfdSourceTermCase sourceTermCase : sourceTermCases) {
      requireCase(sourceTermCase);
      cases.add(sourceTermCase.toMap());
    }
    manifest.put("cases", cases);
    writeToFile(new File(filename),
        new GsonBuilder().setPrettyPrinting().serializeNulls().create().toJson(manifest));
  }

  /**
   * Writes an OpenFOAM-oriented source-term skeleton directory.
   *
   * @param sourceTermCase CFD source-term case
   * @param directory output directory
   */
  public void exportOpenFoamSkeleton(CfdSourceTermCase sourceTermCase, String directory) {
    requireCase(sourceTermCase);
    File root = new File(directory);
    File constant = new File(root, "constant");
    File timeSeries = new File(constant, "sourceTimeSeries");
    mkdirs(timeSeries);
    writeToFile(new File(root, "case.json"), sourceTermCase.toJson());
    writeToFile(new File(constant, "releaseSourceProperties"),
        releaseSourceProperties(sourceTermCase));
    writeToFile(new File(timeSeries, "massFlowRate"),
        timeSeriesFile(sourceTermCase, "massFlowRateKgPerS"));
    writeToFile(new File(timeSeries, "temperature"),
        timeSeriesFile(sourceTermCase, "temperatureK"));
    writeToFile(new File(timeSeries, "jetMomentum"),
        timeSeriesFile(sourceTermCase, "jetMomentumN"));
    writeToFile(new File(root, "README.md"), openFoamReadme(sourceTermCase));
  }

  /**
   * Creates OpenFOAM release source properties text.
   *
   * @param sourceTermCase CFD source-term case
   * @return OpenFOAM dictionary-style text
   */
  private String releaseSourceProperties(CfdSourceTermCase sourceTermCase) {
    Map<String, Object> release = sourceTermCase.getRelease();
    StringBuilder text = new StringBuilder();
    text.append("/* Generated by NeqSim CFD source-term exporter */\n");
    text.append("caseId        \"").append(sourceTermCase.getCaseId()).append("\";\n");
    text.append("schemaVersion \"").append(sourceTermCase.getSchemaVersion()).append("\";\n");
    text.append("holeDiameter  ").append(valueOrZero(release.get("holeDiameterM"))).append(";\n");
    text.append("holeArea      ").append(valueOrZero(release.get("holeAreaM2"))).append(";\n");
    text.append("orientation   \"").append(release.get("orientation")).append("\";\n");
    text.append("sourceModel   \"tabulatedMassMomentumTemperature\";\n");
    text.append("timeSeriesDir \"constant/sourceTimeSeries\";\n");
    return text.toString();
  }

  /**
   * Creates a tabulated OpenFOAM time-series file from a field.
   *
   * @param sourceTermCase CFD source-term case
   * @param field field name in sourceTerm.timeSeries rows
   * @return OpenFOAM tuple list text
   */
  @SuppressWarnings("unchecked")
  private String timeSeriesFile(CfdSourceTermCase sourceTermCase, String field) {
    Object rowsObject = sourceTermCase.getSourceTerm().get("timeSeries");
    List<Map<String, Object>> rows = (List<Map<String, Object>>) rowsObject;
    StringBuilder text = new StringBuilder();
    text.append("(\n");
    for (Map<String, Object> row : rows) {
      text.append("  (").append(valueOrZero(row.get("timeS"))).append(' ')
          .append(valueOrZero(row.get(field))).append(")\n");
    }
    text.append(");\n");
    return text.toString();
  }

  /**
   * Creates a README for the OpenFOAM skeleton package.
   *
   * @param sourceTermCase CFD source-term case
   * @return README markdown
   */
  private String openFoamReadme(CfdSourceTermCase sourceTermCase) {
    StringBuilder text = new StringBuilder();
    text.append("# OpenFOAM Source-Term Skeleton\n\n");
    text.append("Case: ").append(sourceTermCase.getScenarioName()).append("\n\n");
    text.append("This directory contains a NeqSim source-term handoff package. ");
    text.append("It is not a complete CFD model: add mesh, solver, turbulence model, ");
    text.append(
        "species transport setup, boundaries, obstacles and ignition logic for the study.\n\n");
    text.append("Files:\n\n");
    text.append("- `case.json`: neutral NeqSim CFD source-term schema.\n");
    text.append("- `constant/releaseSourceProperties`: OpenFOAM-oriented source metadata.\n");
    text.append("- `constant/sourceTimeSeries/*`: tabulated source-term fields.\n");
    return text.toString();
  }

  /**
   * Converts a value to a numeric string, using zero for nulls.
   *
   * @param value value object
   * @return numeric string
   */
  private static String valueOrZero(Object value) {
    if (value instanceof Number) {
      return Double.toString(((Number) value).doubleValue());
    }
    return "0.0";
  }

  /**
   * Validates that a case is non-null.
   *
   * @param sourceTermCase case to validate
   */
  private static void requireCase(CfdSourceTermCase sourceTermCase) {
    if (sourceTermCase == null) {
      throw new IllegalArgumentException("sourceTermCase must not be null");
    }
  }

  /**
   * Creates directories if needed.
   *
   * @param directory directory to create
   */
  private static void mkdirs(File directory) {
    if (!directory.exists() && !directory.mkdirs()) {
      throw new RuntimeException("Failed to create directory: " + directory);
    }
  }

  /**
   * Writes text to a file.
   *
   * @param file target file
   * @param content text content
   */
  private static void writeToFile(File file, String content) {
    File parent = file.getParentFile();
    if (parent != null) {
      mkdirs(parent);
    }
    try (FileWriter writer = new FileWriter(file)) {
      writer.write(content);
    } catch (IOException ex) {
      throw new RuntimeException("Failed to write CFD source-term file: " + file, ex);
    }
  }
}
