"""
book_render_pdf — Render a multi-chapter book to PDF via Typst.

Extends the paper-level render_pdf.py pipeline with:
- Book/report document class with chapters
- Automatic table of contents
- Chapter-aware equation numbering (Eq. 3.1, 3.2, …)
- Part pages
- Page headers with chapter titles
- Frontmatter/backmatter sections
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

import book_builder
from render_pdf import strip_tags_and_comments, postprocess_typst

# ---------------------------------------------------------------------------
# Typst preamble for a book
# ---------------------------------------------------------------------------

def build_book_typst_preamble(cfg, profile=None):
    """Return a typst preamble string with book styling.

    Parameters
    ----------
    cfg : dict
        Parsed book.yaml configuration.
    profile : dict or None
        Publisher profile (from _publisher_profiles/*.yaml).
    """
    title = cfg.get("title", "Untitled").replace('"', '\\"')
    authors = cfg.get("authors", [])
    author_str = ", ".join(a.get("name", "") for a in authors).replace('"', '\\"')

    settings = cfg.get("settings", {})
    font_size = settings.get("font_size", 11)
    if isinstance(font_size, str):
        font_size = font_size.replace("pt", "")
    line_spacing = settings.get("line_spacing", 1.5)
    leading = f"{0.65 * float(line_spacing):.2f}em"

    # Publisher profile overrides
    if profile:
        trim = profile.get("trim_size", "210x297mm")
        margins = profile.get("margins", {})
        m_top = margins.get("top", "25mm")
        m_bot = margins.get("bottom", "25mm")
        m_inner = margins.get("inner", "25mm")
        m_outer = margins.get("outer", "25mm")
        font_family = profile.get("font", {}).get("family", "New Computer Modern") \
            if isinstance(profile.get("font"), dict) else "New Computer Modern"
        p_font_size = profile.get("font", {}).get("size", f"{font_size}pt") \
            if isinstance(profile.get("font"), dict) else f"{font_size}pt"
    else:
        trim = "210x297mm"
        m_top = "25mm"
        m_bot = "25mm"
        m_inner = "25mm"
        m_outer = "25mm"
        font_family = "New Computer Modern"
        p_font_size = f"{font_size}pt"

    eq_numbering = settings.get("equation_numbering", "chapter")
    if eq_numbering == "chapter":
        eq_num_str = '"(1.1)"'  # chapter.equation
    else:
        eq_num_str = '"(1)"'  # global

    return rf'''// Book styling — auto-generated by book_render_pdf.py
#set document(
  title: "{title}",
  author: "{author_str}",
)

// Pandoc compatibility
#let horizontalrule = line(length: 100%, stroke: 0.5pt + luma(180))

#set page(
  paper: "a4",
  margin: (top: {m_top}, bottom: {m_bot}, inside: {m_inner}, outside: {m_outer}),
  numbering: "1",
  number-align: center,
)

#set text(
  font: "{font_family}",
  size: {p_font_size},
  lang: "en",
)

#set par(
  justify: true,
  leading: {leading},
)

#set heading(numbering: "1.1")

#show heading.where(level: 1): it => {{
  pagebreak(weak: true)
  v(3em)
  block(text(weight: "bold", size: 18pt, it))
  v(1.5em)
}}

#show heading.where(level: 2): it => {{
  v(1.2em)
  block(text(weight: "bold", size: 14pt, it))
  v(0.6em)
}}

#show heading.where(level: 3): it => {{
  v(0.8em)
  block(text(weight: "bold", size: 12pt, it))
  v(0.4em)
}}

#show heading.where(level: 4): it => {{
  v(0.6em)
  block(text(weight: "bold", size: 11pt, it))
  v(0.3em)
}}

// Equation numbering
#set math.equation(numbering: {eq_num_str})

// Table styling
#set table(
  stroke: 0.5pt + luma(160),
  inset: 6pt,
)

// Code block styling
#show raw.where(block: true): it => {{
  set text(size: 7.5pt)
  block(
    width: 100%,
    inset: 8pt,
    fill: luma(245),
    radius: 3pt,
    it
  )
}}

// ── Table of Contents ──
#outline(title: "Table of Contents", depth: 3)
#pagebreak()

'''


# ---------------------------------------------------------------------------
# Chapter preprocessing
# ---------------------------------------------------------------------------

def _preprocess_chapter(text, ch_num, figures_dir=None):
    """Clean chapter markdown for typst conversion.

    - Strip HTML comments and \\tag{}
    - Fix figure paths to point to the copy in submission/
    """
    text = strip_tags_and_comments(text)

    # Rewrite relative figure paths: figures/foo.png → figures_chNN/foo.png
    if figures_dir:
        text = re.sub(
            r"!\[([^\]]*)\]\(figures/([^)]+)\)",
            rf"![\1](figures_ch{ch_num:02d}/\2)",
            text,
        )

    return text


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_book_pdf(book_dir, chapter_filter=None):
    """Render the book (or a single chapter) to PDF via Typst.

    Parameters
    ----------
    book_dir : str or Path
        Path to the book project directory.
    chapter_filter : str or None
        If given, render only the chapter whose ``dir`` matches this string.
        Produces a single-chapter preview PDF.

    Returns
    -------
    Path or None
        Path to the generated PDF, or None on failure.
    """
    book_dir = Path(book_dir)

    # Check dependencies
    if shutil.which("pandoc") is None:
        print("[book_render_pdf] Error: pandoc not found on PATH")
        return None
    try:
        import typst as _typst  # noqa: F401
    except ImportError:
        print("[book_render_pdf] Error: typst package not installed. Run: pip install typst")
        return None

    cfg = book_builder.load_book_config(book_dir)
    profile = book_builder._load_publisher_profile(cfg.get("publisher", "self"))

    submission_dir = book_dir / "submission"
    submission_dir.mkdir(parents=True, exist_ok=True)

    # Build preamble
    preamble = build_book_typst_preamble(cfg, profile)

    # Collect chapter typst fragments
    chapter_fragments = []

    for ch_num, ch, part_title in book_builder.iter_chapters(cfg):
        if chapter_filter and ch["dir"] != chapter_filter:
            continue

        ch_dir = book_builder.resolve_chapter_dir(book_dir, ch)
        ch_md = ch_dir / "chapter.md"

        if not ch_md.exists():
            print(f"[book_render_pdf] Warning: {ch_md} not found, skipping")
            continue

        # Copy chapter figures into submission/
        fig_src = ch_dir / "figures"
        fig_dst = submission_dir / f"figures_ch{ch_num:02d}"
        if fig_src.exists():
            if fig_dst.exists():
                shutil.rmtree(fig_dst)
            shutil.copytree(fig_src, fig_dst)

        # Preprocess chapter markdown
        text = ch_md.read_text(encoding="utf-8")
        text = _preprocess_chapter(text, ch_num, figures_dir=fig_src if fig_src.exists() else None)

        # Write cleaned markdown to temp file
        clean_md = submission_dir / f"_ch{ch_num:02d}_clean.md"
        clean_md.write_text(text, encoding="utf-8")

        # Convert to typst via pandoc
        typ_fragment = submission_dir / f"_ch{ch_num:02d}.typ"
        result = subprocess.run(
            ["pandoc", str(clean_md), "-o", str(typ_fragment), "--wrap=none",
             f"--resource-path={ch_dir}"],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"[book_render_pdf] pandoc error for chapter {ch_num}: {result.stderr}")
            _cleanup(clean_md)
            continue

        if typ_fragment.exists():
            frag_text = typ_fragment.read_text(encoding="utf-8")
            frag_text = postprocess_typst(frag_text)
            chapter_fragments.append(frag_text)

        # Cleanup temp
        _cleanup(clean_md, typ_fragment)

    if not chapter_fragments:
        print("[book_render_pdf] No chapters to render")
        return None

    # Assemble full typst document
    full_typst = preamble + "\n\n".join(chapter_fragments)

    # Write master file
    master_typ = submission_dir / "book.typ"
    master_typ.write_text(full_typst, encoding="utf-8")

    # Compile PDF
    pdf_name = "book.pdf" if not chapter_filter else f"{chapter_filter}.pdf"
    pdf_file = submission_dir / pdf_name

    import typst as typst_mod
    try:
        pdf_bytes = typst_mod.compile(str(master_typ))
        pdf_file.write_bytes(pdf_bytes)
    except Exception as exc:
        print(f"[book_render_pdf] typst compilation failed: {exc}")
        return None

    size_kb = pdf_file.stat().st_size / 1024
    print(f"[book_render_pdf] PDF generated: {pdf_file}  ({size_kb:.0f} KB)")
    return pdf_file


def _cleanup(*paths):
    for p in paths:
        try:
            Path(p).unlink(missing_ok=True)
        except OSError:
            pass
