#!/usr/bin/env python
"""Generate ``docs/development/AGENT_SKILL_MAP.md`` from agent files.

Scans ``.github/agents/*.agent.md`` for any line of the form::

    Loaded skills: skill-a, skill-b, skill-c

(case-insensitive, anywhere in the body) and emits a markdown table mapping
each agent to the skills it loads. This lets contributors and CI verify
agent ↔ skill linkage without hand-maintaining a separate file.

Run: ``python devtools/generate_agent_skill_map.py``
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / ".github" / "agents"
SKILLS_DIR = REPO_ROOT / ".github" / "skills"
OUTPUT_PATH = REPO_ROOT / "docs" / "development" / "AGENT_SKILL_MAP.md"

LOADED_RE = re.compile(
    r"^\s*(?:[-*]\s*)?(?:\*\*)?loaded skills(?:\*\*)?\s*[:\-]\s*(.+?)$",
    re.IGNORECASE | re.MULTILINE,
)
NAME_RE = re.compile(r"^name:\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE)


def parse_agent(path: Path) -> Dict[str, object]:
    text = path.read_text(encoding="utf-8")
    name_match = NAME_RE.search(text)
    name = name_match.group(1).strip().strip('"').strip("'") if name_match else path.stem
    skills: List[str] = []
    for m in LOADED_RE.finditer(text):
        line = m.group(1)
        for token in re.split(r"[,;]+", line):
            token = token.strip().strip("`").strip()
            # Tolerate '@' prefixes or trailing punctuation
            token = token.lstrip("@").rstrip(".")
            if token and token.startswith("neqsim-"):
                skills.append(token)
    # Deduplicate while preserving order
    seen = set()
    skills = [s for s in skills if not (s in seen or seen.add(s))]
    return {"file": path.name, "name": name, "skills": skills}


def main() -> int:
    skills_on_disk = {p.name for p in SKILLS_DIR.iterdir() if p.is_dir()}
    rows: List[Dict[str, object]] = []
    unknown: List[str] = []
    for agent in sorted(AGENTS_DIR.glob("*.agent.md")):
        info = parse_agent(agent)
        for s in info["skills"]:  # type: ignore[union-attr]
            if s not in skills_on_disk:
                unknown.append(f"{agent.name}: references unknown skill '{s}'")
        rows.append(info)

    lines: List[str] = [
        "# Agent → Skill Map",
        "",
        "Auto-generated by `devtools/generate_agent_skill_map.py`. Do not edit by hand.",
        "",
        "Each row lists the skills an agent declares via a ",
        "`Loaded skills: ...` line in its agent file. Skills are loaded with ",
        "`read_file` at the start of an agent invocation.",
        "",
        "| Agent file | Display name | Loaded skills |",
        "|------------|--------------|---------------|",
    ]
    for info in rows:
        skills = info["skills"]  # type: ignore[assignment]
        skill_cell = ", ".join(f"`{s}`" for s in skills) if skills else "_(none declared)_"
        lines.append(f"| `{info['file']}` | {info['name']} | {skill_cell} |")
    lines.append("")
    if unknown:
        lines.append("## Warnings")
        lines.append("")
        for u in unknown:
            lines.append(f"- {u}")
        lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print(f"  Agents: {len(rows)}")
    print(f"  Total skill links: {sum(len(r['skills']) for r in rows)}")  # type: ignore[arg-type]
    if unknown:
        print(f"  Unknown skill refs: {len(unknown)}")
        for u in unknown:
            print(f"    {u}")
        return 1
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
