#!/usr/bin/env python
"""Generate ``docs/development/AGENT_SKILL_MAP.md`` from agent files.

Scans ``.github/agents/*.agent.md`` and reads each agent's skills through
``agent_frontmatter.extract_required_skills`` — the frontmatter
``required_skills`` list (canonical) plus the legacy body forms
``Loaded skills: a, b, c`` and a ``## Loaded skills`` bullet list — and emits a
markdown table mapping each agent to the skills it loads. This lets
contributors and CI verify agent ↔ skill linkage without hand-maintaining a
separate file.

Run: ``python devtools/generate_agent_skill_map.py``
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent))

import agent_frontmatter as af  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / ".github" / "agents"
SKILLS_DIR = REPO_ROOT / ".github" / "skills"
OUTPUT_PATH = REPO_ROOT / "docs" / "development" / "AGENT_SKILL_MAP.md"
KNOWN_SKILLS = {p.name for p in SKILLS_DIR.iterdir() if p.is_dir()}


def extract_loaded_skills(text: str) -> List[str]:
    """Return the skills an agent declares (frontmatter first, then body)."""
    return af.extract_required_skills(text)


def parse_agent(path: Path) -> Dict[str, object]:
    info = af.read_agent(path)
    return {"file": path.name, "name": info["name"], "skills": info["required_skills"]}


def main() -> int:
    rows: List[Dict[str, object]] = []
    unknown: List[str] = []
    for agent in sorted(AGENTS_DIR.glob("*.agent.md")):
        info = parse_agent(agent)
        for s in info["skills"]:  # type: ignore[union-attr]
            if s not in KNOWN_SKILLS:
                unknown.append(f"{agent.name}: references unknown skill '{s}'")
        rows.append(info)

    lines: List[str] = [
        "---",
        "title: Agent to Skill Map",
        "description: Auto-generated map of which skills each NeqSim agent loads at "
        "invocation time, derived from the agent files in .github/agents.",
        "---",
        "",
        "# Agent → Skill Map",
        "",
        "Auto-generated by `devtools/generate_agent_skill_map.py`. Do not edit by hand.",
        "",
        "Each row lists the skills an agent declares in its `required_skills`",
        "frontmatter (or the legacy `Loaded skills: ...` body line). Skills are",
        "loaded with `read_file` at the start of an agent invocation.",
        "",
        "| Agent file | Display name | Loaded skills |",
        "|------------|--------------|---------------|",
    ]
    for info in rows:
        skills = info["skills"]  # type: ignore[assignment]
        skill_cell = ", ".join(f"`{s}`" for s in skills) if skills else "_(none declared)_"
        lines.append(f"| `{info['file']}` | {info['name']} | {skill_cell} |")
    lines.append("")
    if unknown:
        lines.append("## Warnings")
        lines.append("")
        for u in unknown:
            lines.append(f"- {u}")
        lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print(f"  Agents: {len(rows)}")
    print(f"  Total skill links: {sum(len(r['skills']) for r in rows)}")  # type: ignore[arg-type]
    if unknown:
        print(f"  Unknown skill refs: {len(unknown)}")
        for u in unknown:
            print(f"    {u}")
        return 1
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
