#!/usr/bin/env python
"""Generate ``docs/development/AGENT_SKILL_MAP.md`` from agent files.

Scans ``.github/agents/*.agent.md`` for inline declarations of the form::

    Loaded skills: skill-a, skill-b, skill-c

and markdown-list declarations under a heading of the form::

    ## Loaded skills
    - skill-a
    - skill-b

(case-insensitive, anywhere in the body) and emits a markdown table mapping each
agent to the skills it loads. This lets contributors and CI verify agent ↔ skill
linkage without hand-maintaining a separate file.

Run: ``python devtools/generate_agent_skill_map.py``
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / ".github" / "agents"
SKILLS_DIR = REPO_ROOT / ".github" / "skills"
OUTPUT_PATH = REPO_ROOT / "docs" / "development" / "AGENT_SKILL_MAP.md"
KNOWN_SKILLS = {p.name for p in SKILLS_DIR.iterdir() if p.is_dir()}

INLINE_LOADED_RE = re.compile(
    r"^\s*(?:[-*]\s*)?(?:\*\*)?loaded skills(?:\*\*)?\s*[:\-]\s*(.+?)$",
    re.IGNORECASE | re.MULTILINE,
)
BLOCK_LOADED_HEADER_RE = re.compile(
    r"^\s{0,3}#{1,6}\s+(?:\*\*)?loaded skills(?:\*\*)?\s*$",
    re.IGNORECASE,
)
MARKDOWN_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+\S")
NAME_RE = re.compile(r"^name:\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE)
SKILL_REF_RE = re.compile(r"(?<![a-z0-9_-])@?([a-z0-9][a-z0-9_-]*)(?![a-z0-9_-])", re.IGNORECASE)


def append_skill_refs(skills: List[str], text: str) -> None:
    """Append NeqSim skill references found in text to skills."""
    for match in SKILL_REF_RE.finditer(text):
        candidate = match.group(1).lower()
        if candidate in KNOWN_SKILLS:
            skills.append(candidate)


def extract_loaded_skills(text: str) -> List[str]:
    """Extract inline and markdown-list Loaded skills declarations."""
    skills: List[str] = []

    for match in INLINE_LOADED_RE.finditer(text):
        append_skill_refs(skills, match.group(1))

    lines = text.splitlines()
    for line_number, line in enumerate(lines):
        if not BLOCK_LOADED_HEADER_RE.match(line):
            continue
        block_lines: List[str] = []
        for next_line in lines[line_number + 1:]:
            if MARKDOWN_HEADING_RE.match(next_line):
                break
            if not next_line.strip() and block_lines:
                break
            if re.match(r"^\s*[-*]\s+", next_line):
                block_lines.append(next_line)
        append_skill_refs(skills, "\n".join(block_lines))

    seen = set()
    return [skill for skill in skills if not (skill in seen or seen.add(skill))]


def parse_agent(path: Path) -> Dict[str, object]:
    text = path.read_text(encoding="utf-8")
    name_match = NAME_RE.search(text)
    name = name_match.group(1).strip().strip('"').strip("'") if name_match else path.stem
    skills = extract_loaded_skills(text)
    return {"file": path.name, "name": name, "skills": skills}


def main() -> int:
    rows: List[Dict[str, object]] = []
    unknown: List[str] = []
    for agent in sorted(AGENTS_DIR.glob("*.agent.md")):
        info = parse_agent(agent)
        for s in info["skills"]:  # type: ignore[union-attr]
            if s not in KNOWN_SKILLS:
                unknown.append(f"{agent.name}: references unknown skill '{s}'")
        rows.append(info)

    lines: List[str] = [
        "---",
        "title: Agent to Skill Map",
        "description: Auto-generated map of which skills each NeqSim agent loads at "
        "invocation time, derived from the agent files in .github/agents.",
        "---",
        "",
        "# Agent → Skill Map",
        "",
        "Auto-generated by `devtools/generate_agent_skill_map.py`. Do not edit by hand.",
        "",
        "Each row lists the skills an agent declares via `Loaded skills: ...`",
        "or a `## Loaded skills` markdown list in its agent file. Skills are",
        "loaded with `read_file` at the start of an agent invocation.",
        "",
        "| Agent file | Display name | Loaded skills |",
        "|------------|--------------|---------------|",
    ]
    for info in rows:
        skills = info["skills"]  # type: ignore[assignment]
        skill_cell = ", ".join(f"`{s}`" for s in skills) if skills else "_(none declared)_"
        lines.append(f"| `{info['file']}` | {info['name']} | {skill_cell} |")
    lines.append("")
    if unknown:
        lines.append("## Warnings")
        lines.append("")
        for u in unknown:
            lines.append(f"- {u}")
        lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    print(f"  Agents: {len(rows)}")
    print(f"  Total skill links: {sum(len(r['skills']) for r in rows)}")  # type: ignore[arg-type]
    if unknown:
        print(f"  Unknown skill refs: {len(unknown)}")
        for u in unknown:
            print(f"    {u}")
        return 1
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
