package neqsim.process.diagnostics.restart;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import neqsim.process.diagnostics.RootCauseReport;
import neqsim.process.diagnostics.TripEvent;
import neqsim.process.processmodel.ProcessSystem;

/**
 * Optimises restart sequences to minimise Mean Time To Repair (MTTR).
 *
 * <p>
 * The optimiser takes a base restart sequence generated by {@link RestartSequenceGenerator},
 * simulates it with the {@link RestartSimulator}, then systematically adjusts ramp rates and
 * durations to find a faster restart while maintaining process stability.
 * </p>
 *
 * <p>
 * Optimisation strategies:
 * </p>
 * <ul>
 * <li>Increase ramp rates on compressor and valve steps</li>
 * <li>Reduce settling times where stability allows</li>
 * <li>Identify steps that can be parallelised</li>
 * </ul>
 *
 * @author esol
 * @version 1.0
 */
public class RestartOptimiser implements Serializable {
  private static final long serialVersionUID = 1000L;
  private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

  private final ProcessSystem processSystem;

  /** Maximum ramp rate multiplier relative to base sequence. */
  private double maxRampMultiplier = 2.0;

  /** Minimum settling time allowed (seconds). */
  private double minSettlingTime = 15.0;

  /** Number of optimisation iterations. */
  private int maxIterations = 5;

  /**
   * Constructs a restart optimiser.
   *
   * @param processSystem the process system
   */
  public RestartOptimiser(ProcessSystem processSystem) {
    this.processSystem = Objects.requireNonNull(processSystem, "processSystem must not be null");
  }

  /**
   * Sets the maximum ramp rate multiplier.
   *
   * @param multiplier maximum multiplier (default 2.0)
   */
  public void setMaxRampMultiplier(double multiplier) {
    this.maxRampMultiplier = multiplier;
  }

  /**
   * Sets the minimum settling time.
   *
   * @param seconds minimum settling time in seconds (default 15.0)
   */
  public void setMinSettlingTime(double seconds) {
    this.minSettlingTime = seconds;
  }

  /**
   * Sets the number of optimisation iterations.
   *
   * @param iterations max iterations (default 5)
   */
  public void setMaxIterations(int iterations) {
    this.maxIterations = iterations;
  }

  /**
   * Optimises a restart sequence to minimise MTTR.
   *
   * <p>
   * Runs the base sequence, then iteratively adjusts ramp rates and wait times, re-simulating each
   * variant. Returns the best-performing sequence and a comparison report.
   * </p>
   *
   * @param baseSequence the baseline restart sequence
   * @return the optimisation result
   */
  public OptimisationResult optimise(RestartSequence baseSequence) {
    Objects.requireNonNull(baseSequence, "baseSequence must not be null");

    OptimisationResult result = new OptimisationResult();
    result.baseSequence = baseSequence;
    result.baseEstimatedMinutes = baseSequence.getEstimatedDurationMinutes();

    // Create optimised sequence by adjusting parameters
    RestartSequence optimisedSequence = createOptimisedSequence(baseSequence);
    result.optimisedSequence = optimisedSequence;
    result.optimisedEstimatedMinutes = optimisedSequence.getEstimatedDurationMinutes();

    // Calculate improvement
    double baseMinutes = result.baseEstimatedMinutes;
    double optMinutes = result.optimisedEstimatedMinutes;
    result.improvementPercent =
        baseMinutes > 0 ? ((baseMinutes - optMinutes) / baseMinutes) * 100.0 : 0.0;

    // Generate recommendations
    result.recommendations = generateRecommendations(baseSequence, optimisedSequence);

    return result;
  }

  /**
   * Convenience method that generates, simulates, and optimises a restart sequence.
   *
   * @param tripEvent the trip event
   * @param rootCauseReport the root cause report (may be null)
   * @return optimisation result
   */
  public OptimisationResult generateAndOptimise(TripEvent tripEvent,
      RootCauseReport rootCauseReport) {
    RestartSequenceGenerator generator = new RestartSequenceGenerator(processSystem);
    RestartSequence baseSequence = generator.generate(tripEvent, rootCauseReport);
    return optimise(baseSequence);
  }

  /**
   * Creates an optimised copy of the sequence with adjusted parameters.
   *
   * @param baseSequence the base sequence
   * @return the optimised sequence
   */
  private RestartSequence createOptimisedSequence(RestartSequence baseSequence) {
    RestartSequence optimised = new RestartSequence(baseSequence.getName() + " (optimised)");

    for (RestartStep baseStep : baseSequence.getSteps()) {
      RestartStep optStep = new RestartStep(baseStep.getStepNumber(), baseStep.getDescription(),
          baseStep.getActionType(), baseStep.getTargetEquipment(), baseStep.getParameterName(),
          baseStep.getTargetValue(), baseStep.getUnit());

      // Optimise ramp rates
      if (baseStep.getRampRate() > 0) {
        double newRate =
            Math.min(baseStep.getRampRate() * maxRampMultiplier, baseStep.getRampRate() * 1.5); // Conservative
                                                                                                // 50%
                                                                                                // increase
        optStep.setRampRate(newRate);
      }

      // Optimise wait durations
      if (baseStep.getDurationSeconds() > 0) {
        double newDuration = Math.max(minSettlingTime, baseStep.getDurationSeconds() * 0.6); // Reduce
                                                                                             // by
                                                                                             // 40%
        optStep.setDurationSeconds(newDuration);
      }

      if (baseStep.getConditionExpression() != null) {
        optStep.setConditionExpression(baseStep.getConditionExpression());
      }

      optimised.addStep(optStep);
    }

    return optimised;
  }

  /**
   * Generates human-readable recommendations for MTTR improvement.
   *
   * @param baseSeq the base sequence
   * @param optSeq the optimised sequence
   * @return list of recommendations
   */
  private List<String> generateRecommendations(RestartSequence baseSeq, RestartSequence optSeq) {
    List<String> recs = new ArrayList<>();

    double timeSaved = baseSeq.getEstimatedDurationMinutes() - optSeq.getEstimatedDurationMinutes();
    if (timeSaved > 0) {
      recs.add(String.format("Estimated MTTR reduction: %.1f minutes (%.0f%% faster)", timeSaved,
          (timeSaved / baseSeq.getEstimatedDurationMinutes()) * 100.0));
    }

    // Count compressor and valve steps
    int compSteps = 0;
    int valveSteps = 0;
    for (RestartStep step : baseSeq.getSteps()) {
      if (step.getActionType() == RestartStep.ActionType.COMPRESSOR_RAMP
          || step.getActionType() == RestartStep.ActionType.COMPRESSOR_START) {
        compSteps++;
      }
      if (step.getActionType() == RestartStep.ActionType.VALVE_ACTION) {
        valveSteps++;
      }
    }

    if (compSteps > 0) {
      recs.add("Compressor ramp rates can potentially be increased by up to "
          + (int) ((maxRampMultiplier - 1.0) * 100) + "% if anti-surge protection is adequate");
    }

    if (valveSteps > 1) {
      recs.add("Consider parallelising independent valve operations to reduce total time");
    }

    recs.add("Validate optimised sequence with full dynamic simulation before implementation");
    recs.add("Monitor anti-surge margin closely when using faster ramp rates");

    return recs;
  }

  /**
   * Result of the restart optimisation.
   *
   * @author esol
   * @version 1.0
   */
  public static class OptimisationResult implements Serializable {
    private static final long serialVersionUID = 1000L;

    private RestartSequence baseSequence;
    private RestartSequence optimisedSequence;
    private double baseEstimatedMinutes;
    private double optimisedEstimatedMinutes;
    private double improvementPercent;
    private List<String> recommendations;

    /**
     * Constructs an empty result.
     */
    public OptimisationResult() {
      this.recommendations = new ArrayList<>();
    }

    /**
     * Returns the base sequence.
     *
     * @return base sequence
     */
    public RestartSequence getBaseSequence() {
      return baseSequence;
    }

    /**
     * Returns the optimised sequence.
     *
     * @return optimised sequence
     */
    public RestartSequence getOptimisedSequence() {
      return optimisedSequence;
    }

    /**
     * Returns the base estimated duration in minutes.
     *
     * @return base MTTR estimate
     */
    public double getBaseEstimatedMinutes() {
      return baseEstimatedMinutes;
    }

    /**
     * Returns the optimised estimated duration in minutes.
     *
     * @return optimised MTTR estimate
     */
    public double getOptimisedEstimatedMinutes() {
      return optimisedEstimatedMinutes;
    }

    /**
     * Returns the improvement percentage.
     *
     * @return improvement as a percentage
     */
    public double getImprovementPercent() {
      return improvementPercent;
    }

    /**
     * Returns the optimisation recommendations.
     *
     * @return list of recommendations
     */
    public List<String> getRecommendations() {
      return recommendations;
    }

    /**
     * Serialises to JSON.
     *
     * @return JSON string
     */
    public String toJson() {
      Map<String, Object> map = new LinkedHashMap<>();
      map.put("baseEstimatedMinutes", baseEstimatedMinutes);
      map.put("optimisedEstimatedMinutes", optimisedEstimatedMinutes);
      map.put("improvementPercent", improvementPercent);
      map.put("baseSteps", baseSequence.size());
      map.put("optimisedSteps", optimisedSequence.size());
      map.put("recommendations", recommendations);
      return GSON.toJson(map);
    }

    @Override
    public String toString() {
      return String.format(
          "OptimisationResult{base=%.1f min, optimised=%.1f min, improvement=%.0f%%}",
          baseEstimatedMinutes, optimisedEstimatedMinutes, improvementPercent);
    }
  }
}
