package neqsim.process.equipment.capacity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;
import neqsim.process.equipment.capacity.CapacityConstraint.ConstraintType;
import neqsim.process.equipment.pump.Pump;
import neqsim.process.equipment.stream.Stream;
import neqsim.thermo.system.SystemInterface;
import neqsim.thermo.system.SystemSrkEos;

/** Tests for {@link PumpCapacityStrategy}. */
class PumpCapacityStrategyTest {

  /**
   * Verifies that available NPSH headroom is treated as a minimum constraint.
   */
  @Test
  void npshHeadroomUsesMinimumConstraintDirection() {
    SystemInterface fluid = new SystemSrkEos(298.15, 5.0);
    fluid.addComponent("water", 1.0);
    fluid.setMixingRule("classic");
    fluid.setTotalFlowRate(100000.0, "kg/hr");

    Stream feed = new Stream("NPSH constraint feed", fluid);
    feed.run();
    Pump pump = new Pump("NPSH constraint pump", feed);
    pump.setOutletPressure(10.0, "bara");
    pump.run();

    double availableHeadroom = pump.getNPSHAvailable() - pump.getNPSHRequired();
    assertTrue(availableHeadroom > 2.0, "fixture must provide positive NPSH headroom");

    CapacityConstraint safe = getNpshConstraint(pump, availableHeadroom - 1.0);
    CapacityConstraint atLimit = getNpshConstraint(pump, availableHeadroom);
    CapacityConstraint violated = getNpshConstraint(pump, availableHeadroom + 1.0);

    assertTrue(safe.isMinimumConstraint());
    assertEquals(ConstraintType.HARD, safe.getType());
    assertEquals(availableHeadroom - 1.0, safe.getDisplayDesignValue(), 1.0e-10);
    assertEquals((availableHeadroom - 1.0) / availableHeadroom, safe.getUtilization(), 1.0e-10);
    assertFalse(safe.isViolated());
    assertFalse(safe.isHardLimitExceeded());

    assertEquals(1.0, atLimit.getUtilization(), 1.0e-10);
    assertFalse(atLimit.isViolated(), "the exact minimum is feasible");

    assertEquals((availableHeadroom + 1.0) / availableHeadroom, violated.getUtilization(), 1.0e-10);
    assertTrue(violated.isViolated());
    assertTrue(violated.isHardLimitExceeded());
  }

  /**
   * Creates the NPSH constraint generated by a strategy with the supplied minimum headroom.
   *
   * @param pump pump under test
   * @param minimumHeadroom minimum required NPSH headroom in metres
   * @return generated NPSH constraint
   */
  private CapacityConstraint getNpshConstraint(Pump pump, double minimumHeadroom) {
    PumpCapacityStrategy strategy = new PumpCapacityStrategy(minimumHeadroom, 1.1);
    CapacityConstraint constraint = strategy.getConstraints(pump).get("npshMargin");
    assertNotNull(constraint, "fixture must generate an NPSH headroom constraint");
    return constraint;
  }
}
