package neqsim.process.engineering.numerics;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import neqsim.process.engineering.numerics.EngineeringNumericalHealthReport.ClosureObservation;
import neqsim.process.engineering.numerics.EngineeringNumericalHealthReport.JacobianHealth;
import neqsim.process.engineering.numerics.EngineeringNumericalHealthReport.ObservationStatus;
import neqsim.process.engineering.numerics.EngineeringNumericalHealthReport.ResidualObservation;
import neqsim.process.processmodel.ProcessSystem;

/** Builds a numerical-health report from a solved process and explicitly supplied engineering evidence. */
public final class EngineeringNumericalHealthAnalyzer {
  private final ProcessSystem process;
  private final EngineeringNumericalHealthCriteria criteria;
  private final List<ClosureObservation> energyClosure = new ArrayList<ClosureObservation>();
  private final List<ResidualObservation> equationResiduals = new ArrayList<ResidualObservation>();
  private JacobianHealth jacobianHealth;

  public EngineeringNumericalHealthAnalyzer(ProcessSystem process, EngineeringNumericalHealthCriteria criteria) {
    if (process == null) {
      throw new IllegalArgumentException("process must not be null");
    }
    this.process = process;
    this.criteria = criteria == null ? EngineeringNumericalHealthCriteria.defaults() : criteria;
  }

  public static EngineeringNumericalHealthReport analyze(ProcessSystem process) {
    return new EngineeringNumericalHealthAnalyzer(process, EngineeringNumericalHealthCriteria.defaults()).analyze();
  }

  /** Adds an energy imbalance and the non-zero energy-flow magnitude used to normalize it. */
  public EngineeringNumericalHealthAnalyzer addEnergyClosure(String scope, double imbalance, double referenceMagnitude,
      String unit) {
    String checkedScope = text(scope, "scope");
    String checkedUnit = text(unit, "unit");
    double relative = Double.isFinite(imbalance) && Double.isFinite(referenceMagnitude) && referenceMagnitude > 0.0
        ? 100.0 * Math.abs(imbalance) / Math.abs(referenceMagnitude)
        : Double.NaN;
    ObservationStatus status = !Double.isFinite(relative) ? ObservationStatus.NOT_AVAILABLE
        : relative <= criteria.getMaximumEnergyBalanceErrorPercent() ? ObservationStatus.PASS : ObservationStatus.FAIL;
    energyClosure.add(new ClosureObservation("ENERGY", checkedScope, finite(imbalance), finite(relative), checkedUnit,
        criteria.getMaximumEnergyBalanceErrorPercent(), status,
        status == ObservationStatus.PASS ? "Energy closure is within tolerance"
            : status == ObservationStatus.FAIL ? "Energy closure exceeds tolerance"
                : "A finite imbalance and positive finite reference magnitude are required"));
    return this;
  }

  /** Adds a named residual with its physical or numerical tolerance. */
  public EngineeringNumericalHealthAnalyzer addEquationResidual(String name, double value, double tolerance,
      String unit) {
    if (!Double.isFinite(tolerance) || tolerance <= 0.0) {
      throw new IllegalArgumentException("tolerance must be finite and positive");
    }
    equationResiduals.add(new ResidualObservation(text(name, "name"), value, tolerance, text(unit, "unit"),
        criteria.getMaximumNormalizedResidual()));
    return this;
  }

  /** Adds a sensitivity Jacobian generated by the automation sensitivity analyzer or another controlled source. */
  public EngineeringNumericalHealthAnalyzer sensitivityJacobian(double[][] matrix) {
    if (matrix == null) {
      throw new IllegalArgumentException("matrix must not be null");
    }
    jacobianHealth = new JacobianHealth(matrix, criteria.getMaximumJacobianScaleRatio());
    return this;
  }

  public EngineeringNumericalHealthReport analyze() {
    boolean converged = process.solved();
    String diagnostics = converged ? "Process simulation reports convergence" : process.getConvergenceDiagnostics();
    return new EngineeringNumericalHealthReport(process.getName(), converged, diagnostics, criteria, massClosure(),
        energyClosure, equationResiduals, jacobianHealth);
  }

  private List<ClosureObservation> massClosure() {
    Map<String, ProcessSystem.MassBalanceResult> raw = process.checkMassBalance(criteria.getMassBalanceUnit());
    List<Map.Entry<String, ProcessSystem.MassBalanceResult>> entries = new ArrayList<Map.Entry<String, ProcessSystem.MassBalanceResult>>(
        raw.entrySet());
    Collections.sort(entries, new Comparator<Map.Entry<String, ProcessSystem.MassBalanceResult>>() {
      @Override
      public int compare(Map.Entry<String, ProcessSystem.MassBalanceResult> left,
          Map.Entry<String, ProcessSystem.MassBalanceResult> right) {
        return left.getKey().compareTo(right.getKey());
      }
    });
    List<ClosureObservation> result = new ArrayList<ClosureObservation>();
    for (Map.Entry<String, ProcessSystem.MassBalanceResult> entry : entries) {
      ProcessSystem.MassBalanceResult value = entry.getValue();
      double absolute = value.getAbsoluteError();
      double relative = value.getPercentError();
      ObservationStatus status;
      String message;
      if (!Double.isFinite(absolute)) {
        status = ObservationStatus.NOT_AVAILABLE;
        message = "Unit operation did not expose a finite mass imbalance";
      } else if (!Double.isFinite(relative) && Math.abs(absolute) <= 1.0e-12) {
        status = ObservationStatus.NOT_APPLICABLE;
        message = "Zero reference inlet flow and zero absolute imbalance";
      } else if (!Double.isFinite(relative)) {
        status = ObservationStatus.NOT_AVAILABLE;
        message = "A finite reference inlet flow is required to assess relative closure";
      } else if (Math.abs(relative) <= criteria.getMaximumMassBalanceErrorPercent()) {
        status = ObservationStatus.PASS;
        message = "Mass closure is within tolerance";
      } else {
        status = ObservationStatus.FAIL;
        message = "Mass closure exceeds tolerance";
      }
      result.add(new ClosureObservation("MASS", entry.getKey(), finite(absolute), finite(relative), value.getUnit(),
          criteria.getMaximumMassBalanceErrorPercent(), status, message));
    }
    return result;
  }

  private static String text(String value, String name) {
    if (value == null || value.trim().isEmpty()) {
      throw new IllegalArgumentException(name + " must not be blank");
    }
    return value.trim();
  }

  private static Double finite(double value) {
    return Double.isFinite(value) ? Double.valueOf(value) : null;
  }
}
