package neqsim.process.equipment.subsea;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import neqsim.process.equipment.ProcessEquipmentBaseClass;

/**
 * Subsea power cable model for offshore wind farm export and inter-array connections.
 *
 * <p>
 * Models key engineering parameters for subsea power cables:
 * </p>
 * <ul>
 * <li>Cable ampacity and voltage drop calculations</li>
 * <li>Thermal rating with seawater cooling</li>
 * <li>Power losses (resistive, dielectric, sheath)</li>
 * <li>AC vs HVDC cable comparison</li>
 * <li>Reactive power compensation needs (AC cables)</li>
 * </ul>
 *
 * <h2>Cable Types</h2>
 * <ul>
 * <li><b>XLPE AC</b>: Cross-linked polyethylene, up to 245 kV</li>
 * <li><b>XLPE HVDC</b>: Cross-linked polyethylene HVDC, up to 640 kV</li>
 * <li><b>MI HVDC</b>: Mass-impregnated HVDC, up to 600 kV</li>
 * </ul>
 *
 * <h2>Design Standards</h2>
 * <ul>
 * <li>IEC 60287 — Current rating of cables (ampacity)</li>
 * <li>IEC 60228 — Conductors of insulated cables</li>
 * <li>IEC 62067 — Power cables with extruded insulation for rated voltages above 150 kV</li>
 * <li>CIGRE TB 610 — Offshore generation cable connections</li>
 * <li>DNV-RP-J301 — Subsea power cables in shallow water</li>
 * </ul>
 *
 * <h2>Usage Example</h2>
 *
 * <pre>{@code
 * SubseaPowerCable cable = new SubseaPowerCable("Export Cable");
 * cable.setCableType(SubseaPowerCable.CableType.XLPE_AC);
 * cable.setVoltage(66.0);            // kV
 * cable.setLength(50.0);             // km
 * cable.setPowerRating(500.0);       // MW
 * cable.setConductorArea(1000.0);    // mm^2
 * cable.setSeawaterTemperature(10.0); // C
 * cable.setBurialDepth(1.0);         // m
 * cable.run();
 *
 * double totalLoss = cable.getTotalPowerLoss(); // MW
 * double voltDrop = cable.getVoltageDrop();     // %
 * }</pre>
 *
 * @author esol
 * @version 1.0
 */
public class SubseaPowerCable extends ProcessEquipmentBaseClass {
  /** Serialization version UID. */
  private static final long serialVersionUID = 1000L;

  /**
   * Cable insulation type.
   */
  public enum CableType {
    /** XLPE AC cable. */
    XLPE_AC("XLPE AC"),
    /** XLPE HVDC cable. */
    XLPE_HVDC("XLPE HVDC"),
    /** Mass-impregnated HVDC cable. */
    MI_HVDC("MI HVDC");

    private final String displayName;

    CableType(String displayName) {
      this.displayName = displayName;
    }

    /**
     * Get display name.
     *
     * @return display name
     */
    public String getDisplayName() {
      return displayName;
    }
  }

  /** Cable type. */
  private CableType cableType = CableType.XLPE_AC;

  /** Rated voltage [kV]. */
  private double voltage = 66.0;

  /** Cable length [km]. */
  private double length = 50.0;

  /** Power transmitted [MW]. */
  private double powerRating = 500.0;

  /** Number of cables (for redundancy). */
  private int numberOfCables = 1;

  /** Number of cores per cable (1 for HVDC, 3 for AC). */
  private int numberOfCores = 3;

  /** Conductor cross-section area [mm2]. */
  private double conductorArea = 1000.0;

  /** Conductor material resistivity at 20C [ohm mm2/m]. */
  private double conductorResistivity = 0.01724;

  /** Temperature coefficient of resistance [1/K]. */
  private double tempCoefficient = 0.00393;

  /** Operating temperature of conductor [C]. */
  private double conductorTemperature = 90.0;

  /** Seawater temperature [C]. */
  private double seawaterTemperature = 10.0;

  /** Burial depth [m]. */
  private double burialDepth = 1.0;

  /** Water depth [m]. */
  private double waterDepth = 50.0;

  /** Power factor (for AC cables). */
  private double powerFactor = 0.95;

  /** Frequency [Hz] (50 or 60). */
  private double frequency = 50.0;

  /** Calculated total power loss [MW]. */
  private double totalPowerLoss = 0.0;

  /** Calculated resistive losses [MW]. */
  private double resistiveLoss = 0.0;

  /** Calculated dielectric losses [MW]. */
  private double dielectricLoss = 0.0;

  /** Calculated voltage drop [%]. */
  private double voltageDrop = 0.0;

  /** Calculated cable ampacity [A]. */
  private double ampacity = 0.0;

  /** Operating current [A]. */
  private double operatingCurrent = 0.0;

  /** Reactive power generated by cable capacitance [MVAr]. */
  private double reactivepower = 0.0;

  /** Cable cost estimate [MUSD]. */
  private double cableCost = 0.0;

  /** Efficiency (1 - loss fraction). */
  private double efficiency = 0.0;

  /**
   * Default constructor.
   */
  public SubseaPowerCable() {
    this("SubseaPowerCable");
  }

  /**
   * Construct with name.
   *
   * @param name equipment name
   */
  public SubseaPowerCable(String name) {
    super(name);
  }

  /** {@inheritDoc} */
  @Override
  public void run(UUID id) {
    // Calculate conductor resistance at operating temperature
    double rDC = conductorResistivity * length * 1000.0 / conductorArea;
    double rAC = rDC * (1.0 + tempCoefficient * (conductorTemperature - 20.0));

    // Skin effect and proximity factor for AC
    if (cableType == CableType.XLPE_AC) {
      double skinFactor = 1.0 + 0.02; // Simplified skin/proximity
      rAC = rAC * skinFactor;
    }

    // Calculate current
    if (cableType == CableType.XLPE_AC) {
      // AC: P = sqrt(3) * V * I * cos(phi)
      operatingCurrent = (powerRating * 1.0e6)
          / (Math.sqrt(3.0) * voltage * 1000.0 * powerFactor * numberOfCables);
    } else {
      // DC: P = V * I (bipole)
      operatingCurrent = (powerRating * 1.0e6) / (voltage * 1000.0 * numberOfCables * 2.0);
    }

    // Resistive losses per cable [W]
    double resistiveLossPerCable;
    if (cableType == CableType.XLPE_AC) {
      resistiveLossPerCable = numberOfCores * operatingCurrent * operatingCurrent * rAC;
    } else {
      resistiveLossPerCable = 2.0 * operatingCurrent * operatingCurrent * rAC;
    }
    resistiveLoss = resistiveLossPerCable * numberOfCables / 1.0e6;

    // Dielectric losses (AC only)
    if (cableType == CableType.XLPE_AC) {
      // Simplified: Wd = 2*pi*f * C * V^2 * tan(delta)
      // Capacitance ~ 0.2 uF/km for XLPE
      double capPerKm = 0.2e-6;
      double tanDelta = 0.001;
      double dielectricPerCable = 2.0 * Math.PI * frequency * capPerKm * length
          * (voltage * 1000.0) * (voltage * 1000.0) * tanDelta * numberOfCores;
      dielectricLoss = dielectricPerCable * numberOfCables / 1.0e6;

      // Reactive power from cable capacitance
      double qcPerKm = 2.0 * Math.PI * frequency * capPerKm
          * (voltage * 1000.0) * (voltage * 1000.0) / 1.0e6;
      reactivepower = qcPerKm * length * numberOfCables * numberOfCores;
    } else {
      dielectricLoss = 0.0;
      reactivepower = 0.0;
    }

    // Total losses
    totalPowerLoss = resistiveLoss + dielectricLoss;

    // Voltage drop
    if (cableType == CableType.XLPE_AC) {
      // dV = I * (R*cos(phi) + X*sin(phi)) * L
      // Inductance ~ 0.4 mH/km for trefoil
      double inductancePerKm = 0.4e-3;
      double xL = 2.0 * Math.PI * frequency * inductancePerKm * length;
      double rTotal = rAC;
      double cosP = powerFactor;
      double sinP = Math.sqrt(1.0 - cosP * cosP);
      double dropV = operatingCurrent * (rTotal * cosP + xL * sinP);
      voltageDrop = 100.0 * dropV / (voltage * 1000.0);
    } else {
      voltageDrop = 100.0 * operatingCurrent * rAC / (voltage * 1000.0);
    }

    // Ampacity (IEC 60287 simplified)
    // Maximum continuous current for conductor at max temperature
    double thermalResistance = 1.5; // K*m/W typical for seabed
    double maxTempRise = conductorTemperature - seawaterTemperature;
    if (rAC > 0) {
      double rPerMeter = rAC / (length * 1000.0);
      ampacity = Math.sqrt(maxTempRise / (rPerMeter * thermalResistance * numberOfCores));
    }

    // Efficiency
    efficiency = powerRating > 0 ? (powerRating - totalPowerLoss) / powerRating : 0.0;

    // Cost estimate (simplified)
    double costPerKm;
    if (cableType == CableType.XLPE_AC) {
      costPerKm = 0.8 + conductorArea / 2000.0; // MUSD/km, rough
    } else {
      costPerKm = 1.2 + conductorArea / 1500.0;
    }
    cableCost = costPerKm * length * numberOfCables;

    setCalculationIdentifier(id);
  }

  /**
   * Get total power loss [MW].
   *
   * @return total power loss [MW]
   */
  public double getTotalPowerLoss() {
    return totalPowerLoss;
  }

  /**
   * Get resistive power loss [MW].
   *
   * @return resistive loss [MW]
   */
  public double getResistiveLoss() {
    return resistiveLoss;
  }

  /**
   * Get dielectric loss [MW].
   *
   * @return dielectric loss [MW]
   */
  public double getDielectricLoss() {
    return dielectricLoss;
  }

  /**
   * Get voltage drop [%].
   *
   * @return voltage drop [%]
   */
  public double getVoltageDrop() {
    return voltageDrop;
  }

  /**
   * Get cable ampacity [A].
   *
   * @return ampacity [A]
   */
  public double getAmpacity() {
    return ampacity;
  }

  /**
   * Get operating current [A].
   *
   * @return operating current [A]
   */
  public double getOperatingCurrent() {
    return operatingCurrent;
  }

  /**
   * Get reactive power generated [MVAr].
   *
   * @return reactive power [MVAr]
   */
  public double getReactivePower() {
    return reactivepower;
  }

  /**
   * Get cable transmission efficiency [0-1].
   *
   * @return efficiency
   */
  public double getEfficiency() {
    return efficiency;
  }

  /**
   * Get estimated cable cost [MUSD].
   *
   * @return cable cost [MUSD]
   */
  public double getCableCost() {
    return cableCost;
  }

  /**
   * Get design results as a map.
   *
   * @return design results map
   */
  public Map<String, Object> getDesignResults() {
    Map<String, Object> results = new LinkedHashMap<String, Object>();
    results.put("cableType", cableType.getDisplayName());
    results.put("voltage_kV", voltage);
    results.put("length_km", length);
    results.put("powerRating_MW", powerRating);
    results.put("numberOfCables", numberOfCables);
    results.put("conductorArea_mm2", conductorArea);
    results.put("operatingCurrent_A", operatingCurrent);
    results.put("ampacity_A", ampacity);
    results.put("resistiveLoss_MW", resistiveLoss);
    results.put("dielectricLoss_MW", dielectricLoss);
    results.put("totalPowerLoss_MW", totalPowerLoss);
    results.put("voltageDrop_pct", voltageDrop);
    results.put("reactivePower_MVAr", reactivepower);
    results.put("efficiency_pct", efficiency * 100.0);
    results.put("cableCost_MUSD", cableCost);
    return results;
  }

  /**
   * Set cable type.
   *
   * @param type cable type
   */
  public void setCableType(CableType type) {
    this.cableType = type;
    if (type == CableType.XLPE_AC) {
      numberOfCores = 3;
    } else {
      numberOfCores = 1;
    }
  }

  /**
   * Get cable type.
   *
   * @return cable type
   */
  public CableType getCableType() {
    return cableType;
  }

  /**
   * Set rated voltage [kV].
   *
   * @param voltage rated voltage [kV]
   */
  public void setVoltage(double voltage) {
    this.voltage = voltage;
  }

  /**
   * Get rated voltage [kV].
   *
   * @return voltage [kV]
   */
  public double getVoltage() {
    return voltage;
  }

  /**
   * Set cable length [km].
   *
   * @param length cable length [km]
   */
  public void setLength(double length) {
    this.length = length;
  }

  /**
   * Get cable length [km].
   *
   * @return cable length [km]
   */
  public double getLength() {
    return length;
  }

  /**
   * Set power rating [MW].
   *
   * @param power power rating [MW]
   */
  public void setPowerRating(double power) {
    this.powerRating = power;
  }

  /**
   * Get power rating [MW].
   *
   * @return power [MW]
   */
  public double getPowerRating() {
    return powerRating;
  }

  /**
   * Set number of cables.
   *
   * @param n number of cables
   */
  public void setNumberOfCables(int n) {
    this.numberOfCables = n;
  }

  /**
   * Set conductor cross-section area [mm2].
   *
   * @param area conductor area [mm2]
   */
  public void setConductorArea(double area) {
    this.conductorArea = area;
  }

  /**
   * Get conductor area [mm2].
   *
   * @return conductor area [mm2]
   */
  public double getConductorArea() {
    return conductorArea;
  }

  /**
   * Set seawater temperature [C].
   *
   * @param temp seawater temperature [C]
   */
  public void setSeawaterTemperature(double temp) {
    this.seawaterTemperature = temp;
  }

  /**
   * Set cable burial depth [m].
   *
   * @param depth burial depth [m]
   */
  public void setBurialDepth(double depth) {
    this.burialDepth = depth;
  }

  /**
   * Set water depth [m].
   *
   * @param depth water depth [m]
   */
  public void setWaterDepth(double depth) {
    this.waterDepth = depth;
  }

  /**
   * Set power factor (AC cables only).
   *
   * @param pf power factor [0-1]
   */
  public void setPowerFactor(double pf) {
    this.powerFactor = pf;
  }

  /**
   * Set frequency [Hz].
   *
   * @param freq frequency [Hz]
   */
  public void setFrequency(double freq) {
    this.frequency = freq;
  }

  /**
   * Set conductor material resistivity at 20C [ohm mm2/m].
   *
   * @param resistivity conductor resistivity
   */
  public void setConductorResistivity(double resistivity) {
    this.conductorResistivity = resistivity;
  }

  /**
   * Set maximum conductor temperature [C].
   *
   * @param temp conductor temperature [C]
   */
  public void setConductorTemperature(double temp) {
    this.conductorTemperature = temp;
  }
}
