/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thermo_util_JNI_GERG2004EOS */

#ifndef _Included_thermo_util_JNI_GERG2004EOS
#define _Included_thermo_util_JNI_GERG2004EOS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    POTDX
 * Signature: (DDDDDDDDDDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_POTDX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    ZOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_ZOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    HOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_HOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    SOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_SOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    CPOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_CPOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    WOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_WOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    RJTOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_RJTOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    GOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_GOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    UOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_UOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    AOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_AOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    SFUGOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_thermo_util_JNI_GERG2004EOS_SFUGOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    SPHIOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_thermo_util_JNI_GERG2004EOS_SPHIOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    CVOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_CVOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    SALLOTPX
 * Signature: (DDDDDDDDDDDDDDDDDDDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_thermo_util_JNI_GERG2004EOS_SALLOTPX
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
