/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thermo_util_JNI_GERG2004EOS */

#ifndef _Included_thermo_util_JNI_GERG2004EOS
#define _Included_thermo_util_JNI_GERG2004EOS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thermo_util_JNI_GERG2004EOS
 * Method:    POTDX
 * Signature: (DDDDDDDDDDDDDDDDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_thermo_util_JNI_GERG2004EOS_POTDX
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
