package neqsim.process.util.optimizer;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Eclipse VFP (Vertical Flow Performance) table exporter.
 *
 * <p>
 * Generates Eclipse E300 compatible VFP tables for:
 * </p>
 * <ul>
 * <li>VFPPROD - Production well performance tables</li>
 * <li>VFPINJ - Injection well performance tables</li>
 * <li>VFPEXP - Export pipeline/processing facility tables</li>
 * </ul>
 *
 * <p>
 * <strong>VFP Table Format</strong>
 * </p>
 * <p>
 * VFP tables define the relationship between flowing bottom-hole pressure and production rate as a
 * function of various parameters (GOR, water cut, artificial lift, etc.).
 * </p>
 *
 * <p>
 * <strong>Example Usage</strong>
 * </p>
 * 
 * <pre>
 * EclipseVFPExporter exporter = new EclipseVFPExporter();
 * 
 * // Configure table
 * exporter.setTableNumber(1);
 * exporter.setDatumDepth(2500.0);
 * exporter.setFlowRates(new double[] {100, 500, 1000, 2000, 5000});
 * exporter.setTHPs(new double[] {10, 20, 30, 50, 70, 100});
 * exporter.setWaterCuts(new double[] {0, 0.2, 0.5, 0.8});
 * exporter.setGORs(new double[] {50, 100, 200, 500});
 * 
 * // Generate from lift curve data
 * exporter.setLiftCurveData(liftCurveData);
 * 
 * // Export
 * exporter.exportVFPPROD("well1_vfp.inc");
 * </pre>
 *
 * @author NeqSim Development Team
 * @version 1.0
 */
public class EclipseVFPExporter implements Serializable {

  /** Serialization version UID. */
  private static final long serialVersionUID = 1000L;

  /** Logger. */
  private static final Logger logger = LogManager.getLogger(EclipseVFPExporter.class);

  /** VFP table number. */
  private int tableNumber = 1;

  /** Datum depth in meters TVD. */
  private double datumDepth = 0.0;

  /** Flow rate type (OIL, LIQ, GAS, WAT, TM). */
  private String flowRateType = "OIL";

  /** Water cut type (WCT, WGR). */
  private String waterCutType = "WCT";

  /** GOR type (GOR, OGR, GLR). */
  private String gorType = "GOR";

  /** Flow rates for the table. */
  private double[] flowRates;

  /** Tubing head pressures (THP) in bara. */
  private double[] THPs;

  /** Water cuts (0-1). */
  private double[] waterCuts;

  /** Gas-oil ratios (Sm3/Sm3). */
  private double[] GORs;

  /** Artificial lift quantities (for gas lift). */
  private double[] ALQs;

  /** BHP values [flowRate][THP][waterCut][GOR][ALQ]. */
  private double[][][][][] BHPTable;

  /** Lift curve data source. */
  private transient ProcessOptimizationEngine.LiftCurveData liftCurveData;

  /** Unit system (METRIC, FIELD). */
  private String unitSystem = "METRIC";

  /** Table title/description. */
  private String tableTitle = "Generated by NeqSim";

  /**
   * Default constructor.
   */
  public EclipseVFPExporter() {}

  /**
   * Constructor with table number.
   *
   * @param tableNumber VFP table number
   */
  public EclipseVFPExporter(int tableNumber) {
    this.tableNumber = tableNumber;
  }

  /**
   * Exports a VFPPROD table to file.
   *
   * @param filename output filename
   * @throws IOException if file cannot be written
   */
  public void exportVFPPROD(String filename) throws IOException {
    try (BufferedWriter writer = new BufferedWriter(
        new OutputStreamWriter(new FileOutputStream(filename), StandardCharsets.UTF_8))) {
      writeVFPPROD(writer);
    }
    logger.info("Exported VFPPROD table {} to {}", tableNumber, filename);
  }

  /**
   * Exports a VFPINJ table to file.
   *
   * @param filename output filename
   * @throws IOException if file cannot be written
   */
  public void exportVFPINJ(String filename) throws IOException {
    try (BufferedWriter writer = new BufferedWriter(
        new OutputStreamWriter(new FileOutputStream(filename), StandardCharsets.UTF_8))) {
      writeVFPINJ(writer);
    }
    logger.info("Exported VFPINJ table {} to {}", tableNumber, filename);
  }

  /**
   * Exports a VFPEXP table to file for export pipelines/facilities.
   *
   * @param filename output filename
   * @throws IOException if file cannot be written
   */
  public void exportVFPEXP(String filename) throws IOException {
    try (BufferedWriter writer = new BufferedWriter(
        new OutputStreamWriter(new FileOutputStream(filename), StandardCharsets.UTF_8))) {
      writeVFPEXP(writer);
    }
    logger.info("Exported VFPEXP table {} to {}", tableNumber, filename);
  }

  /**
   * Gets the VFPPROD table as a string.
   *
   * @return VFPPROD table string
   */
  public String getVFPPRODString() {
    StringBuilder sb = new StringBuilder();
    try {
      writeVFPPRODContent(sb);
    } catch (IOException e) {
      logger.error("Error generating VFPPROD string", e);
    }
    return sb.toString();
  }

  /**
   * Gets the VFPINJ table as a string.
   *
   * @return VFPINJ table string
   */
  public String getVFPINJString() {
    StringBuilder sb = new StringBuilder();
    try {
      writeVFPINJContent(sb);
    } catch (IOException e) {
      logger.error("Error generating VFPINJ string", e);
    }
    return sb.toString();
  }

  /**
   * Writes VFPPROD to a writer.
   */
  private void writeVFPPROD(BufferedWriter writer) throws IOException {
    StringBuilder sb = new StringBuilder();
    writeVFPPRODContent(sb);
    writer.write(sb.toString());
  }

  /**
   * Writes VFPPROD content to a StringBuilder.
   *
   * <p>
   * Output format follows Eclipse VFP convention:
   * </p>
   * 
   * <pre>
   * VFPPROD
   *   TableNum  DatumDepth  'FlowType'  'WGR'  'OGR'  /
   *   FlowRate1  FlowRate2  ... /
   *   THP1  THP2  ... /
   *   0 /
   *   0 /
   *   0 /
   *   1  1  1  1  BHP1  BHP2  ... /
   *   2  1  1  1  BHP1  BHP2  ... /
   * </pre>
   */
  private void writeVFPPRODContent(Appendable out) throws IOException {
    // Header comments
    out.append("---------------------------------------------------------------------------\n");
    out.append("-- ").append(tableTitle).append("\n");
    out.append("-- Generated by NeqSim EclipseVFPExporter\n");
    out.append("-- Units: ").append(unitSystem).append("\n");
    out.append("---------------------------------------------------------------------------\n");

    out.append("VFPPROD\n\n");

    // Table header line - use quoted types for GAS systems with WGR/OGR
    out.append(String.format("  %d  %.0f  '%s'  '%s'  '%s'  /\n", tableNumber, datumDepth,
        flowRateType, waterCutType, gorType));

    // Flow rates (Sm3/d) - split across lines if many values
    writeArraySplitLines(out, flowRates, 6);
    out.append("/\n");

    // THPs (bara) - single line
    out.append("  ");
    if (THPs != null) {
      for (double thp : THPs) {
        out.append(String.format("%.0f  ", thp));
      }
    }
    out.append("\n/\n");

    // WGR - single value
    out.append("  0\n/\n");

    // OGR - single value
    out.append("  0\n/\n");

    // ALQ - single value
    out.append("  0\n/\n");

    // BHP tables with row index prefix
    writeBHPTablesWithIndex(out);
  }

  /**
   * Writes VFPINJ to a writer.
   */
  private void writeVFPINJ(BufferedWriter writer) throws IOException {
    StringBuilder sb = new StringBuilder();
    writeVFPINJContent(sb);
    writer.write(sb.toString());
  }

  /**
   * Writes VFPINJ content.
   */
  private void writeVFPINJContent(Appendable out) throws IOException {
    out.append("-- ").append(tableTitle).append("\n");
    out.append("-- Generated by NeqSim EclipseVFPExporter\n\n");

    out.append("VFPINJ\n");

    // Table header (simpler than VFPPROD)
    out.append(String.format("  %d %.2f %s %s %s /\n", tableNumber, datumDepth, flowRateType, "THP",
        unitSystem));

    // Flow rates
    out.append("-- Injection rates\n");
    writeArray(out, flowRates);

    // THPs
    out.append("-- THP values\n");
    writeArray(out, THPs);

    // BHP tables (2D for injection)
    out.append("-- BHP values\n");
    writeInjectionBHPTable(out);

    out.append("/\n\n");
  }

  /**
   * Writes VFPEXP (export system) table.
   */
  private void writeVFPEXP(BufferedWriter writer) throws IOException {
    StringBuilder sb = new StringBuilder();

    sb.append("-- Export System VFP Table\n");
    sb.append("-- ").append(tableTitle).append("\n");
    sb.append("-- Generated by NeqSim EclipseVFPExporter\n\n");

    // VFPEXP uses similar format to VFPPROD
    sb.append("VFPPROD\n");

    sb.append(String.format("  %d %.2f %s %s %s %s %s %s /\n", tableNumber, datumDepth,
        flowRateType, waterCutType, gorType, "THP", "BHP", unitSystem));

    // Same structure as VFPPROD
    sb.append("-- Flow rates\n");
    writeArray(sb, flowRates);

    sb.append("-- Outlet pressures (THP)\n");
    writeArray(sb, THPs);

    sb.append("-- Water cuts\n");
    writeArray(sb, waterCuts);

    sb.append("-- GOR values\n");
    writeArray(sb, GORs);

    sb.append("-- ALQ values (none for export)\n  0 /\n");

    sb.append("-- Required inlet pressure (BHP)\n");
    writeBHPTables(sb);

    sb.append("/\n\n");

    writer.write(sb.toString());
  }

  /**
   * Writes an array of values in Eclipse format.
   */
  private void writeArray(Appendable out, double[] values) throws IOException {
    if (values == null || values.length == 0) {
      out.append("  0 /\n");
      return;
    }

    out.append(" ");
    for (int i = 0; i < values.length; i++) {
      out.append(String.format(" %.4f", values[i]));
      if ((i + 1) % 8 == 0 && i < values.length - 1) {
        out.append("\n ");
      }
    }
    out.append(" /\n");
  }

  /**
   * Writes an array of values with line splitting after specified number of values.
   *
   * @param out output appendable
   * @param values array of values
   * @param valuesPerLine number of values per line before wrapping
   */
  private void writeArraySplitLines(Appendable out, double[] values, int valuesPerLine)
      throws IOException {
    if (values == null || values.length == 0) {
      out.append("  0\n");
      return;
    }

    for (int i = 0; i < values.length; i++) {
      if (i % valuesPerLine == 0) {
        out.append("  ");
      }
      out.append(String.format("%.2E  ", values[i]));
      if ((i + 1) % valuesPerLine == 0 && i < values.length - 1) {
        out.append("\n");
      }
    }
    out.append("\n");
  }

  /**
   * Writes BHP tables with row index prefix format.
   *
   * <p>
   * Format: rowIdx 1 1 1 BHP1 BHP2 ... /
   * </p>
   *
   * <p>
   * Missing values are filled with nearest valid value from same row.
   * </p>
   */
  private void writeBHPTablesWithIndex(Appendable out) throws IOException {
    if (BHPTable == null) {
      generateBHPFromLiftCurve();
    }

    if (BHPTable == null) {
      out.append("-- No BHP data available\n");
      return;
    }

    int nFlow = flowRates != null ? flowRates.length : 0;
    int nTHP = THPs != null ? THPs.length : 0;

    // Write one row per THP with index prefix
    for (int iTHP = 0; iTHP < nTHP; iTHP++) {
      int rowIdx = iTHP + 1;

      // Collect BHP values for this THP row
      double[] rowValues = new double[nFlow];
      boolean[] hasValue = new boolean[nFlow];

      for (int iFlow = 0; iFlow < nFlow; iFlow++) {
        double bhp = getBHPValue(iFlow, iTHP, 0, 0, 0);
        if (bhp > 0 && !Double.isNaN(bhp)) {
          rowValues[iFlow] = bhp;
          hasValue[iFlow] = true;
        }
      }

      // Fill missing values with nearest valid value from same row
      fillMissingWithNearest(rowValues, hasValue);

      // Write row with index prefix: rowIdx 1 1 1 values /
      out.append(String.format("  %d  1  1  1", rowIdx));
      for (int iFlow = 0; iFlow < nFlow; iFlow++) {
        out.append(String.format("  %.2f", rowValues[iFlow]));
      }
      out.append(" /\n");
    }
  }

  /**
   * Fills missing values in a row with the nearest valid value.
   *
   * @param values array of values (modified in place)
   * @param hasValue boolean array indicating which values are valid
   */
  private void fillMissingWithNearest(double[] values, boolean[] hasValue) {
    // Find indices of valid values
    int[] validIndices = new int[values.length];
    int validCount = 0;
    for (int i = 0; i < values.length; i++) {
      if (hasValue[i]) {
        validIndices[validCount++] = i;
      }
    }

    if (validCount == 0) {
      return; // No valid values to copy from
    }

    // Fill each missing value with nearest valid value
    for (int i = 0; i < values.length; i++) {
      if (!hasValue[i]) {
        int nearestIdx = validIndices[0];
        int minDist = Math.abs(i - nearestIdx);
        for (int j = 1; j < validCount; j++) {
          int dist = Math.abs(i - validIndices[j]);
          if (dist < minDist) {
            minDist = dist;
            nearestIdx = validIndices[j];
          }
        }
        values[i] = values[nearestIdx];
      }
    }
  }

  /**
   * Writes BHP tables (5D array).
   */
  private void writeBHPTables(Appendable out) throws IOException {
    if (BHPTable == null) {
      generateBHPFromLiftCurve();
    }

    if (BHPTable == null) {
      out.append("-- No BHP data available\n");
      return;
    }

    int nFlow = flowRates != null ? flowRates.length : 0;
    int nTHP = THPs != null ? THPs.length : 0;
    int nWC = waterCuts != null ? waterCuts.length : 0;
    int nGOR = GORs != null ? GORs.length : 0;
    int nALQ = ALQs != null ? ALQs.length : 1;

    for (int iALQ = 0; iALQ < nALQ; iALQ++) {
      for (int iGOR = 0; iGOR < nGOR; iGOR++) {
        for (int iWC = 0; iWC < nWC; iWC++) {
          out.append(String.format("-- ALQ=%d GOR=%d WCT=%d\n", iALQ + 1, iGOR + 1, iWC + 1));
          for (int iTHP = 0; iTHP < nTHP; iTHP++) {
            out.append(" ");
            for (int iFlow = 0; iFlow < nFlow; iFlow++) {
              double bhp = getBHPValue(iFlow, iTHP, iWC, iGOR, iALQ);
              out.append(String.format(" %.2f", bhp));
            }
            out.append(" /\n");
          }
        }
      }
    }
  }

  /**
   * Writes injection BHP table (2D).
   */
  private void writeInjectionBHPTable(Appendable out) throws IOException {
    int nFlow = flowRates != null ? flowRates.length : 0;
    int nTHP = THPs != null ? THPs.length : 0;

    for (int iTHP = 0; iTHP < nTHP; iTHP++) {
      out.append(" ");
      for (int iFlow = 0; iFlow < nFlow; iFlow++) {
        double bhp = getBHPValue(iFlow, iTHP, 0, 0, 0);
        out.append(String.format(" %.2f", bhp));
      }
      out.append(" /\n");
    }
  }

  /**
   * Gets a BHP value from the table.
   */
  private double getBHPValue(int iFlow, int iTHP, int iWC, int iGOR, int iALQ) {
    if (BHPTable != null && iFlow < BHPTable.length && iTHP < BHPTable[iFlow].length
        && iWC < BHPTable[iFlow][iTHP].length && iGOR < BHPTable[iFlow][iTHP][iWC].length
        && iALQ < BHPTable[iFlow][iTHP][iWC][iGOR].length) {
      return BHPTable[iFlow][iTHP][iWC][iGOR][iALQ];
    }

    // Default calculation if no table
    double flow = flowRates != null && iFlow < flowRates.length ? flowRates[iFlow] : 0;
    double thp = THPs != null && iTHP < THPs.length ? THPs[iTHP] : 0;
    double wc = waterCuts != null && iWC < waterCuts.length ? waterCuts[iWC] : 0;
    double gor = GORs != null && iGOR < GORs.length ? GORs[iGOR] : 0;

    // Simple correlation (would be replaced with actual calculations)
    return thp + 0.001 * flow * (1 + wc) + 0.0001 * gor;
  }

  /**
   * Generates BHP table from lift curve data.
   */
  private void generateBHPFromLiftCurve() {
    if (liftCurveData == null || flowRates == null || THPs == null) {
      return;
    }

    int nFlow = flowRates.length;
    int nTHP = THPs.length;
    int nWC = waterCuts != null ? waterCuts.length : 1;
    int nGOR = GORs != null ? GORs.length : 1;
    int nALQ = ALQs != null ? ALQs.length : 1;

    BHPTable = new double[nFlow][nTHP][nWC][nGOR][nALQ];

    // Interpolate from lift curve data
    for (ProcessOptimizationEngine.LiftCurvePoint point : liftCurveData.getPoints()) {
      // Find indices
      int iWC = findIndex(waterCuts, point.getWaterCut());
      int iGOR = findIndex(GORs, point.getGOR());
      int iTHP = findIndex(THPs, point.getInletPressure());

      if (iWC >= 0 && iGOR >= 0 && iTHP >= 0) {
        // Map max flow rate to BHP relationship
        for (int iFlow = 0; iFlow < nFlow; iFlow++) {
          for (int iALQ = 0; iALQ < nALQ; iALQ++) {
            // Calculate BHP based on flow vs max flow
            double ratio = flowRates[iFlow] / point.getMaxFlowRate();
            double bhp = point.getInletPressure() * (1 + 0.1 * ratio);
            BHPTable[iFlow][iTHP][iWC][iGOR][iALQ] = bhp;
          }
        }
      }
    }
  }

  /**
   * Finds the closest index in an array.
   */
  private int findIndex(double[] array, double value) {
    if (array == null || array.length == 0) {
      return 0;
    }

    int bestIndex = 0;
    double bestDiff = Math.abs(array[0] - value);

    for (int i = 1; i < array.length; i++) {
      double diff = Math.abs(array[i] - value);
      if (diff < bestDiff) {
        bestDiff = diff;
        bestIndex = i;
      }
    }

    return bestIndex;
  }

  /**
   * Creates a COMPDAT style export for compressor data.
   *
   * @param wellName well/connection name
   * @return COMPDAT string
   */
  public String exportCOMPDAT(String wellName) {
    StringBuilder sb = new StringBuilder();

    sb.append("-- Compressor/Facility connection data\n");
    sb.append("-- Generated by NeqSim\n\n");

    sb.append("COMPDAT\n");
    sb.append(String.format("  '%s' 1* 1* 1* 'OPEN' 1* 1* 0.1 1* 0 0 'Z' /\n", wellName));
    sb.append("/\n\n");

    sb.append("WCONPROD\n");
    sb.append(String.format("  '%s' 'OPEN' 'ORAT' 1* 4* %.2f /\n", wellName,
        flowRates != null && flowRates.length > 0 ? flowRates[flowRates.length - 1] : 10000));
    sb.append("/\n\n");

    return sb.toString();
  }

  /**
   * Exports VFP tables for multiple scenarios.
   *
   * @param scenarios list of scenario configurations
   * @param baseFilename base filename for outputs
   * @throws IOException if files cannot be written
   */
  public void exportMultipleScenarios(List<VFPScenario> scenarios, String baseFilename)
      throws IOException {
    for (int i = 0; i < scenarios.size(); i++) {
      VFPScenario scenario = scenarios.get(i);
      setTableNumber(scenario.getTableNumber());
      setFlowRates(scenario.getFlowRates());
      setTHPs(scenario.getTHPs());
      setWaterCuts(scenario.getWaterCuts());
      setGORs(scenario.getGORs());
      setBHPTable(scenario.getBHPTable());

      String filename = baseFilename + "_" + scenario.getTableNumber() + ".inc";
      exportVFPPROD(filename);
    }
  }

  // Getters and setters

  /**
   * Gets the table number.
   *
   * @return table number
   */
  public int getTableNumber() {
    return tableNumber;
  }

  /**
   * Sets the table number.
   *
   * @param tableNumber VFP table number
   */
  public void setTableNumber(int tableNumber) {
    this.tableNumber = tableNumber;
  }

  /**
   * Gets the datum depth.
   *
   * @return datum depth in meters
   */
  public double getDatumDepth() {
    return datumDepth;
  }

  /**
   * Sets the datum depth.
   *
   * @param depth datum depth in meters TVD
   */
  public void setDatumDepth(double depth) {
    this.datumDepth = depth;
  }

  /**
   * Gets the flow rate type.
   *
   * @return flow rate type
   */
  public String getFlowRateType() {
    return flowRateType;
  }

  /**
   * Sets the flow rate type.
   *
   * @param type flow rate type (OIL, LIQ, GAS, WAT, TM)
   */
  public void setFlowRateType(String type) {
    this.flowRateType = type;
  }

  /**
   * Gets the flow rates.
   *
   * @return flow rate array
   */
  public double[] getFlowRates() {
    return flowRates;
  }

  /**
   * Sets the flow rates.
   *
   * @param rates flow rate array
   */
  public void setFlowRates(double[] rates) {
    this.flowRates = rates;
  }

  /**
   * Gets the THP values.
   *
   * @return THP array
   */
  public double[] getTHPs() {
    return THPs;
  }

  /**
   * Sets the THP values.
   *
   * @param thps THP array in bara
   */
  public void setTHPs(double[] thps) {
    this.THPs = thps;
  }

  /**
   * Gets the water cuts.
   *
   * @return water cut array
   */
  public double[] getWaterCuts() {
    return waterCuts;
  }

  /**
   * Sets the water cuts.
   *
   * @param wcs water cut array (0-1)
   */
  public void setWaterCuts(double[] wcs) {
    this.waterCuts = wcs;
  }

  /**
   * Gets the GORs.
   *
   * @return GOR array
   */
  public double[] getGORs() {
    return GORs;
  }

  /**
   * Sets the GORs.
   *
   * @param gors GOR array in Sm3/Sm3
   */
  public void setGORs(double[] gors) {
    this.GORs = gors;
  }

  /**
   * Gets the ALQs.
   *
   * @return ALQ array
   */
  public double[] getALQs() {
    return ALQs;
  }

  /**
   * Sets the ALQs.
   *
   * @param alqs ALQ array (gas lift quantity)
   */
  public void setALQs(double[] alqs) {
    this.ALQs = alqs;
  }

  /**
   * Gets the BHP table.
   *
   * @return BHP table array
   */
  public double[][][][][] getBHPTable() {
    return BHPTable;
  }

  /**
   * Sets the BHP table.
   *
   * @param table BHP table [flow][THP][WC][GOR][ALQ]
   */
  public void setBHPTable(double[][][][][] table) {
    this.BHPTable = table;
  }

  /**
   * Gets the unit system.
   *
   * @return unit system
   */
  public String getUnitSystem() {
    return unitSystem;
  }

  /**
   * Sets the unit system.
   *
   * @param system unit system (METRIC, FIELD)
   */
  public void setUnitSystem(String system) {
    this.unitSystem = system;
  }

  /**
   * Gets the table title.
   *
   * @return table title
   */
  public String getTableTitle() {
    return tableTitle;
  }

  /**
   * Sets the table title.
   *
   * @param title table title/description
   */
  public void setTableTitle(String title) {
    this.tableTitle = title;
  }

  /**
   * Sets the lift curve data.
   *
   * @param data lift curve data
   */
  public void setLiftCurveData(ProcessOptimizationEngine.LiftCurveData data) {
    this.liftCurveData = data;
    BHPTable = null; // Clear cached table
  }

  /**
   * VFP scenario configuration.
   */
  public static class VFPScenario implements Serializable {
    private static final long serialVersionUID = 1L;
    private int tableNumber;
    private double[] flowRates;
    private double[] THPs;
    private double[] waterCuts;
    private double[] GORs;
    private double[][][][][] BHPTable;
    private String description;

    public int getTableNumber() {
      return tableNumber;
    }

    public void setTableNumber(int num) {
      this.tableNumber = num;
    }

    public double[] getFlowRates() {
      return flowRates;
    }

    public void setFlowRates(double[] rates) {
      this.flowRates = rates;
    }

    public double[] getTHPs() {
      return THPs;
    }

    public void setTHPs(double[] thps) {
      this.THPs = thps;
    }

    public double[] getWaterCuts() {
      return waterCuts;
    }

    public void setWaterCuts(double[] wcs) {
      this.waterCuts = wcs;
    }

    public double[] getGORs() {
      return GORs;
    }

    public void setGORs(double[] gors) {
      this.GORs = gors;
    }

    public double[][][][][] getBHPTable() {
      return BHPTable;
    }

    public void setBHPTable(double[][][][][] table) {
      this.BHPTable = table;
    }

    public String getDescription() {
      return description;
    }

    public void setDescription(String desc) {
      this.description = desc;
    }
  }
}
