package neqsim.process.util.optimizer;

import java.io.IOException;
import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Locale;

/**
 * Formats supplied bottomhole pressures as OPM/Eclipse VFPPROD or VFPINJ records.
 *
 * <p>
 * Inputs are standard surface volume rates (default Sm3/day), absolute pressures (default bara), datum depth in metres
 * TVD, composition ratios in Sm3/Sm3 and gas-lift quantities in Sm3/day. {@link #setInputUnits(String, String)} changes
 * only the production/injection rate and pressure input units. {@link #setUnitSystem(String)} selects METRIC or FIELD
 * output and converts every dimensional axis and pressure. FIELD gas volume is Mscf, including gas/liquid ratios.
 * Standard volumes must already refer to the reservoir deck's surface reference conditions; this formatter does not
 * flash a fluid or change its reference conditions.
 * </p>
 *
 * <p>
 * The supplied array order is [flow][THP][water ratio][gas ratio][ALQ]. Every combination is exported with one-based
 * THP, water, gas and ALQ indices. Missing, non-finite or infeasible BHP values are rejected; no correlation,
 * nearest-neighbour fill or extrapolation is performed. BHP must be the flowing well pressure at the specified datum.
 * Process outlet pressures and throughput maxima are not BHP. This class qualifies the deck representation, not a well
 * model.
 * </p>
 *
 * <p>
 * Supported production definitions: OIL/LIQ/GAS, WCT/WOR/WGR, GOR/GLR/OGR, THP, BHP, and either no artificial lift
 * (singleton zero) or GRAT. Injection supports OIL/WAT/GAS with singleton zero composition and ALQ axes. Other dialects
 * and definitions fail explicitly.
 * </p>
 */
public class EclipseVFPExporter implements Serializable {
  private static final long serialVersionUID = 1000L;
  private static final double CUBIC_METRES_PER_STB = 0.158987294928;
  private static final double CUBIC_METRES_PER_MSCF = 28.316846592;
  private static final double PASCALS_PER_PSI = 6894.757293168;
  private int tableNumber = 1;
  private double datumDepth;
  private String flowRateType = "OIL";
  private String waterCutType = "WCT";
  private String gorType = "GOR";
  private String alqType = "";
  private String inputFlowRateUnit = "Sm3/day";
  private String inputPressureUnit = "bara";
  private double[] flowRates;
  private double[] THPs;
  private double[] waterCuts;
  private double[] GORs;
  private double[] ALQs;
  private double[][][][][] BHPTable;
  private String unitSystem = "METRIC";
  private String tableTitle = "Generated by NeqSim";

  /** Creates a formatter for table 1. */
  public EclipseVFPExporter() {
  }

  /**
   * Creates a formatter.
   *
   * @param tableNumber positive table number
   */
  public EclipseVFPExporter(int tableNumber) {
    this.tableNumber = tableNumber;
  }

  /**
   * Writes a complete validated production table. Validation precedes opening the destination.
   *
   * @param filename output path
   * @throws IOException if the file cannot be written
   * @throws IllegalArgumentException if axes, units or pressure data are invalid
   */
  public void exportVFPPROD(String filename) throws IOException {
    String content = getVFPPRODString();
    Files.write(Paths.get(filename), content.getBytes(StandardCharsets.UTF_8));
  }

  /**
   * Writes a complete validated injection table. Validation precedes opening the destination.
   *
   * @param filename output path
   * @throws IOException if the file cannot be written
   * @throws IllegalArgumentException if axes, units or pressure data are invalid
   */
  public void exportVFPINJ(String filename) throws IOException {
    String content = getVFPINJString();
    Files.write(Paths.get(filename), content.getBytes(StandardCharsets.UTF_8));
  }

  /**
   * Rejects the legacy export-system format, which has no supported deck contract.
   *
   * @param filename unused output path; no file is opened
   * @throws IOException retained for source compatibility
   * @throws UnsupportedOperationException always; use process capacity CSV/JSON for screening
   * @deprecated no VFPEXP dialect is implemented; only supplied well BHP may use VFPPROD
   */
  @Deprecated
  public void exportVFPEXP(String filename) throws IOException {
    throw new UnsupportedOperationException("VFPEXP is not a supported deck dialect. "
        + "Use process capacity CSV/JSON; supply independently qualified well BHP to VFPPROD.");
  }

  /**
   * Formats all supplied production axes and pressure values.
   *
   * @return OPM/Eclipse VFPPROD keyword with explicit definitions and units
   * @throws IllegalArgumentException if inputs are unsupported, incomplete or infeasible
   */
  public String getVFPPRODString() {
    return format(false);
  }

  /**
   * Formats a supplied two-dimensional injection pressure table.
   *
   * @return OPM/Eclipse VFPINJ keyword with indexed THP rows
   * @throws IllegalArgumentException if inputs are unsupported, incomplete or infeasible
   */
  public String getVFPINJString() {
    return format(true);
  }

  private String format(boolean injection) {
    double[] water = axisOrZero(waterCuts);
    double[] gas = axisOrZero(GORs);
    double[] lift = axisOrZero(ALQs);
    validate(injection, water, gas, lift);
    boolean field = "FIELD".equals(unitSystem);
    double rateFactor = rateToSm3PerDay()
        / (field ? ("GAS".equals(flowRateType) ? CUBIC_METRES_PER_MSCF : CUBIC_METRES_PER_STB) : 1.0);
    double pressureFactor = pressureToPa() / (field ? PASCALS_PER_PSI : 100000.0);
    double gasLiquidFactor = field ? CUBIC_METRES_PER_STB / CUBIC_METRES_PER_MSCF : 1.0;
    StringBuilder out = new StringBuilder();
    out.append("-- ").append(tableTitle == null ? "" : tableTitle.replace('\n', ' ').replace('\r', ' '));
    out.append("\n-- Supplied well BHP at datum; generated by NeqSim\n");
    out.append(injection ? "VFPINJ\n" : "VFPPROD\n");
    out.append("  ").append(tableNumber).append(' ');
    appendNumber(out, datumDepth / (field ? 0.3048 : 1.0));
    out.append(" '").append(flowRateType).append("' ");
    if (!injection) {
      out.append("'").append(waterCutType).append("' '").append(gorType).append("' ");
    }
    out.append("'THP' ");
    if (!injection) {
      out.append("'").append(alqType).append("' ");
    }
    out.append("'").append(unitSystem).append("' 'BHP' /\n");
    appendAxis(out, flowRates, rateFactor);
    appendAxis(out, THPs, pressureFactor);
    if (!injection) {
      appendAxis(out, water, "WGR".equals(waterCutType) ? 1.0 / gasLiquidFactor : 1.0);
      appendAxis(out, gas, "OGR".equals(gorType) ? 1.0 / gasLiquidFactor : gasLiquidFactor);
      appendAxis(out, lift, field && "GRAT".equals(alqType) ? 1.0 / CUBIC_METRES_PER_MSCF : 1.0);
    }
    for (int t = 0; t < THPs.length; t++) {
      for (int w = 0; w < water.length; w++) {
        for (int g = 0; g < gas.length; g++) {
          for (int a = 0; a < lift.length; a++) {
            out.append("  ").append(t + 1);
            if (!injection) {
              out.append(' ').append(w + 1).append(' ').append(g + 1).append(' ').append(a + 1);
            }
            for (int f = 0; f < flowRates.length; f++) {
              out.append(' ');
              appendNumber(out, BHPTable[f][t][w][g][a] * pressureFactor);
            }
            out.append(" /\n");
          }
        }
      }
    }
    return out.toString();
  }

  private void validate(boolean injection, double[] water, double[] gas, double[] lift) {
    require(tableNumber > 0 && Double.isFinite(datumDepth), "Table number must be positive and datum finite");
    require("METRIC".equals(unitSystem) || "FIELD".equals(unitSystem), "Supported deck units: METRIC, FIELD");
    require(
        "OIL".equals(flowRateType) || "GAS".equals(flowRateType)
            || (injection ? "WAT".equals(flowRateType) : "LIQ".equals(flowRateType)),
        "Unsupported rate basis for " + (injection ? "VFPINJ" : "VFPPROD") + ": " + flowRateType);
    require("WCT".equals(waterCutType) || "WOR".equals(waterCutType) || "WGR".equals(waterCutType),
        "Supported water ratios: WCT, WOR, WGR");
    require("GOR".equals(gorType) || "GLR".equals(gorType) || "OGR".equals(gorType),
        "Supported gas ratios: GOR, GLR, OGR");
    require("".equals(alqType) || "GRAT".equals(alqType), "Supported ALQ types: empty or GRAT");
    rateToSm3PerDay();
    pressureToPa();
    validateAxis("flow", flowRates, false);
    validateAxis("THP", THPs, true);
    validateAxis("water ratio", water, false);
    validateAxis("gas ratio", gas, false);
    validateAxis("ALQ", lift, false);
    require(!"WCT".equals(waterCutType) || water[water.length - 1] <= 1.0, "WCT must be in [0, 1]");
    require(!"".equals(alqType) || (lift.length == 1 && lift[0] == 0.0),
        "Nonzero or multiple ALQ values require explicit GRAT type");
    if (injection) {
      require(water.length == 1 && water[0] == 0.0 && gas.length == 1 && gas[0] == 0.0 && lift.length == 1
          && lift[0] == 0.0, "VFPINJ requires singleton zero composition and ALQ axes");
    }
    require(BHPTable != null && BHPTable.length == flowRates.length,
        "Supply complete BHP data in [flow][THP][water][gas][ALQ] order");
    for (int f = 0; f < flowRates.length; f++) {
      require(BHPTable[f] != null && BHPTable[f].length == THPs.length, "BHP THP dimension mismatch");
      for (int t = 0; t < THPs.length; t++) {
        require(BHPTable[f][t] != null && BHPTable[f][t].length == water.length, "BHP water dimension mismatch");
        for (int w = 0; w < water.length; w++) {
          require(BHPTable[f][t][w] != null && BHPTable[f][t][w].length == gas.length, "BHP gas dimension mismatch");
          for (int g = 0; g < gas.length; g++) {
            require(BHPTable[f][t][w][g] != null && BHPTable[f][t][w][g].length == lift.length,
                "BHP ALQ dimension mismatch");
            for (int a = 0; a < lift.length; a++) {
              double p = BHPTable[f][t][w][g][a];
              require(Double.isFinite(p) && p > 0.0, "Missing or infeasible BHP at zero-based indices [" + f + "][" + t
                  + "][" + w + "][" + g + "][" + a + "]");
            }
          }
        }
      }
    }
  }

  private static double[] axisOrZero(double[] values) {
    return values == null ? new double[] { 0.0 } : values;
  }

  private static void validateAxis(String name, double[] values, boolean positive) {
    require(values != null && values.length > 0, name + " axis must be supplied and nonempty");
    for (int i = 0; i < values.length; i++) {
      require(
          Double.isFinite(values[i]) && (positive ? values[i] > 0.0 : values[i] >= 0.0)
              && (i == 0 || values[i] > values[i - 1]),
          name + " axis must be finite and strictly increasing"
              + (positive ? " with positive pressures" : " with nonnegative values"));
    }
  }

  private static void require(boolean valid, String message) {
    if (!valid) {
      throw new IllegalArgumentException(message);
    }
  }

  private double rateToSm3PerDay() {
    if ("Sm3/day".equals(inputFlowRateUnit)) {
      return 1.0;
    }
    if ("Sm3/hr".equals(inputFlowRateUnit)) {
      return 24.0;
    }
    if ("Sm3/s".equals(inputFlowRateUnit)) {
      return 86400.0;
    }
    throw new IllegalArgumentException(
        "Supported input rates: Sm3/day, Sm3/hr, Sm3/s; mass/actual volume is not VFP flow");
  }

  private double pressureToPa() {
    if ("bara".equals(inputPressureUnit)) {
      return 100000.0;
    }
    if ("Pa".equals(inputPressureUnit)) {
      return 1.0;
    }
    if ("psia".equals(inputPressureUnit)) {
      return PASCALS_PER_PSI;
    }
    throw new IllegalArgumentException(
        "Supported absolute input pressures: bara, Pa, psia; gauge units are unsupported");
  }

  private static void appendNumber(StringBuilder out, double value) {
    require(Double.isFinite(value), "Unit conversion overflow");
    out.append(Double.toString(value));
  }

  private static void appendAxis(StringBuilder out, double[] values, double factor) {
    out.append("  ");
    for (double value : values) {
      appendNumber(out, value * factor);
      out.append(' ');
    }
    out.append("/\n");
  }

  /**
   * Sets rate and absolute pressure units for supplied axes and BHP values.
   *
   * @param rateUnit Sm3/day, Sm3/hr or Sm3/s of the selected surface phase basis
   * @param pressureUnit bara, Pa or psia; applies to both THP and BHP
   */
  public void setInputUnits(String rateUnit, String pressureUnit) {
    inputFlowRateUnit = rateUnit;
    inputPressureUnit = pressureUnit;
  }

  /**
   * Sets the water fraction/ratio definition. All ratios use surface Sm3/Sm3 input.
   *
   * @param type WCT (water/liquid), WOR (water/oil) or WGR (water/gas)
   */
  public void setWaterCutType(String type) {
    waterCutType = type == null ? null : type.toUpperCase(Locale.ROOT);
  }

  /**
   * Sets the gas fraction/ratio definition. All ratios use surface Sm3/Sm3 input.
   *
   * @param type GOR (gas/oil), GLR (gas/liquid) or OGR (oil/gas)
   */
  public void setGORType(String type) {
    gorType = type == null ? null : type.toUpperCase(Locale.ROOT);
  }

  /**
   * Sets the artificial lift definition.
   *
   * @param type empty for no lift (singleton zero), or GRAT for lift gas rate in Sm3/day
   */
  public void setALQType(String type) {
    alqType = type == null ? null : type.toUpperCase(Locale.ROOT);
  }

  /**
   * Creates a COMPDAT style export for compressor data.
   *
   * @param wellName well/connection name
   * @return COMPDAT string
   */
  public String exportCOMPDAT(String wellName) {
    StringBuilder sb = new StringBuilder();

    sb.append("-- Compressor/Facility connection data\n");
    sb.append("-- Generated by NeqSim\n\n");

    sb.append("COMPDAT\n");
    sb.append(String.format("  '%s' 1* 1* 1* 'OPEN' 1* 1* 0.1 1* 0 0 'Z' /\n", wellName));
    sb.append("/\n\n");

    sb.append("WCONPROD\n");
    sb.append(String.format("  '%s' 'OPEN' 'ORAT' 1* 4* %.2f /\n", wellName,
        flowRates != null && flowRates.length > 0 ? flowRates[flowRates.length - 1] : 10000));
    sb.append("/\n\n");

    return sb.toString();
  }

  /**
   * Exports VFP tables for multiple scenarios.
   *
   * @param scenarios list of scenario configurations
   * @param baseFilename base filename for outputs
   * @throws IOException if files cannot be written
   */
  public void exportMultipleScenarios(List<VFPScenario> scenarios, String baseFilename) throws IOException {
    for (int i = 0; i < scenarios.size(); i++) {
      VFPScenario scenario = scenarios.get(i);
      setTableNumber(scenario.getTableNumber());
      setFlowRates(scenario.getFlowRates());
      setTHPs(scenario.getTHPs());
      setWaterCuts(scenario.getWaterCuts());
      setGORs(scenario.getGORs());
      setBHPTable(scenario.getBHPTable());

      String filename = baseFilename + "_" + scenario.getTableNumber() + ".inc";
      exportVFPPROD(filename);
    }
  }

  // Getters and setters

  /**
   * Gets the table number.
   *
   * @return table number
   */
  public int getTableNumber() {
    return tableNumber;
  }

  /**
   * Sets the table number.
   *
   * @param tableNumber VFP table number
   */
  public void setTableNumber(int tableNumber) {
    this.tableNumber = tableNumber;
  }

  /**
   * Gets the datum depth.
   *
   * @return datum depth in meters
   */
  public double getDatumDepth() {
    return datumDepth;
  }

  /**
   * Sets the datum depth.
   *
   * @param depth datum depth in meters TVD
   */
  public void setDatumDepth(double depth) {
    this.datumDepth = depth;
  }

  /**
   * Gets the flow rate type.
   *
   * @return flow rate type
   */
  public String getFlowRateType() {
    return flowRateType;
  }

  /**
   * Sets the flow rate type.
   *
   * @param type OIL/LIQ/GAS for production; OIL/WAT/GAS for injection
   */
  public void setFlowRateType(String type) {
    this.flowRateType = type == null ? null : type.toUpperCase(Locale.ROOT);
  }

  /**
   * Gets the flow rates.
   *
   * @return flow rate array
   */
  public double[] getFlowRates() {
    return flowRates;
  }

  /**
   * Sets the flow rates.
   *
   * @param rates standard surface volume rates in the configured input rate unit
   */
  public void setFlowRates(double[] rates) {
    this.flowRates = rates;
  }

  /**
   * Gets the THP values.
   *
   * @return THP array
   */
  public double[] getTHPs() {
    return THPs;
  }

  /**
   * Sets the THP values.
   *
   * @param thps absolute THP values in the configured input pressure unit
   */
  public void setTHPs(double[] thps) {
    this.THPs = thps;
  }

  /**
   * Gets the water cuts.
   *
   * @return water cut array
   */
  public double[] getWaterCuts() {
    return waterCuts;
  }

  /**
   * Sets the water cuts.
   *
   * @param wcs water ratio in Sm3/Sm3 (WCT is bounded by 0 and 1)
   */
  public void setWaterCuts(double[] wcs) {
    this.waterCuts = wcs;
  }

  /**
   * Gets the GORs.
   *
   * @return GOR array
   */
  public double[] getGORs() {
    return GORs;
  }

  /**
   * Sets the GORs.
   *
   * @param gors GOR array in Sm3/Sm3
   */
  public void setGORs(double[] gors) {
    this.GORs = gors;
  }

  /**
   * Gets the ALQs.
   *
   * @return ALQ array
   */
  public double[] getALQs() {
    return ALQs;
  }

  /**
   * Sets the ALQs.
   *
   * @param alqs gas lift rates in Sm3/day for GRAT, or singleton zero for no lift
   */
  public void setALQs(double[] alqs) {
    this.ALQs = alqs;
  }

  /**
   * Gets the BHP table.
   *
   * @return BHP table array
   */
  public double[][][][][] getBHPTable() {
    return BHPTable;
  }

  /**
   * Sets the BHP table.
   *
   * @param table supplied well BHP at datum in configured pressure units, [flow][THP][WC][GOR][ALQ]
   */
  public void setBHPTable(double[][][][][] table) {
    this.BHPTable = table;
  }

  /**
   * Gets the unit system.
   *
   * @return unit system
   */
  public String getUnitSystem() {
    return unitSystem;
  }

  /**
   * Sets output deck units; all dimensional inputs are converted from their documented units.
   *
   * @param system unit system (METRIC, FIELD)
   */
  public void setUnitSystem(String system) {
    this.unitSystem = system == null ? null : system.toUpperCase(Locale.ROOT);
  }

  /**
   * Gets the table title.
   *
   * @return table title
   */
  public String getTableTitle() {
    return tableTitle;
  }

  /**
   * Sets the table title.
   *
   * @param title table title/description
   */
  public void setTableTitle(String title) {
    this.tableTitle = title;
  }

  /**
   * Rejects process capacity screening data, which do not contain well BHP.
   *
   * @param data unsupported process screening data
   * @throws UnsupportedOperationException always
   * @deprecated supply independently qualified well BHP with {@link #setBHPTable(double[][][][][])}
   */
  @Deprecated
  public void setLiftCurveData(ProcessOptimizationEngine.LiftCurveData data) {
    throw new UnsupportedOperationException("Process capacity screening is not well BHP. Use setBHPTable with "
        + "independently qualified flowing bottomhole pressures at the specified datum.");
  }

  /**
   * VFP scenario configuration.
   */
  public static class VFPScenario implements Serializable {
    private static final long serialVersionUID = 1L;
    private int tableNumber;
    private double[] flowRates;
    private double[] THPs;
    private double[] waterCuts;
    private double[] GORs;
    private double[][][][][] BHPTable;
    private String description;

    public int getTableNumber() {
      return tableNumber;
    }

    public void setTableNumber(int num) {
      this.tableNumber = num;
    }

    public double[] getFlowRates() {
      return flowRates;
    }

    public void setFlowRates(double[] rates) {
      this.flowRates = rates;
    }

    public double[] getTHPs() {
      return THPs;
    }

    public void setTHPs(double[] thps) {
      this.THPs = thps;
    }

    public double[] getWaterCuts() {
      return waterCuts;
    }

    public void setWaterCuts(double[] wcs) {
      this.waterCuts = wcs;
    }

    public double[] getGORs() {
      return GORs;
    }

    public void setGORs(double[] gors) {
      this.GORs = gors;
    }

    public double[][][][][] getBHPTable() {
      return BHPTable;
    }

    public void setBHPTable(double[][][][][] table) {
      this.BHPTable = table;
    }

    public String getDescription() {
      return description;
    }

    public void setDescription(String desc) {
      this.description = desc;
    }
  }
}
