package neqsim.process.util.optimizer;

import java.io.Serializable;
import neqsim.process.automation.ProcessAutomation;
import neqsim.process.equipment.capacity.CapacityConstraint;

/**
 * Immutable installed-equipment capacity evidence for one completed process-model operating point.
 *
 * <p>
 * Normalized feasibility is deliberately separated from physical engineering evidence. Utilization and normalized
 * margin are dimensionless, while current value, applicable limit, physical margin, and required relief use
 * {@link #getPhysicalUnit()}. The snapshot contains no supplier or equipment reference and therefore remains stable
 * after later process runs, equipment mutation, Java serialization, or JPype inspection.
 * </p>
 *
 * <p>
 * Required relief is the non-negative physical change needed to reach the applicable limit at the sampled point. For a
 * maximum-directed limit it is {@code max(0, current - limit)}; for a minimum-directed limit it is
 * {@code max(0, limit - current)}. It is a constraint residual, not a capacity-sizing recommendation, production-loss
 * estimate, shadow price, economic value, or operating approval.
 * </p>
 *
 * @author NeqSim Development Team
 * @version 1.0
 */
public final class InstalledEquipmentCapacityEvidence implements Serializable {
  /** Serialization version UID. */
  private static final long serialVersionUID = 1L;

  /** Origin of a discovered capacity constraint. */
  public enum ConstraintOrigin {
    /** Constraint was registered directly on the equipment. */
    DIRECT,
    /** Constraint was generated by the equipment capacity strategy registry. */
    STRATEGY,
    /** Origin was unavailable, for example in an older compatibility path. */
    UNKNOWN
  }

  /** Direction of the applicable physical limit. */
  public enum LimitDirection {
    /** Values above the applicable limit are worse. */
    MAXIMUM,
    /** Values below the applicable limit are worse. */
    MINIMUM
  }

  /** Numerical availability of the physical and normalized snapshot. */
  public enum EvidenceStatus {
    /** Current value, applicable limit, and utilization are finite. */
    AVAILABLE,
    /** The sampled current value is non-finite. */
    NON_FINITE_CURRENT_VALUE,
    /** The applicable installed limit is non-finite or absent. */
    NON_FINITE_APPLICABLE_LIMIT,
    /** The applicable installed limit is zero or negative. */
    INVALID_APPLICABLE_LIMIT,
    /** The derived normalized utilization is non-finite. */
    NON_FINITE_UTILIZATION
  }

  /** Applicability of the evidence basis at the sampled current value. */
  public enum EvidenceApplicability {
    /** No validity range was declared. */
    NOT_ASSESSED,
    /** Current value is within the inclusive declared validity range. */
    WITHIN_VALIDITY_RANGE,
    /** Current value is outside the inclusive declared validity range. */
    OUTSIDE_VALIDITY_RANGE
  }

  private final String areaName;
  private final String equipmentName;
  private final String qualifiedEquipmentName;
  private final String equipmentClassName;
  private final String referenceDesignation;
  private final String constraintName;
  private final String qualifiedConstraintName;
  private final ConstraintOrigin constraintOrigin;
  private final CapacityConstraint.ConstraintType constraintType;
  private final CapacityConstraint.ConstraintSeverity severity;
  private final boolean enabled;
  private final LimitDirection limitDirection;
  private final double normalizedUtilization;
  private final double normalizedMargin;
  private final double currentValue;
  private final double designValue;
  private final double minimumValue;
  private final double maximumValue;
  private final double applicableLimit;
  private final double physicalMargin;
  private final double requiredRelief;
  private final double warningThreshold;
  private final String physicalUnit;
  private final String description;
  private final String dataSource;
  private final boolean confidenceSet;
  private final double confidence;
  private final boolean validityRangeSet;
  private final double validityMinimum;
  private final double validityMaximum;
  private final EvidenceApplicability evidenceApplicability;
  private final EvidenceStatus evidenceStatus;
  private final boolean feasible;

  /**
   * Creates one frozen capacity snapshot from an already sampled current value.
   *
   * @param areaName process area name
   * @param equipmentName equipment name
   * @param equipmentClassName fully qualified equipment class name
   * @param referenceDesignation IEC 81346 reference designation, or empty when unset
   * @param constraintName equipment-local constraint name
   * @param constraintOrigin direct or strategy-generated origin
   * @param constraint installed capacity definition
   * @param currentValue current value sampled exactly once by the caller
   */
  InstalledEquipmentCapacityEvidence(String areaName, String equipmentName, String equipmentClassName,
      String referenceDesignation, String constraintName, ConstraintOrigin constraintOrigin,
      CapacityConstraint constraint, double currentValue) {
    this.areaName = safeText(areaName);
    this.equipmentName = safeText(equipmentName);
    this.qualifiedEquipmentName = this.areaName + ProcessAutomation.AREA_SEPARATOR + this.equipmentName;
    this.equipmentClassName = safeText(equipmentClassName);
    this.referenceDesignation = safeText(referenceDesignation);
    this.constraintName = safeText(constraintName);
    this.qualifiedConstraintName = this.qualifiedEquipmentName + "/" + this.constraintName;
    this.constraintOrigin = constraintOrigin == null ? ConstraintOrigin.UNKNOWN : constraintOrigin;
    this.constraintType = constraint.getType();
    this.severity = constraint.getSeverity();
    this.enabled = constraint.isEnabled();
    this.limitDirection = constraint.isMinimumConstraint() ? LimitDirection.MINIMUM : LimitDirection.MAXIMUM;
    this.currentValue = currentValue;
    this.designValue = constraint.getDesignValue();
    this.minimumValue = constraint.getMinValue();
    this.maximumValue = constraint.getMaxValue();
    this.applicableLimit = constraint.getDisplayDesignValue();
    this.normalizedUtilization = constraint.getUtilization(currentValue);
    this.normalizedMargin = 1.0 - this.normalizedUtilization;
    this.physicalMargin = calculatePhysicalMargin(currentValue, this.applicableLimit, this.limitDirection);
    this.requiredRelief = Double.isFinite(this.physicalMargin) ? Math.max(0.0, -this.physicalMargin) : Double.NaN;
    this.warningThreshold = constraint.getWarningThreshold();
    this.physicalUnit = safeText(constraint.getUnit());
    this.description = safeText(constraint.getDescription());
    this.dataSource = safeDataSource(constraint.getDataSource());
    this.confidenceSet = constraint.hasConfidence();
    this.confidence = this.confidenceSet ? constraint.getConfidence() : Double.NaN;
    this.validityRangeSet = constraint.hasValidityRange();
    this.validityMinimum = this.validityRangeSet ? constraint.getValidityMinimum() : Double.NaN;
    this.validityMaximum = this.validityRangeSet ? constraint.getValidityMaximum() : Double.NaN;
    this.evidenceApplicability = determineApplicability(this.validityRangeSet, currentValue, this.validityMinimum,
        this.validityMaximum);
    this.evidenceStatus = determineStatus(currentValue, this.applicableLimit, this.normalizedUtilization);
    this.feasible = Double.isFinite(this.normalizedUtilization) && this.normalizedUtilization <= 1.0;
  }

  /** Returns empty text for null metadata. */
  private static String safeText(String value) {
    return value == null ? "" : value;
  }

  /** Returns the explicit unset provenance marker for null metadata. */
  private static String safeDataSource(String value) {
    return value == null ? "not_set" : value;
  }

  /** Calculates signed physical headroom with direction-aware sign. */
  private static double calculatePhysicalMargin(double currentValue, double applicableLimit, LimitDirection direction) {
    if (!Double.isFinite(currentValue) || !Double.isFinite(applicableLimit)) {
      return Double.NaN;
    }
    return direction == LimitDirection.MINIMUM ? currentValue - applicableLimit : applicableLimit - currentValue;
  }

  /** Determines scalar validity applicability without resampling the supplier. */
  private static EvidenceApplicability determineApplicability(boolean rangeSet, double currentValue, double minimum,
      double maximum) {
    if (!rangeSet) {
      return EvidenceApplicability.NOT_ASSESSED;
    }
    return currentValue >= minimum && currentValue <= maximum ? EvidenceApplicability.WITHIN_VALIDITY_RANGE
        : EvidenceApplicability.OUTSIDE_VALIDITY_RANGE;
  }

  /** Determines the first numerical evidence limitation. */
  private static EvidenceStatus determineStatus(double currentValue, double applicableLimit, double utilization) {
    if (!Double.isFinite(currentValue)) {
      return EvidenceStatus.NON_FINITE_CURRENT_VALUE;
    }
    if (!Double.isFinite(applicableLimit) || applicableLimit == Double.MAX_VALUE) {
      return EvidenceStatus.NON_FINITE_APPLICABLE_LIMIT;
    }
    if (applicableLimit <= 0.0) {
      return EvidenceStatus.INVALID_APPLICABLE_LIMIT;
    }
    if (!Double.isFinite(utilization)) {
      return EvidenceStatus.NON_FINITE_UTILIZATION;
    }
    return EvidenceStatus.AVAILABLE;
  }

  /** @return stable process area name */
  public String getAreaName() {
    return areaName;
  }

  /** @return stable equipment name */
  public String getEquipmentName() {
    return equipmentName;
  }

  /** @return stable area-qualified equipment name */
  public String getQualifiedEquipmentName() {
    return qualifiedEquipmentName;
  }

  /** @return fully qualified Java equipment class name */
  public String getEquipmentClassName() {
    return equipmentClassName;
  }

  /** @return IEC 81346 reference designation, or empty when unset */
  public String getReferenceDesignation() {
    return referenceDesignation;
  }

  /** @return equipment-local constraint name */
  public String getConstraintName() {
    return constraintName;
  }

  /** @return stable {@code area::equipment/constraint} identity */
  public String getQualifiedConstraintName() {
    return qualifiedConstraintName;
  }

  /** @return whether the limit came directly from equipment or from a strategy */
  public ConstraintOrigin getConstraintOrigin() {
    return constraintOrigin;
  }

  /** @return installed capacity constraint type */
  public CapacityConstraint.ConstraintType getConstraintType() {
    return constraintType;
  }

  /** @return installed capacity severity */
  public CapacityConstraint.ConstraintSeverity getSeverity() {
    return severity;
  }

  /** @return whether the source constraint was enabled */
  public boolean isEnabled() {
    return enabled;
  }

  /** @return maximum- or minimum-directed physical limit */
  public LimitDirection getLimitDirection() {
    return limitDirection;
  }

  /** @return true when values below the applicable limit are worse */
  public boolean isMinimumConstraint() {
    return limitDirection == LimitDirection.MINIMUM;
  }

  /** @return dimensionless utilization, where 1.0 is the applicable limit */
  public double getNormalizedUtilization() {
    return normalizedUtilization;
  }

  /** @return dimensionless signed margin {@code 1 - utilization} */
  public double getNormalizedMargin() {
    return normalizedMargin;
  }

  /** @return normalized utilization and margin unit, always {@code "1"} */
  public String getNormalizedUnit() {
    return "1";
  }

  /** @return sampled physical current value */
  public double getCurrentValue() {
    return currentValue;
  }

  /** @return configured design value, including the legacy sentinel for minimum constraints */
  public double getDesignValue() {
    return designValue;
  }

  /** @return configured minimum value */
  public double getMinimumValue() {
    return minimumValue;
  }

  /** @return configured maximum value */
  public double getMaximumValue() {
    return maximumValue;
  }

  /** @return physical limit used to calculate utilization */
  public double getApplicableLimit() {
    return applicableLimit;
  }

  /** @return signed direction-aware physical headroom */
  public double getPhysicalMargin() {
    return physicalMargin;
  }

  /** @return non-negative physical relief needed to reach the applicable limit */
  public double getRequiredRelief() {
    return requiredRelief;
  }

  /** @return configured dimensionless warning threshold */
  public double getWarningThreshold() {
    return warningThreshold;
  }

  /** @return unit shared by current value, applicable limit, physical margin, and relief */
  public String getPhysicalUnit() {
    return physicalUnit;
  }

  /** @return installed constraint description */
  public String getDescription() {
    return description;
  }

  /** @return source of the installed limit */
  public String getDataSource() {
    return dataSource;
  }

  /** @return true when evidence-quality confidence was explicitly assigned */
  public boolean hasConfidence() {
    return confidenceSet;
  }

  /** @return evidence-quality confidence, or NaN when unset */
  public double getConfidence() {
    return confidenceSet ? confidence : Double.NaN;
  }

  /** @return true when a scalar validity range was explicitly assigned */
  public boolean hasValidityRange() {
    return validityRangeSet;
  }

  /** @return lower inclusive validity bound in the physical unit, or NaN */
  public double getValidityMinimum() {
    return validityRangeSet ? validityMinimum : Double.NaN;
  }

  /** @return upper inclusive validity bound in the physical unit, or NaN */
  public double getValidityMaximum() {
    return validityRangeSet ? validityMaximum : Double.NaN;
  }

  /** @return applicability of the installed limit basis at the sampled current value */
  public EvidenceApplicability getEvidenceApplicability() {
    return evidenceApplicability;
  }

  /** @return numerical availability diagnostic */
  public EvidenceStatus getEvidenceStatus() {
    return evidenceStatus;
  }

  /** @return true when current value, applicable limit, and utilization are finite */
  public boolean hasFiniteEvidence() {
    return evidenceStatus == EvidenceStatus.AVAILABLE;
  }

  /** @return true when normalized utilization is finite and no greater than one */
  public boolean isFeasible() {
    return feasible;
  }

  /** @return true when finite utilization exceeds the configured warning threshold */
  public boolean isNearLimit() {
    return Double.isFinite(normalizedUtilization) && Double.isFinite(warningThreshold)
        && normalizedUtilization > warningThreshold;
  }
}
