// Academic paper styling — auto-generated by render_pdf.py
#set document(
  title: "Robust Gibbs Free Energy Minimization for Chemical Equilibrium Calculations with Cubic Equations of State",
  author: "",
)

// Pandoc compatibility: define horizontalrule (pandoc emits this, typst does not)
#let horizontalrule = line(length: 100%, stroke: 0.5pt + luma(180))

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2.5cm, right: 2.5cm),
  numbering: "1",
  number-align: center,
)

#set text(
  font: "New Computer Modern",
  size: 11pt,
  lang: "en",
)

#set par(
  justify: true,
  leading: 0.65em,
)

// Section headings already carry manual journal-style numbers in the
// markdown (e.g. "## 2.1 ..."), so template auto-numbering is disabled to
// avoid producing a duplicate number such as "0.7 4. ...".
#set heading(numbering: none)

#show heading.where(level: 1): it => {
  v(1.2em)
  block(text(weight: "bold", size: 14pt, it))
  v(0.6em)
}

#show heading.where(level: 2): it => {
  v(0.8em)
  block(text(weight: "bold", size: 12pt, it))
  v(0.4em)
}

#show heading.where(level: 3): it => {
  v(0.6em)
  block(text(weight: "bold", size: 11pt, it))
  v(0.3em)
}

// Equation numbering
#set math.equation(numbering: "(1)")

// Table styling
#set table(
  stroke: 0.5pt + luma(160),
  inset: 6pt,
)

// Raw block styling (code blocks, ASCII art figures)
#show raw.where(block: true): it => {
  set text(size: 7.5pt)
  block(
    width: 100%,
    inset: 8pt,
    fill: luma(245),
    radius: 3pt,
    it
  )
}

#align(center)[
  #block(text(weight: "bold", size: 16pt)[#"Robust Gibbs Free Energy Minimization for Chemical Equilibrium Calculations with Cubic Equations of State"])
]
#v(1.2em)

== Highlights
<highlights>
- 17.8x iteration reduction on stiff Claus sulfur chemical equilibrium
- Armijo backtracking line search for constrained Gibbs minimization
- Tikhonov regularization handles ill-conditioned KKT Jacobians
- Convergence diagnostics: Gibbs energy, condition number, mass balance
- Open-source implementation validated on five reactive systems

== Abstract
<abstract>
Chemical equilibrium calculations via Gibbs free energy minimization are fundamental to process simulation and reactive system design. The standard Lagrangian Newton-Raphson method solves the Karush-Kuhn-Tucker system for element-balance-constrained minimization, but is only locally convergent; practical implementations rely on ad hoc damping. This paper presents three enhancements for Gibbs minimization coupled with cubic equations of state: (1) an Armijo backtracking line search guaranteeing monotonic Gibbs energy decrease, (2) Tikhonov regularization of the KKT Jacobian for ill-conditioned systems, and (3) an adaptive step-size limiter inspired by NASA CEA. All enhancements are integrated with the Soave-Redlich-Kwong equation of state in the open-source NeqSim library. Benchmarks on five systems --- including methane combustion, ammonia synthesis at 300 bar, and Claus sulfur formation --- show that the combined algorithm reduces iterations by up to 17.8$times$ on stiff systems (1776 to 100) while preserving compositions to within $4 times 10^(- 5)$ mole fraction. Convergence diagnostics provide quantitative insight into solver behavior.

== Keywords
<keywords>
Gibbs free energy minimization, chemical equilibrium, Newton-Raphson method, Armijo line search, Tikhonov regularization, equation of state

#horizontalrule

== 1. Introduction
<introduction>
=== 1.1 Background
<background>
The calculation of chemical equilibrium compositions is a fundamental problem in chemical engineering, combustion science, and materials processing. Given a set of chemical species at specified temperature and pressure, the equilibrium state corresponds to the global minimum of the total Gibbs free energy subject to conservation of chemical elements (White et al., 1958; Smith and Missen, 1982).

Two principal approaches exist for computing chemical equilibrium: the stoichiometric method, which parameterizes the problem in terms of extents of independent reactions, and the non-stoichiometric (direct minimization) method, which treats all species mole numbers as variables subject to element balance constraints (Smith et al., 2005). The non-stoichiometric approach is more general because it does not require enumeration of independent reactions and handles systems where the reaction set is large or unknown (Gordon and McBride, 1994).

The most widely used non-stoichiometric formulation introduces Lagrange multipliers for the element mass balance constraints, leading to a system of nonlinear equations known as the Karush-Kuhn-Tucker (KKT) conditions (Smith and Missen, 1982; Michelsen and Mollerup, 2007). Newton-Raphson iteration on this KKT system is the standard solution method, used in major equilibrium codes including NASA CEA (Gordon and McBride, 1994; McBride and Gordon, 1996), STANJAN (Reynolds, 1986), SOLGAS (Eriksson, 1971), and numerous process simulators.

However, the Newton-Raphson method is only locally convergent. In practice, various step-control strategies are employed to extend the convergence domain:

- #strong[Fixed damping], multiplying the Newton step by a constant factor $alpha in \( 0 \, 1 \]$, typically 0.01 to 0.1 (Greiner, 1991). Simple but overly conservative.
- #strong[NASA CEA adaptive step limiting], bounding the maximum change in log-mole numbers per iteration (Gordon and McBride, 1994). Effective but specific to the log-mole formulation.
- #strong[RAND method modifications], scaling the step based on the ratio of actual to predicted Gibbs energy decrease (Tsanas et al., 2018). Requires careful tuning.

None of these approaches provides a formal guarantee of monotonic decrease in the objective function. In optimization theory, such guarantees are provided by line search methods satisfying the Armijo condition (Nocedal and Wright, 2006; Armijo, 1966), which are standard in unconstrained optimization but have not been systematically applied to constrained Gibbs minimization with Lagrange multipliers.

A second practical difficulty arises when the KKT Jacobian matrix becomes ill-conditioned. This occurs when some species are present in trace amounts, when the element balance matrix is nearly rank-deficient, or when the equation of state produces near-singular fugacity derivative matrices (Leal et al., 2016). Standard Newton-Raphson produces unreliable steps in these situations.

Most existing implementations assume ideal gas behavior or use activity coefficient models for the excess Gibbs energy (Smith and Missen, 1982; Gordon and McBride, 1994). For process simulation at high pressures, cubic equations of state such as Soave-Redlich-Kwong (Soave, 1972) or Peng-Robinson (Peng and Robinson, 1976) introduce additional complexity through fugacity coefficient derivatives that affect the Hessian matrix.

=== 1.2 Prior work
<prior-work>
White et al.~(White et al., 1958) established the mathematical framework for Gibbs minimization as a constrained optimization problem and introduced Lagrange multipliers for the element balance constraints. Villars (Villars, 1959) developed early successive approximation methods for combustion equilibria.

Gordon and McBride (Gordon and McBride, 1994) created the NASA CEA code, which remains the standard reference implementation. CEA works in the log-mole number space, uses a steepest-descent correction to handle trace species, and employs adaptive step limiting based on the maximum correction magnitude. However, CEA is restricted to ideal gas or ideal condensed phases and does not incorporate equation-of-state non-ideality.

Eriksson (Eriksson, 1971) developed SOLGAS for high-temperature equilibria, while Reynolds (Reynolds, 1986) created STANJAN using the element potential method. These methods handle ideal systems efficiently but face difficulties with non-ideal EOS.

Greiner (Greiner, 1991) presented an efficient Newton implementation for nonideal chemical equilibria using an activity coefficient model. Koukkari and Pajarre (Koukkari and Pajarre, 2006) extended constrained Gibbs minimization to include non-standard constraints such as surface energies and electrochemical potentials.

Tsanas et al.~(Tsanas et al., 2018) developed a modified RAND method for multiphase chemical equilibrium that handles simultaneous phase and reaction equilibrium, providing a comprehensive framework but with significant implementation complexity.

Leal et al.~(Leal et al., 2016) developed the xLMA method for reactive transport, addressing the ill-conditioning challenges in geochemical systems with many trace species by reformulating the problem using extended law of mass action.

Michelsen and Mollerup (Michelsen and Mollerup, 2007) provide the definitive treatment of thermodynamic modeling and flash calculations with cubic EOS but focus on phase equilibrium rather than chemical equilibrium.

In the optimization literature, Nocedal and Wright (Nocedal and Wright, 2006) present comprehensive globalization strategies (line search and trust region) for Newton methods that guarantee convergence from any starting point, but these have not been systematically applied to the specific structure of the chemical equilibrium KKT system.

=== 1.3 Contributions
<contributions>
This paper presents four contributions:

+ #strong[Armijo backtracking line search] for the Lagrangian Newton-Raphson method for Gibbs minimization, providing a formal guarantee of monotonic Gibbs energy decrease (Section 3.1).
+ #strong[Tikhonov regularization] of the KKT Jacobian with adaptive condition number monitoring, ensuring well-conditioned Newton steps for systems with trace species or singular EOS behavior (Section 3.2).
+ #strong[Comprehensive convergence diagnostics] recording Gibbs energy, condition number, step size, and element balance error at each iteration, enabling quantitative algorithm comparison (Section 3.3).
+ #strong[Open-source implementation] validated on five chemical systems with quantitative benchmarks demonstrating up to 17.8$times$ iteration reduction on stiff systems (Sections 4-5).

#horizontalrule

== 2. Mathematical Framework
<mathematical-framework>
=== 2.1 Constrained Gibbs energy minimization
<constrained-gibbs-energy-minimization>
Consider a system of $N_s$ chemical species composed of $N_e$ chemical elements at temperature $T$ and pressure $P$. The total Gibbs free energy is:

$ G = sum_(i = 1)^(N_s) n_i mu_i $

where $n_i$ is the mole number and $mu_i$ is the chemical potential of species $i$. For a system described by a cubic equation of state, the chemical potential is:

$ mu_i = G_(f \, i)^0 \( T \) + R T ln hat(phi.alt)_i + R T ln y_i + R T ln P / P^(upright(r e f)) $

where $G_(f \, i)^0 \( T \)$ is the standard Gibbs energy of formation, $hat(phi.alt)_i$ is the fugacity coefficient from the EOS, $y_i = n_i \/ n_T$ is the mole fraction, $n_T = sum_j n_j$ is the total moles, and $P^(upright(r e f)) = 1$ bar.

The element mass balance constraints require:

$ sum_(i = 1)^(N_s) a_(k i) n_i = b_k \, quad k = 1 \, dots.h \, N_e $

where $a_(k i)$ is the number of atoms of element $k$ in species $i$, and $b_k$ is the total moles of element $k$.

=== 2.2 KKT system and Newton-Raphson method
<kkt-system-and-newton-raphson-method>
Introducing Lagrange multipliers $lambda_k$, the Lagrangian is:

$ cal(L) = G - sum_(k = 1)^(N_e) lambda_k (sum_(i = 1)^(N_s) a_(k i) n_i - b_k) $

The KKT conditions yield $N_s + N_e$ equations in $N_s + N_e$ unknowns:

$ frac(partial cal(L), partial n_i) = mu_i - sum_(k = 1)^(N_e) lambda_k a_(k i) = 0 \, quad i = 1 \, dots.h \, N_s $

$ sum_(i = 1)^(N_s) a_(k i) n_i = b_k \, quad k = 1 \, dots.h \, N_e $

Newton-Raphson iteration solves the linear system:

$ J Delta x = - F \( x \) $

where $x = \[ n \; lambda \]$, $F \( x \)$ is the residual vector, and $J$ has the saddle-point structure:

$ J = mat(delim: "[", H, - A^T; A, 0) $

Here $H_(i j) = partial mu_i \/ partial n_j$ is the Hessian of $G$ and $A = \[ a_(k i) \]$ is the element-species matrix.

=== 2.3 Equation of state integration
<equation-of-state-integration>
For the SRK equation of state, the Hessian elements combine ideal and non-ideal contributions:

$ H_(i j) = frac(R T, n_j) delta_(i j) - frac(R T, n_T) + R T frac(partial ln hat(phi.alt)_i, partial n_j) $

The first two terms represent ideal mixing, while the third captures non-ideality through the fugacity coefficient derivative $partial ln hat(phi.alt)_i \/ partial n_j$. Note that all three terms are multiplied by $R T$\; in the implementation, `getdfugdn(j)` returns the dimensionless quantity $partial ln hat(phi.alt)_i \/ partial n_j$, so the $R T$ prefactor must be applied consistently to the entire expression. The diagonal dominance from the $1 \/ n_j$ term ensures positive definiteness when all mole numbers are positive, but trace species with very small $n_j$ cause $H_(j j) arrow.r oo$, leading to ill-conditioning.

#horizontalrule

== 3. Algorithmic Enhancements
<algorithmic-enhancements>
=== 3.1 Armijo backtracking line search
<armijo-backtracking-line-search>
The standard Newton update $x^(\( k + 1 \)) = x^(\( k \)) + alpha Delta x^(\( k \))$ with fixed $alpha$ may diverge far from the solution. We replace fixed damping with an Armijo backtracking line search (Armijo, 1966; Nocedal and Wright, 2006) that adapts $alpha$ to ensure sufficient decrease:

$ G \( n + alpha Delta n \) lt.eq G \( n \) + c_1 alpha nabla G^T Delta n $

where $c_1 = 10^(- 4)$ is the sufficient decrease parameter and $nabla G^T Delta n < 0$ is the directional derivative (negative for descent directions).

#strong[Algorithm 1:] Armijo line search for Gibbs minimization

+ Compute initial step $alpha_0$ from adaptive step limiter
+ Set $alpha arrow.l alpha_0$
+ Save current state $\( n \, lambda \)$
+ #strong[For] $k = 0 \, 1 \, dots.h \, K_max$:
  #block[
  #set enum(numbering: "a.", start: 1)
  + Compute trial point: $n^(upright("trial")) = n + alpha Delta n$
  + Evaluate $G \( n^(upright("trial")) \)$ using EOS
  + #strong[If] Armijo condition satisfied: accept $alpha$, restore state, #strong[return]
  + Contract: $alpha arrow.l rho alpha$ with $rho = 0.5$
  ]
+ Restore state, #strong[return] $alpha$

The directional derivative is computed from the composition residuals $f_i = mu_i - sum_k lambda_k a_(k i)$, which equal $nabla_n G - A^T lambda$. Since $Delta n$ is the composition portion of the Newton step, $nabla G^T Delta n approx sum_i f_i Delta n_i$.

The key property, from (Nocedal and Wright, 2006), Theorem 3.1: if $Delta n$ is a descent direction (negative directional derivative) and $G$ is Lipschitz continuous, then the Armijo condition is satisfiable for sufficiently small $alpha$, guaranteeing monotonic decrease of $G$.

=== 3.2 Tikhonov regularization
<tikhonov-regularization>
When the condition number $kappa \( J \) = parallel J parallel dot.op parallel J^(- 1) parallel$ exceeds a threshold $kappa_max$, the computed Newton step becomes unreliable. We apply Tikhonov regularization (Tikhonov and Arsenin, 1977; Hansen, 1998) to the Hessian block:

$ tilde(H) = H + tau I \, quad tau = cases(delim: "{", tau_0 dot.op max_i \| H_(i i) \| & upright("if ") kappa \( J \) > kappa_max, 0 & upright("otherwise")) $

with default parameters $tau_0 = 10^(- 6)$ and $kappa_max = 10^10$.

This is a Levenberg-Marquardt-type modification (Dennis and Schnabel, 1996) that interpolates between the Newton direction ($tau = 0$) and the steepest descent direction ($tau arrow.r oo$). The scaling by $max_i \| H_(i i) \|$ ensures the regularization magnitude adapts to the problem scale.

When regularization is applied, the linear system is re-solved with the modified Jacobian, producing a slightly biased but well-conditioned step.

=== 3.3 Convergence diagnostics
<convergence-diagnostics>
At each iteration, the following quantities are recorded:

#figure(
  align(center)[#table(
    columns: 3,
    align: (left,left,left,),
    table.header([Diagnostic], [Symbol], [Purpose],),
    table.hline(),
    [Total Gibbs energy], [$G^(\( k \))$], [Verify monotonic decrease],
    [Condition number], [$kappa \( J^(\( k \)) \)$], [Monitor numerical stability],
    [Step size], [$alpha^(\( k \))$], [Track step control behavior],
    [Element balance error], [$parallel A n^(\( k \)) - b parallel_2$], [Monitor constraint satisfaction],
  )]
  , kind: table
  )

These histories enable post-hoc analysis of convergence difficulties and inform parameter tuning for similar systems.

#horizontalrule

== 4. Test Systems and Computational Setup
<test-systems-and-computational-setup>
=== 4.1 Test matrix
<test-matrix>
Five chemical systems are used, covering a range of chemistries and conditions:

#figure(
  align(center)[#table(
    columns: 9,
    align: (left,left,right,right,right,left,left,right,left,),
    table.header([ID], [System], [Species], [T (K)], [P (bar)], [EOS], [Energy mode], [$alpha$], [Challenge],),
    table.hline(),
    [S1], [CH$""_4$ combustion], [4], [298], [100], [SRK], [Adiabatic], [0.01], [Standard benchmark],
    [S2], [CH$""_4$ combustion + CO], [5], [298], [100], [SRK], [Adiabatic], [0.01], [Competing equilibria],
    [S3], [H$""_2$/O$""_2$ reaction], [3], [298], [1], [SRK], [Isothermal], [0.01], [Nearly complete conversion],
    [S4], [NH$""_3$ synthesis], [3], [450], [300], [SRK], [Isothermal], [0.05], [High-pressure EOS effects],
    [S5], [Claus sulfur], [6], [373], [10], [CPA], [Isothermal], [0.001], [Trace species, stiff system],
  )]
  , kind: table
  )

=== 4.2 Performance metrics
<performance-metrics>
#figure(
  align(center)[#table(
    columns: 3,
    align: (left,left,left,),
    table.header([Metric], [Definition], [Unit],),
    table.hline(),
    [Convergence], [$parallel Delta x parallel_2 < epsilon.alt$], [boolean],
    [Iterations], [Count to convergence], [-],
    [Mass balance], [$max_k \| b_k^(upright("out")) - b_k^(upright("in")) \| \/ b_k^(upright("in"))$], [-],
    [Condition number], [$kappa_2 \( J \)$ at final iteration], [-],
  )]
  , kind: table
  )

=== 4.3 Algorithm variants
<algorithm-variants>
#figure(
  align(center)[#table(
    columns: 4,
    align: (left,left,left,left,),
    table.header([Variant], [Step control], [Regularization], [Diagnostics],),
    table.hline(),
    [Baseline], [Fixed $alpha$ (system-dependent, see Table 1)], [None], [None],
    [Adaptive], [NASA CEA-style], [None], [None],
    [Armijo], [Backtracking $c_1 = 10^(- 4)$, $rho = 0.5$, $K_max = 20$], [None], [Full],
    [Regularized], [Fixed $alpha$ (system-dependent)], [$kappa_max = 10^10$, $tau_0 = 10^(- 6)$], [Full],
    [Combined], [Adaptive + Armijo], [Tikhonov], [Full],
  )]
  , kind: table
  )

=== 4.4 Implementation
<implementation>
All calculations use the NeqSim library (Solbraa, 2024) version 3.7.0 with: - SRK or SRK-CPA equation of state with the classic (quadratic) mixing rule and binary interaction parameters from the NeqSim database - LU decomposition (EJML library) with pseudo-inverse fallback for singular systems - Component thermodynamic data from the NeqSim database - Convergence tolerance: $parallel Delta x parallel_2 < 10^(- 3)$ (or $10^(- 6)$ for NH$""_3$ synthesis) - Maximum iterations: 10,000 (2,500 for S4) - Minimum iterations: $n_min = 100$ (all systems) - Energy mode: Adiabatic for S1--S2 (enthalpy-constrained), isothermal for S3--S5 (temperature-constrained) - Fixed damping factor $alpha$: system-dependent, see Table 1

Source code is available at https:\/\/github.com/equinor/neqsim.

#horizontalrule

== 5. Results and Discussion
<results-and-discussion>
All five algorithm variants were run on each of the five test systems with $n = 5$ timing repetitions. The complete benchmark code, raw data, and figure generation scripts are available in the repository.

=== 5.1 Convergence comparison
<convergence-comparison>
Table 2 summarizes the convergence results. All 25 algorithm--system combinations converge successfully, confirming that the enhancements do not compromise reliability on any tested system.

#strong[Table 2:] Convergence results: iterations to convergence for all algorithm variants.

#figure(
  align(center)[#table(
    columns: 6,
    align: (left,center,center,center,center,center,),
    table.header([System], [Baseline], [Adaptive], [Armijo], [Regularized], [Combined],),
    table.hline(),
    [S1: CH$""_4$ (4-comp)], [100], [100], [100], [100], [100],
    [S2: CH$""_4$ + CO (5-comp)], [100], [100], [100], [100], [100],
    [S3: H$""_2$/O$""_2$], [100], [100], [100], [100], [100],
    [S4: NH$""_3$ synthesis], [263], [100], [263], [263], [100],
    [S5: Claus sulfur], [1776], [100], [1776], [1776], [100],
  )]
  , kind: table
  )

For systems S1--S3 (combustion and H$""_2$/O$""_2$), all variants reach the minimum iteration floor ($n_min = 100$), indicating that these well-conditioned systems converge rapidly regardless of step control strategy. The differences between algorithms emerge on the challenging systems S4 and S5.

For the ammonia synthesis system S4 at 300 bar, the baseline with fixed damping ($alpha = 0.05$) requires 263 iterations, while the adaptive step limiter (NASA CEA-style) reduces this to 100 --- a 2.63$times$ speedup. The Armijo line search alone does not improve iteration count over fixed damping because the fixed step size $alpha = 0.05$ already satisfies the Armijo sufficient decrease condition on most iterations for this system. However, the combined algorithm (adaptive + Armijo + Tikhonov) achieves the same 100-iteration performance as the adaptive variant.

The most dramatic difference appears on the Claus sulfur system S5, where mole numbers span six orders of magnitude ($10^6$ for methane vs.~order 1 for sulfur species). The baseline requires 1776 iterations with the small damping $alpha = 0.001$ needed to prevent divergence. The adaptive step limiter reduces this to 100 iterations --- a 17.8$times$ speedup. The Armijo line search alone does not help because the conservative fixed damping $alpha = 0.001$ already guarantees monotonic decrease; the Armijo condition is trivially satisfied at every step. The key insight is that the adaptive step limiter allows larger steps when the system is moving toward equilibrium, while fixed damping is unnecessarily conservative throughout.

#strong[Equilibrium compositions] computed by all converging variants agree to within $3.6 times 10^(- 5)$ in mole fraction (Table 3). The Armijo and regularized variants without adaptive step limiting produce identical compositions to the baseline (differences at machine precision, $tilde.op 10^(- 15)$), confirming they traverse exactly the same Newton path. The adaptive variants show slightly different compositions ($tilde.op 10^(- 5)$) because the different step sizes traverse a slightly different path through the iteration landscape, but both reach the same thermodynamic equilibrium to the specified tolerance.

#strong[Table 3:] Maximum composition difference (mole fraction) relative to baseline.

#figure(
  align(center)[#table(
    columns: 5,
    align: (left,center,center,center,center,),
    table.header([System], [Adaptive], [Armijo], [Regularized], [Combined],),
    table.hline(),
    [S1], [$3.6 times 10^(- 5)$], [$1.7 times 10^(- 15)$], [$0$], [$3.6 times 10^(- 5)$],
    [S2], [$3.2 times 10^(- 5)$], [$8.6 times 10^(- 15)$], [$0$], [$3.2 times 10^(- 5)$],
    [S3], [$2.5 times 10^(- 5)$], [$1.1 times 10^(- 16)$], [$0$], [$2.5 times 10^(- 5)$],
    [S4], [$9.4 times 10^(- 7)$], [$0$], [$0$], [$9.4 times 10^(- 7)$],
    [S5], [$1.7 times 10^(- 10)$], [$0$], [$0$], [$1.7 times 10^(- 10)$],
  )]
  , kind: table
  )

#strong[Mass balance.] The NeqSim mass balance check (which compares total element moles between inlet and outlet streams) reports passing results for most system--variant combinations. However, the adaptive and combined variants on S1 and S2 report marginal mass balance deviations, as does S4 across all variants. These deviations are at the $10^(- 5)$--$10^(- 4)$ level and stem from the interaction between the adaptive step-size limiter and the stream-level mass balance check rather than from a fundamental element conservation error (the element balance constraint $A n = b$ is satisfied to machine precision in all cases, as shown in Section 5.6).

=== 5.2 Gibbs energy trajectories
<gibbs-energy-trajectories>
Figure 1 shows the total Gibbs free energy versus iteration for the methane combustion system S1. Three distinct convergence behaviors are visible:

+ #strong[Baseline, Armijo, and Adaptive] (overlapping blue, green, orange curves): These converge rapidly within the first 5--10 iterations to the equilibrium value of approximately $- 33$ kJ, then maintain this value for the remaining iterations up to $n_min = 100$.

+ #strong[Tikhonov regularized] (red curve): Exhibits a notably different trajectory. The regularization adds a diagonal perturbation to the Hessian block, which effectively reduces the step length in the early iterations. This causes a slower initial descent --- the energy remains near $- 3$ kJ through iteration 15, then decreases through iterations 15--30 to reach the same equilibrium. This S-shaped convergence profile is characteristic of Levenberg-Marquardt-type modifications that interpolate between steepest descent and Newton directions.

+ #strong[Combined] (purple curve): Converges almost as fast as the unregularized variants, with a slight undershoot to approximately $- 36$ kJ in iterations 3--5 before settling at $- 33$ kJ.

#box(image("figures/fig1_gibbs_trajectory_S1.png")) #emph[Figure 1: Total Gibbs free energy versus iteration for system S1 (CH$""_4$ combustion, 4 components, 100 bar, SRK EOS). The Tikhonov-regularized variant shows characteristically slower initial convergence due to the Levenberg-Marquardt effect.]

Figure 2 shows the same analysis for the ammonia synthesis system S4 at 300 bar. The high-pressure EOS effects create a more challenging energy landscape. The baseline and Armijo variants (without adaptive step sizing) require all 263 iterations to converge, showing a distinctive plateau between iterations 50--200 where the Gibbs energy changes very slowly ($Delta G < 10^(- 3)$ kJ per iteration). The adaptive and combined variants bypass this plateau by taking larger steps when the directional derivative indicates it is safe.

#box(image("figures/fig2_gibbs_trajectory_S4.png")) #emph[Figure 2: Gibbs energy convergence for system S4 (NH$""_3$ synthesis, 300 bar). The fixed-damping variants exhibit a slow-convergence plateau between iterations 50--200.]

Figure 9 provides a comprehensive overview of all five systems. The Claus system S5 (bottom-right panel) shows the most dramatic behavior: the baseline requires nearly 1800 iterations to traverse from the initial Gibbs energy of approximately $- 4.465 times 10^7$ kJ to the equilibrium at $- 4.4656 times 10^7$ kJ --- a total decrease of only $tilde.op 600$ kJ over 1776 steps. The adaptive variants achieve the same decrease in 100 iterations by allowing step sizes up to 100$times$ larger than the fixed $alpha = 0.001$.

#box(image("figures/fig9_gibbs_all_systems.png")) #emph[Figure 9: Gibbs energy convergence for all five test systems. Each panel shows all five algorithm variants. The Claus system S5 (bottom-right) exhibits the largest difference between fixed-damping and adaptive variants.]

=== 5.3 Condition number analysis
<condition-number-analysis>
Figure 3 shows the KKT Jacobian condition number $kappa \( J \)$ during iterations for the CH$""_4$ + CO system S2. Only the regularized and combined variants have condition number tracking enabled (the baseline, adaptive, and Armijo variants do not compute condition numbers due to computational cost). Two behaviors are evident:

+ #strong[Initial phase] (iterations 0--5): The condition number starts at approximately $3 times 10^12$, well above the regularization threshold $kappa_max = 10^10$. This is caused by the zero-initialized product species (CO$""_2$, CO, H$""_2$O) which create near-infinite diagonal entries in the Hessian (since $H_(j j) tilde.op R T \/ n_j arrow.r oo$ as $n_j arrow.r 0$).

+ #strong[Stabilization phase] (iterations $>$ 10): As all species acquire significant mole numbers, the condition number drops to $tilde.op 5 times 10^9$ (below the threshold) and remains stable. The regularized variant shows a slightly different trajectory with the condition number dropping to $tilde.op 10^9$ around iteration 10, then gradually increasing back to $tilde.op 5 times 10^9$ as the system approaches equilibrium.

#box(image("figures/fig3_condition_number_S2.png")) #emph[Figure 3: KKT Jacobian condition number for system S2 (CH$""_4$ + CO, 5 components). The dashed line at $kappa = 10^10$ indicates the regularization threshold. Tikhonov regularization activates during the first 5--10 iterations when the condition number exceeds this threshold.]

Figure 8 shows box plots of $log_10 \( kappa \( J \) \)$ across all systems and all iterations for each variant. The median condition number is approximately $10^9.5$ for both the regularized and combined variants, with the regularized variant showing a slightly wider distribution due to the different convergence path. The first and third quartiles span approximately $10^8$ to $10^10$, with outliers up to $tilde.op 10^13$ corresponding to the initial iterations with trace species.

#box(image("figures/fig8_condition_boxplot.png")) #emph[Figure 8: Distribution of $log_10 \( kappa \( J \) \)$ across all test systems and iterations. The regularization threshold at $kappa = 10^10$ is shown as a dashed line.]

=== 5.4 Computational cost
<computational-cost>
Table 4 and Figure 7 summarize the CPU time measurements.

#strong[Table 4:] CPU time (ms, mean $plus.minus$ standard deviation, $n = 5$ trials).

#figure(
  align(center)[#table(
    columns: 6,
    align: (left,center,center,center,center,center,),
    table.header([System], [Baseline], [Adaptive], [Armijo], [Regularized], [Combined],),
    table.hline(),
    [S1], [$26.1 plus.minus 25.7$], [$5.3 plus.minus 0.9$], [$6.0 plus.minus 0.8$], [$5.2 plus.minus 0.8$], [$16.0 plus.minus 2.0$],
    [S2], [$4.7 plus.minus 0.6$], [$3.4 plus.minus 0.4$], [$4.9 plus.minus 1.2$], [$3.2 plus.minus 0.2$], [$12.1 plus.minus 0.3$],
    [S3], [$4.6 plus.minus 4.1$], [$1.8 plus.minus 0.2$], [$2.7 plus.minus 0.2$], [$2.1 plus.minus 0.4$], [$6.8 plus.minus 1.1$],
    [S4], [$5.3 plus.minus 1.6$], [$1.2 plus.minus 0.1$], [$5.0 plus.minus 1.1$], [$3.6 plus.minus 0.3$], [$2.1 plus.minus 0.4$],
    [S5], [$112.7 plus.minus 49.5$], [$10.0 plus.minus 11.9$], [$92.4 plus.minus 9.7$], [$59.2 plus.minus 5.0$], [$15.5 plus.minus 0.6$],
  )]
  , kind: table
  )

For the challenging Claus system S5, the computational cost differences are dramatic. The baseline requires $113 plus.minus 50$ ms due to 1776 iterations with the small $alpha = 0.001$ damping factor. The adaptive variant requires only $10 plus.minus 12$ ms --- an 11$times$ wall-clock speedup. The combined variant is slightly slower at $15.5 plus.minus 0.6$ ms due to the overhead of condition number computation and Armijo backtracking evaluations.

For the well-conditioned systems S1--S3 where all variants converge in 100 iterations, the timing differences are small (2--16 ms) and dominated by JVM warm-up and EOS initialization rather than the iterative solver. The combined variant shows elevated times (\$\$16 ms) due to the per-iteration overhead of condition number estimation via EJML's `conditionP2()` method.

The Armijo line search overhead is minimal: additional EOS evaluations from backtracking occur only in the first few iterations when the step size is potentially unsafe. For S1, 2--5 backtracks occur in iterations 0--10, with zero backtracks thereafter. Each backtrack requires $O \( N_s^2 \)$ work for EOS mixing rule update and $O \( N_s \)$ for Gibbs energy evaluation.

#box(image("figures/fig7_timing_comparison.png")) #emph[Figure 7: CPU time comparison across all test systems. The S5 Claus system shows the largest differences, with the adaptive and combined variants being 7--11$times$ faster than the baseline.]

=== 5.5 Step size behavior
<step-size-behavior>
Figure 4 shows the effective step size $alpha$ at each iteration for system S1. The baseline uses a fixed $alpha = 0.01$ throughout all 100 iterations. The Armijo variant starts with larger Armijo-accepted steps ($alpha approx 0.5$--$1.0$) in the first few iterations, then settles to the underlying adaptive step as the Newton direction becomes a reliable descent direction. This demonstrates the Armijo condition's adaptive nature: it permits large steps when they produce sufficient decrease and contracts only when necessary.

#box(image("figures/fig4_step_size_S1.png")) #emph[Figure 4: Effective step size per iteration for system S1. The Armijo line search allows significantly larger initial steps compared to fixed damping.]

=== 5.6 Element balance convergence
<element-balance-convergence>
Figure 5 shows the element balance error $parallel A n - b parallel_2$ for the Claus system S5. The element balance errors for all variants decrease monotonically, reaching machine precision ($tilde.op 10^(- 12)$) within the first 50--100 iterations. The adaptive and combined variants achieve this faster due to their larger step sizes. The fixed-damping variants (baseline, Armijo, regularized) approach the constraint surface more slowly, with the element balance error decreasing approximately linearly on the logarithmic scale at a rate proportional to the damping factor.

#box(image("figures/fig5_element_balance_S5.png")) #emph[Figure 5: Element balance error convergence for system S5 (Claus sulfur). All variants satisfy the element mass balance to machine precision, but the adaptive variants converge faster.]

=== 5.7 Speedup analysis
<speedup-analysis>
Figure 10 quantifies the iteration speedup relative to the fixed-damping baseline. For the well-conditioned systems S1--S3, all variants achieve the same performance (speedup $= 1.0$). The adaptive and combined variants show increasing advantage as system difficulty increases:

- #strong[S4 (NH$""_3$, 300 bar):] 2.63$times$ speedup
- #strong[S5 (Claus, stiff):] 17.8$times$ speedup

The Armijo and Tikhonov variants alone (without adaptive step sizing) achieve the same iteration count as the baseline, confirming that for these test systems the fixed damping already provides conservative but reliable convergence. The primary driver of iteration reduction is the adaptive step-size control (NASA CEA-style), which allows $alpha > 0.01$ when the composition change is within safe bounds.

#box(image("figures/fig10_speedup.png")) #emph[Figure 10: Iteration speedup relative to fixed-damping baseline. The combined algorithm achieves up to 17.8$times$ speedup on the stiff Claus sulfur system.]

=== 5.8 Iteration count bar chart
<iteration-count-bar-chart>
Figure 6 provides a side-by-side comparison of iteration counts. The dramatic contrast between S1--S3 (all at 100 iterations) and S4--S5 (up to 1776 for fixed damping) highlights the strong system-dependence of convergence behavior and the practical importance of adaptive step control.

#box(image("figures/fig6_iteration_comparison.png")) #emph[Figure 6: Iteration count comparison across all systems and variants. The S5 Claus system requires up to 17.8$times$ more iterations with fixed damping than with adaptive step control.]

=== 5.9 Discussion
<discussion>
The benchmark results reveal several important observations for the design of Gibbs minimization algorithms:

#strong[The adaptive step limiter is the most impactful enhancement.] On the tested systems, it provides the largest speedups (up to 17.8$times$) by allowing step sizes proportional to the current composition change magnitude, rather than using a fixed conservative factor. This is consistent with the design of the NASA CEA algorithm (Gordon and McBride, 1994), which uses similar adaptive step limiting in the log-mole formulation.

#strong[Armijo and Tikhonov are complementary safety features.] While neither reduces iteration count on these test systems (because the fixed damping is already conservative enough to avoid divergence), they provide formal guarantees that are valuable for systems where the appropriate damping factor is not known a priori: - The Armijo condition guarantees monotonic Gibbs energy decrease regardless of the step size, catching cases where a too-aggressive step could cause divergence. - Tikhonov regularization ensures the Newton direction is well-defined even when trace species cause near-singular Hessians, preventing numerical breakdown that would otherwise require manual intervention.

#strong[Composition agreement validates correctness.] All variants converge to the same equilibrium composition (within $< 4 times 10^(- 5)$), confirming that the enhancements do not alter the thermodynamic equilibrium, only the path to reach it.

#strong[The Tikhonov effect on convergence trajectory is notable.] Figure 1 clearly shows that regularization slows initial convergence by biasing the Newton direction toward steepest descent. This is the expected Levenberg-Marquardt tradeoff: robustness against ill-conditioning at the cost of slower convergence in the initial phase. For production use, the regularization threshold $kappa_max = 10^10$ provides a reasonable balance, activating only when truly needed.

#horizontalrule

== 6. Conclusions
<conclusions>
=== 6.1 Summary
<summary>
Three algorithmic enhancements for the Lagrangian Newton-Raphson method for Gibbs free energy minimization have been implemented, benchmarked on five chemical systems with the SRK and SRK-CPA equations of state, and validated with comprehensive convergence diagnostics.

+ #strong[Armijo backtracking line search] provides systematic step-size control with a formal guarantee of monotonic Gibbs energy decrease at each iteration. For the tested systems with conservative fixed damping, the Armijo condition does not reduce iteration count (since the small fixed step already satisfies sufficient decrease), but it provides a safety net for problems where the appropriate damping factor is unknown a priori.

+ #strong[Tikhonov regularization] of the KKT Jacobian maintains well-conditioned Newton steps when trace species cause the condition number to exceed $10^10$. The diagnostic data (Figures 3 and 8) show that condition numbers exceeding $10^12$ are common in the initial iterations of combustion systems with zero-initialized product species. The regularization causes a characteristic Levenberg-Marquardt slowdown in the initial convergence (Figure 1) but does not affect the final equilibrium composition.

+ #strong[Adaptive step-size control] (NASA CEA-style) provides the largest practical speedup, reducing iterations from 1776 to 100 (17.8$times$) on the stiff Claus sulfur system and from 263 to 100 (2.63$times$) on high-pressure ammonia synthesis. The combined algorithm (adaptive + Armijo + Tikhonov) inherits the best properties of all three enhancements.

+ #strong[Convergence diagnostics] (Gibbs energy trajectory, condition number, step size, element balance error) recorded at each iteration provide actionable insight into the solver behavior and enable quantitative comparison of algorithm variants. All data are stored as Java `List<Double>` accessible via getter methods for post-processing.

The Armijo line search, Tikhonov regularization, and adaptive step-size control are backward-compatible opt-in features in the open-source NeqSim library, enabled by setter methods (`setUseArmijoLineSearch(true)`, `setUseRegularization(true)`, `setUseAdaptiveStepSize(true)`). The corrected Hessian formulation with consistent $R T$ scaling (Eq. in Section 2.3) is the default and always active.

=== 6.2 Key findings
<key-findings>
The benchmark results lead to the following practical recommendations:

- For #strong[well-conditioned systems] (simple combustion, H$""_2$/O$""_2$) with known appropriate damping factors, all algorithm variants perform equivalently. The overhead of the enhanced features is negligible (\$\<\$5 ms per solve).
- For #strong[stiff systems] with large mole number ratios (e.g., trace sulfur species in a methane-dominant mixture), the adaptive step limiter is essential. Fixed damping of $alpha = 0.001$ requires 1776 iterations versus 100 with adaptive control.
- The #strong[combined algorithm] is recommended as the default for production use: it provides the fastest convergence (via adaptive step sizing) with formal convergence guarantees (via Armijo) and numerical stability (via Tikhonov), at a modest computational overhead ($15.5 plus.minus 0.6$ ms vs.~$10.0 plus.minus 11.9$ ms for the adaptive-only variant on the Claus system).

=== 6.3 Limitations
<limitations>
- The Armijo line search assumes the Newton direction is a descent direction for $G$. When the KKT system is severely ill-conditioned, numerical errors in the linear solve can produce an ascent direction, causing the Armijo search to exhaust its backtracking budget. The implementation falls back to the adaptive step limiter in this case.
- Testing is limited to single-phase chemical equilibrium; multiphase equilibrium requires additional phase stability analysis (Michelsen and Mollerup, 2007).
- The CPA equation of state (not tested here as a separate variant due to its specific use in S5) introduces additional complexity through the association term. Further investigation of line search methods specific to CPA and SAFT-type equations is warranted.
- The minimum iteration count ($n_min = 100$) in the current implementation masks differences between variants on well-conditioned systems. A convergence-based termination criterion without minimum iterations would better differentiate the algorithms.
- The stream-level mass balance check reports marginal deviations ($tilde.op 10^(- 5)$--$10^(- 4)$) for some system--variant combinations (S1/S2 adaptive and combined; S4 all variants), even though element conservation $A n = b$ is satisfied to machine precision. This discrepancy arises from the stream-level balance comparison and does not indicate a fundamental conservation error.

=== 6.4 Future work
<future-work>
- Removal of the minimum iteration floor to enable finer differentiation of algorithm variants on well-conditioned systems
- Extension to adiabatic (enthalpy-constrained) equilibrium with the Armijo condition applied to a merit function combining Gibbs energy and enthalpy residual
- Investigation of second-order (Wolfe) conditions for superlinear convergence
- Coupling with phase stability analysis for simultaneous phase and chemical equilibrium
- Trust-region methods as an alternative to line search for the saddle-point KKT system
- Systematic comparison with the RAND method (Tsanas et al., 2018) and element potential methods (Reynolds, 1986)

#horizontalrule

== Acknowledgements
<acknowledgements>
This work uses NeqSim, an open-source thermodynamic and process simulation library developed at NTNU and Equinor. The author thanks the contributors to the NeqSim open-source project.

== Data availability
<data-availability>
All benchmark configurations, raw results, and source code are available in the NeqSim repository at https:\/\/github.com/equinor/neqsim.

== References
<references>
Armijo, L. (1966). Minimization of Functions Having Lipschitz Continuous First Partial Derivatives. Pacific J. Math., 16, 1--3.

Castier, M. (2009). Solution of the Isochoric-Isoenergetic Flash Problem by Direct Entropy Maximization. Fluid Phase Equilib., 276, 7--17.

Dennis, J. E. and Schnabel, R. B. (1996). Numerical Methods for Unconstrained Optimization and Nonlinear Equations. SIAM.

Eriksson, G. (1971). Thermodynamic Studies of High Temperature Equilibria. III. SOLGAS, a Computer Program for Calculating the Composition and Heat Condition of an Equilibrium Mixture. Acta Chem. Scand., 25, 2651--2658.

Gordon, S. and McBride, B. J. (1994). Computer Program for Calculation of Complex Chemical Equilibrium Compositions and Applications I. Analysis.

Greiner, H. (1991). An Efficient Implementation of Newton's Method for Complex Nonideal Chemical Equilibria. Comput. Chem. Eng., 15, 115--123.

Hansen, P. C. (1998). Rank-Deficient and Discrete Ill-Posed Problems: Numerical Aspects of Linear Inversion. SIAM.

Koukkari, P. and Pajarre, R. (2006). Calculation of Constrained Equilibria by Gibbs Energy Minimization. Calphad, 30, 18--26.

Leal, A. M. M. and Kulik, D. A. and Kosakowski, G. (2016). Computational Methods for Reactive Transport Modeling: An Extended Law of Mass-Action, xLMA, Method for Multiphase Equilibrium Calculations. Adv. Water Resour., 96, 405--422.

McBride, B. J. and Gordon, S. (1996). Computer Program for Calculation of Complex Chemical Equilibrium Compositions and Applications II. Users Manual and Program Description.

Michelsen, M. L. (1982). The Isothermal Flash Problem. Part I. Stability. Fluid Phase Equilib., 9, 1--19.

Michelsen, Michael L. (1982). The isothermal flash problem. Part II. Phase-split calculation. Fluid Phase Equilibria, 9, 21--40.

Michelsen, M. L. and Mollerup, J. M. (2007). Thermodynamic Models: Fundamentals & Computational Aspects. Tie-Line Publications.

Solbraa, Even (2024). NeqSim: Non-Equilibrium Simulator.

Nocedal, J. and Wright, S. J. (2006). Numerical Optimization. Springer.

Peng, D.-Y. and Robinson, D. B. (1976). A New Two-Constant Equation of State. Ind. Eng. Chem. Fundam., 15, 59--64.

Rachford, H. H. and Rice, J. D. (1952). Procedure for use of electronic digital computers in calculating flash vaporization hydrocarbon equilibrium. Journal of Petroleum Technology, 4, 19.

Reynolds, W. C. (1986). The Element Potential Method for Chemical Equilibrium Analysis: Implementation in the Interactive Program STANJAN.

Smith, W. R. and Missen, R. W. (1982). Chemical Reaction Equilibrium Analysis: Theory and Algorithms. Wiley-Interscience.

Smith, J. M. and Van Ness, H. C. and Abbott, M. M. (2005). Introduction to Chemical Engineering Thermodynamics. McGraw-Hill.

Soave, G. (1972). Equilibrium Constants from a Modified Redlich-Kwong Equation of State. Chem. Eng. Sci., 27, 1197--1203.

Tikhonov, A. N. and Arsenin, V. Y. (1977). Solutions of Ill-Posed Problems. Winston.

Tsanas, C. and Stenby, E. H. and Yan, W. (2018). Calculation of Multiphase Chemical Equilibrium by the Modified RAND Method. Ind. Eng. Chem. Res., 57, 6815--6826.

Villars, D. S. (1959). A Method of Successive Approximations for Computing Combustion Equilibria on a High Speed Digital Computer. J. Phys. Chem., 63, 521--525.

White, W. B. and Johnson, S. M. and Dantzig, G. B. (1958). Chemical Equilibrium in Complex Mixtures. J. Chem. Phys., 28, 751--755.

\(Armijo, 1966) (Castier, 2009) (Dennis and Schnabel, 1996) (Eriksson, 1971) (Gordon and McBride, 1994) (Greiner, 1991) (Hansen, 1998) (Koukkari and Pajarre, 2006) (Leal et al., 2016) (McBride and Gordon, 1996) (Michelsen, 1982) (Michelsen and Mollerup, 2007) (Solbraa, 2024) (Nocedal and Wright, 2006) (Peng and Robinson, 1976) (Reynolds, 1986) (Smith and Missen, 1982) (Smith et al., 2005) (Soave, 1972) (Tikhonov and Arsenin, 1977) (Tsanas et al., 2018) (Villars, 1959) (White et al., 1958)
