name: Build maven java 8

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pomJava8.xml
      # - run: mkdir staging && cp target/*.jar staging
      # - uses: actions/upload-artifact@v2
      #   with:
      #    name: jarfiles
      #    path: staging
