name: Release to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
      - name: Set up Java 17 environment
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Get the version number from the pushed tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_OUTPUT"
      - name: Deploy to GitHub Package Registry
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn --settings settings.xml deploy
