name: Dependabot Metrics Badge

on:
  schedule:
    - cron: '0 * * * *'  # hourly refresh
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/security-metrics.yml'

permissions:
  contents: write  # need write to commit updated JSON
  actions: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Dependabot Alerts
        id: dependabot
        run: |
          curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts?state=open&per_page=100" > dependabot.json
          echo "count=$(jq '[.[] | select(.state=="open")] | length' dependabot.json)" >> $GITHUB_OUTPUT

      - name: Compose dependabot-only JSON
        run: |
          dep=${{ steps.dependabot.outputs.count }}
          color="green"
          if [ "$dep" -gt 0 ]; then color="orange"; fi
          if [ "$dep" -gt 5 ]; then color="red"; fi
          cat > dependabot-metrics.json <<EOF
          {
            "schemaVersion": 1,
            "label": "dep vulns",
            "message": "${dep}",
            "color": "${color}"
          }
          EOF

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: dependabot-metrics
          path: dependabot-metrics.json
