name: Security Metrics Badge

on:
  schedule:
    - cron: '0 * * * *'  # hourly refresh
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/security-metrics.yml'

permissions:
  contents: read
  security-events: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch CodeQL Alerts
        id: codeql
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?state=open" > codeql.json
          echo "count=$(jq '[.[] | select(.state=="open")] | length' codeql.json)" >> $GITHUB_OUTPUT

      - name: Fetch Dependabot Alerts
        id: dependabot
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts?state=open" > dependabot.json
          echo "count=$(jq '[.[] | select(.state=="open")] | length' dependabot.json)" >> $GITHUB_OUTPUT

      - name: Compose metrics JSON
        run: |
          total=$((${ { steps.codeql.outputs.count } } + ${ { steps.dependabot.outputs.count } }))
          # Secrets scanning alerts API requires GHAS enterprise token; skipping if unavailable.
          cat > security-metrics.json <<EOF
          {
            "schemaVersion": 1,
            "label": "security",
            "message": "alerts ${total}",
            "color": "blue",
            "details": {
              "codeql_open": "${{ steps.codeql.outputs.count }}",
              "dependabot_open": "${{ steps.dependabot.outputs.count }}"
            }
          }
          EOF

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: security-metrics
          path: security-metrics.json

      - name: Commit metrics JSON
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p .github/metrics
          cp security-metrics.json .github/metrics/security-metrics.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/metrics/security-metrics.json
          if git diff --cached --quiet; then
            echo "No changes in metrics JSON"
          else
            git commit -m "chore: update security metrics badge JSON"
            git push origin HEAD:master
          fi
